### ISSUE TITLE
mt76x2: missing packet length in txinfo

### ISSUE THREAD

**Issue by MrBan** [openwrt/mt76#102]
Hi,

I've noticed that for _mt76x2_ the `pkt length` field of the `tx_info` (bits [13:0]) is not filled. Is it normal?

**Comment by kabakaev** [comment]
@MrBan, where is this piece?
I experience some weird issue on MT7612E: small packets are transmitted normally (say, DHCP), but a first big packet (e.g. HTTP) freezes the card. 

I'm wondering whether it may be related to your finding?

**Comment by nbd168** [comment]
@kabakaev your issue should be fixed now. @MrBan I don't think it's needed. Everything seems to be working just fine.
