### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by zuowanbushiwo** [openwrt/mt76#103]
I want to use the nearest mt76  on  openwrt  chaos_calmer Branch ， but  build failed， info：
/openwrt/build_dir/target-mipsel_24kec+dsp_uClibc-0.9.33.2/linux-ramips_mt7688/mt76-2016-06-17/mt76.h:295:14: error: comparison between 'enum ieee80211_band' and 'enum nl80211_band' [-Werror=enum-compare]
  if (c->band == NL80211_BAND_2GHZ)
              ^
cc1: all warnings being treated as errors

I probe openwrt  master branch MT76 MakeFile  to  openwrt  chaos_calmer branch , because openwrt  chaos_calmer branch MT76 can support MT7688， what should I do？
Thanks!!

**Comment by psyborg55** [comment]
update mac80211 package to newer revision
