### ISSUE TITLE
MT7603 wifi driver : how to isolate clients connected to AP?

### ISSUE THREAD

**Issue by amulpatel** [openwrt/mt76#106]
Hello team,

I am using MT7621 processor along with MT7603 wifi chip similar to ZBT device.
I want to isolate clients using MAC address. i.e. ebtales rules can block communication with MAC address.

But i don't receive two wifi clients communication packets on ebtables (and on tcpdump on wireless interface ) hence I am not able to block client communication using MAC address.

Please note that over Ethernet I can see client communication packet on tcpdump and can block using ebtables but not on wireless access point.

Does any one know how I can get packets on tcpdump and ebtables so that rules can be apply?

The issue seems only on mediatek because same i could achieve using hostapd and mac80211 driver on TP link adopter.

I dont find category for MT7621 hence selected MT2523.

Thanks,
Amul Patel

**Comment by nbd168** [comment]
You can enable AP isolation in the configuration, then clients won't be able to talk to each other directly anymore. If you enable hairpin mode on the bridge ports, they can talk again, but you can filter with ebtables.
