### ISSUE TITLE
MT76 in STA mode and how to edit wifi AP beacon for MT76

### ISSUE THREAD

**Issue by jaminck** [openwrt/mt76#109]
Hi, 
I would like to know if MT76 wifi driver works correctly in STA mode?
I would like to edit the beacon sent by the driver to add some information in order to be easily recognisable by a wifi client. How may I do this with MT76 driver?

**Comment by nbd168** [comment]
Yes, the driver works in STA mode. Beacon handling is not part of the driver, but handled by mac80211 and hostapd/wpa_supplicant, I suggest you look there.
