### ISSUE TITLE
Division by zero in minstreal

### ISSUE THREAD

**Issue by kristrev** [openwrt/mt76#119]
I have a custom board with an MT7621 PCI card. EEPROM, etc. is correct and loaded, but when connecting an iPhone 7 Plus I get the following error. The error usually appears when I push data at quite high bandwidth (100Mbit/s+), but sometimes appear right away when the device is connected.

I replaced the MT7621 with cards using ath9k and 10k, and did not see the error. So it seems to be triggered by something in mt76.

Error msg:
[ 3469.546024] Division by zero in kernel.
[ 3469.549879] CPU: 0 PID: 0 Comm: swapper/0 Not tainted 4.9.49 #0
[ 3469.555812] Hardware name: Marvell Armada 380/385 (Device Tree)
[ 3469.561755] [<c0015f50>] (unwind_backtrace) from [<c0012168>] (show_stack+0x10/0x14)
[ 3469.569523] [<c0012168>] (show_stack) from [<c020a9a0>] (dump_stack+0x7c/0x9c)
[ 3469.576766] [<c020a9a0>] (dump_stack) from [<c0209614>] (Ldiv0+0x8/0x10)
[ 3469.583543] [<c0209614>] (Ldiv0) from [<bf2017d0>] (minstrel_ht_get_tp_avg+0x3c/0x90 [mac80211])
[ 3469.592411] [<bf2017d0>] (minstrel_ht_get_tp_avg [mac80211]) from [<bf201958>] (minstrel_ht_get_expected_throughput+0x134/0x6d0 [mac80211])
[ 3469.605018] [<bf201958>] (minstrel_ht_get_expected_throughput [mac80211]) from [<bf201b40>] (minstrel_ht_get_expected_throughput+0x31c/0x6d0 [mac80211])
[ 3469.618755] [<bf201b40>] (minstrel_ht_get_expected_throughput [mac80211]) from [<bf20230c>] (minstrel_ht_tx_status+0x418/0x884 [mac80211])
[ 3469.631272] [<bf20230c>] (minstrel_ht_tx_status [mac80211]) from [<bf1bd5f8>] (ieee80211_tx_status+0x364/0x67c [mac80211])
[ 3469.642381] [<bf1bd5f8>] (ieee80211_tx_status [mac80211]) from [<bf228408>] (mt76_dma_tx_cleanup+0x1f8/0x2f8 [mt76])
[ 3469.652944] [<bf228408>] (mt76_dma_tx_cleanup [mt76]) from [<bf23a224>] (mt76x2_tx_tasklet+0x28/0xa8 [mt76x2e])
[ 3469.663069] [<bf23a224>] (mt76x2_tx_tasklet [mt76x2e]) from [<c002d9c0>] (tasklet_action+0x8c/0xe8)
[ 3469.672139] [<c002d9c0>] (tasklet_action) from [<c002d158>] (__do_softirq+0xd0/0x204)
[ 3469.679989] [<c002d158>] (__do_softirq) from [<c002d510>] (irq_exit+0x94/0xb8)
[ 3469.687231] [<c002d510>] (irq_exit) from [<c0061a50>] (__handle_domain_irq+0x90/0xb4)
[ 3469.695082] [<c0061a50>] (__handle_domain_irq) from [<c0009428>] (gic_handle_irq+0x50/0x94)
[ 3469.703454] [<c0009428>] (gic_handle_irq) from [<c0012bcc>] (__irq_svc+0x6c/0x90)
[ 3469.710953] Exception stack(0xc0613f60 to 0xc0613fa8)
[ 3469.716017] 3f60: 00000001 00000000 00000000 c001b0c0 00000000 c0612000 c0614fe4 00000001
[ 3469.724215] 3f80: c060f168 00000000 c0613fb8 00000001 00000000 c0613fb0 c000f7c8 c000f7cc
[ 3469.732410] 3fa0: 60000013 ffffffff
[ 3469.735909] [<c0012bcc>] (__irq_svc) from [<c000f7cc>] (arch_cpu_idle+0x2c/0x38)
[ 3469.743328] [<c000f7cc>] (arch_cpu_idle) from [<c005adac>] (cpu_startup_entry+0xf0/0x19c)
[ 3469.751530] [<c005adac>] (cpu_startup_entry) from [<c05ccc14>] (start_kernel+0x35c/0x3d8)

My work-around so far is to only update avg_ampdu_len if value is larger than zero, but that is probably not a very good solution.

**Comment by nbd168** [comment]
Fixed in 37654d704772512065cd28b007342758c2a0f14a
