### ISSUE TITLE
2.4G client not working

### ISSUE THREAD

**Issue by ptpt52** [openwrt/mt76#127]
[  361.138253] br-lan: port 3(wlan1-1) entered disabled state
[  361.657493] wlan1: deauthenticating from 04:a1:51:8c:ab:a2 by local choice (Reason: 3=DEAUTH_LEAVING)
[  362.093308] ieee80211 phy1: rt2x00queue_flush_queue: Warning - Queue 2 failed to flush
[  362.484444] ieee80211 phy1: rt2x00queue_flush_queue: Warning - Queue 2 failed to flush
[  363.234208] ieee80211 phy1: rt2x00queue_flush_queue: Warning - Queue 2 failed to flush
[  363.918451] ieee80211 phy1: rt2x00queue_flush_queue: Warning - Queue 2 failed to flush
[  366.850111] IPv6: ADDRCONF(NETDEV_UP): wlan1: link is not ready
[  369.146637] wlan1: authenticate with 04:a1:51:8c:ab:a2
[  369.158666] wlan1: send auth to 04:a1:51:8c:ab:a2 (try 1/3)
[  369.165455] wlan1: authenticated
[  369.169717] wlan1: associate with 04:a1:51:8c:ab:a2 (try 1/3)
[  369.176673] wlan1: RX AssocResp from 04:a1:51:8c:ab:a2 (capab=0x431 status=0 aid=3)
[  369.184915] wlan1: associated
[  369.189932] IPv6: ADDRCONF(NETDEV_CHANGE): wlan1: link becomes ready
[  369.450649] ieee80211 phy1: rt2x00queue_write_tx_frame: Error - Arrived at non-free entry in the non-full queue 2
[  369.450649] Please file bug report to http://rt2x00.serialmonkey.com

**Comment by nbd168** [comment]
You're using the rt2x00 driver, not mt76.
