### ISSUE TITLE
Router Lenovo Y1 RAMIPS  MT7620 Chaos Calmer 15.05.1

### ISSUE THREAD

**Issue by mrzahz** [openwrt/mt76#130]
reboot command send the router to freeze/ halt mode. 
power off ON to put in operational mode.

**Comment by BertLammers** [comment]
I am experiencing the exact same issue on a LinkIt Smart 7688 (MT7688) device. I use the latest Lede snapshot (55e70c8).

**Comment by nbd168** [comment]
This has nothing to do with the mt76 driver though.
