### ISSUE TITLE
tx power low 

### ISSUE THREAD

**Issue by Rascal6** [openwrt/mt76#132]
ZBT-WG3526   MT7612E +  MT7603E, last trunc

on native firmware tx power was higher

5 GHz does not exceed 11 dbm
![image](https://user-images.githubusercontent.com/24735402/33872350-56e39228-df38-11e7-9260-90d8ee90d4ad.png)

2.4GHz does not exceed 0 dbm
![image](https://user-images.githubusercontent.com/24735402/33872382-7df7db9e-df38-11e7-8bf9-9f985d5779e9.png)

**Comment by nbd168** [comment]
The 20 dBm reported by that other firmware is fake. The hardware is not capable of doing 20 dBm. Reported power is now lower, because I fixed reporting the real target tx power of the device.

**Comment by Rascal6** [comment]
maximally 11?
when there was a native firmware, the power was much better

**Comment by Rascal6** [comment]
2,4 - max 0 ?

**Comment by nbd168** [comment]
For 2.4 GHz, reporting is not implemented yet. From what I can tell, 11 dBm is the limit for VHT80. I have such a device myself, and I've run some tests with both the proprietary driver and my reimplementation. Signal strength on the client looks exactly the same in both cases.
