### ISSUE TITLE
Data buffer not 16 bytes aligned

### ISSUE THREAD

**Issue by MaFeSa** [openwrt/mt76#156]
Xiaomi 3G (MT7603 - MT7612) - OpenWrt SNAPSHOT r6297-9a0cc49 

Every time I transfer large files using 5 GHz between clients speed transfert decreases and on kernel log there are many (even over 100 times) "Data buffer not 16 bytes aligned"
Thanks

```
[ 9576.288069] Data buffer not 16 bytes aligned: 8cb004b8
[ 9576.337872] Data buffer not 16 bytes aligned: 8cb001f8
[ 9576.347530] Data buffer not 16 bytes aligned: 8cb00328
[ 9576.361787] Data buffer not 16 bytes aligned: 8cb00068
[ 9576.444747] Data buffer not 16 bytes aligned: 8cb00078
[ 9576.453296] Data buffer not 16 bytes aligned: 8cb000b8
[ 9576.462692] Data buffer not 16 bytes aligned: 8cb00288
[ 9576.472247] Data buffer not 16 bytes aligned: 8cb00068
[ 9576.488434] Data buffer not 16 bytes aligned: 8cb00268
[ 9576.496996] Data buffer not 16 bytes aligned: 8cb002f8
[ 9576.505507] Data buffer not 16 bytes aligned: 8cb000e8
[ 9576.519563] Data buffer not 16 bytes aligned: 8cb000d8
[ 9576.530198] Data buffer not 16 bytes aligned: 8cb003d8
[ 9576.552339] Data buffer not 16 bytes aligned: 8cb00078
...

```

**Comment by nbd168** [comment]
If I grep for this error message, I end up in a printk in the nand driver. I don't think this is mt76 related at all.

**Comment by MaFeSa** [comment]
OK, thanks for your help!

**Comment by kofec** [comment]
@MaFeSa 
mcaptur - compile latest nbd168 branch where: 
Here find a build with latest master (https://github.com/openwrt/openwrt/commit/d8655868ca04d12ad5ed36e26fc63d61b076e33d9)
latest MT76 commit (https://github.com/openwrt/mt76/commit/cda627fd8feffdadfcd692fbb6d823d455aa19ab12)
using kernel 4.14 and Gcc 7.3 (O2 optimization)
You can test HW offload by using (can add to firewall.user)

iptables -I FORWARD 1 -m conntrack --ctstate RELATED,ESTABLISHED -j FLOWOFFLOAD

Maybe you want to try ?
