### ISSUE TITLE
MT7628 multi SSID crash

### ISSUE THREAD

**Issue by baohavan** [openwrt/mt76#158]
Device: Tplink C50 v3
Lede rev: r6433-4fd8722056

Edit: 2018/04/09
Stable with andoird, but usually unstable with Ipad (IOS 10)

**Comment by loyasto** [comment]
I met the same problem. Did you solve it？

**Comment by ffrediani** [comment]
Have exactly the same issue with the same radio. I initially thought it was something broader related to 2.4 Ghz radio but from the recent tests indicate it's related to multi SSID.

**Comment by nbd168** [comment]
Please try the latest version from OpenWrt master, I pushed some more fixes.

**Comment by ffrediani** [comment]
Hello. Has this been fixed completely ? Since my last test it was broken. Has anyone else tested after the latest commit if multiple SSID works fine now without any issues ?

**Comment by goraelec** [comment]
Hello.

Unfortunately, I have no way to tell. I reverted to stock fw, which has
superior Wi-Fi performance
