### ISSUE TITLE
Cannot change mac address using uci (or similar tools) in openwrt for mt76x2e on the Xiaomi 3G device

### ISSUE THREAD

**Issue by d1b** [openwrt/mt76#164]
Hi, it appears that configuring a mac address for the mt76x2e interface with openwrt[0] on the Xiaomi 3G device currently requires [modifying the Factory partition](https://forum.lede-project.org/t/xiaomi-wifi-router-3g/5377/621) in order to allow clients to connect.

[0] snapshot release r6565-fd588db

**Comment by nasbdh9** [comment]
You can use breed ( a bootloaderHe can modify many of R3G's parameters, including mac address ) After refreshing, you need to set a `xiaomi.r3g.bootfw` environment variable in the breath and set the value to `2` to specify boot from kernel1.

**Comment by d1b** [comment]
@nasbdh9 okay.

**Comment by d1b** [comment]
The issue appears to still be present.

**Comment by psyborg55** [comment]
how does your issue relates to the wifi driver?

**Comment by d1b** [comment]
Assuming that there isn't a bug in uci (and similar tools) then there is a bug in the wifi driver.

**Comment by d1b** [comment]
It doesn't appear to have been fixed in 19.07.0-rc2.

**Comment by d1b** [comment]
This seemingly has been resolved.
