### ISSUE TITLE
 Issues with 4.14.37 using  mt7615-for-mt7623-linux-4.14.23.ko

### ISSUE THREAD

**Issue by BGFWDev** [openwrt/mt76#171]
On 4.14.37, we see

root@OpenWrt:~# uname -a
Linux OpenWrt 4.14.37 #0 SMP PREEMPT Mon May 7 16:54:23 2018 armv7l GNU/Linux
root@OpenWrt:~# insmod mt7615-for-mt7623-linux-4.14.23.ko
failed to insert mt7615-for-mt7623-linux-4.14.23.ko
root@OpenWrt:~# dmesg | grep mt7615
[ 3736.709495] mt7615: module license 'Proprietary' taints kernel.
[ 3736.726064] mt7615: Unknown symbol vfs_write (err 0)
[ 3736.731117] mt7615: Unknown symbol vfs_read (err 0)

In the 4.14.x series, these VFS symbols were unexported; drivers should be using kernel_read() and kernel_write().  An example of the same issue from ZFS for Linux development is given by

https://github.com/zfsonlinux/spl/issues/656

How can we address this issue? How can driver updats be kept up to date with the latest kernel? Can source without full firmware be accomodated to allow driver updates to match the kernel revision byt the customer?

**Comment by lukasz1992** [comment]
This repo is **only** for mt76 driver, so please stop spamming.
