### ISSUE TITLE
Airtime fairness in mt76

### ISSUE THREAD

**Issue by lePereT** [openwrt/mt76#175]
Hi, I see that airtime fairness is landing on some (ath9k) chipsets. Is this feasible and planned for mt76?

**Comment by lukasz1992** [comment]
There are some commits, but not even added to trunk.

You could try with manually adding that patches:

https://github.com/openwrt/mt76/commit/29460609fc05561a054aea79909c82e62fb1bd2a
https://git.openwrt.org/?p=openwrt/staging/nbd.git;a=commit;h=debe9f9a7332177c47958c5aa355e9c748edb1ba

**Comment by lukasz1992** [comment]
@nbd168 Do we have any news here?

**Comment by JFtico** [comment]
@nbd168 What is the current status of this?

Does 18.06.4 include support for this?

Thanks in advance

**Comment by nbd168** [comment]
Airtime fairness is included in 19.07 and master branch.
