### ISSUE TITLE
MT7601U crashes on insert

### ISSUE THREAD

**Issue by jsantala** [openwrt/mt76#177]
The platform is VoCore2, MT7601U USB stick inserted via USB OTG port on a device, other USB wifi sticks work just fine:
 -----------------------------------------------------
 OpenWrt SNAPSHOT, r7060-7a20c7a
 -----------------------------------------------------
root@xxx:/# uname -a
Linux xxx 4.14.44 #0 Wed May 30 04:38:19 2018 mips GNU/Linux
root@xxx:/#
[ 4319.322222] usb 1-1: new high-speed USB device number 4 using ehci-platform
[ 4319.702314] usb 1-1: reset high-speed USB device number 4 using ehci-platform
[ 4319.925880] mt7601u 1-1:1.0: ASIC revision: 76010001 MAC revision: 76010500
[ 4320.122356] mt7601u 1-1:1.0: Firmware Version: 0.1.00 Build: 7640 Build time: 201302052146____
[ 4320.580732] mt7601u 1-1:1.0: EEPROM ver:0c fae:00
[ 4320.764488] mt7601u 1-1:1.0: Error: RX urb failed:-71
[ 4320.769668] mt7601u 1-1:1.0: Error: MCU resp urb failed:-71
[ 4320.775387] mt7601u 1-1:1.0: Error: MCU resp evt:0 seq:5-4!
[ 4320.784979] mt7601u 1-1:1.0: Error: RX urb failed:-71
[ 4320.790245] mt7601u 1-1:1.0: Error: MCU resp urb failed:-71
[ 4320.795942] mt7601u 1-1:1.0: Error: MCU resp evt:0 seq:5-4!
[ 4320.805351] mt7601u 1-1:1.0: Error: RX urb failed:-71
[ 4320.810617] mt7601u 1-1:1.0: Error: MCU resp urb failed:-71
[ 4320.816314] mt7601u 1-1:1.0: Error: MCU resp evt:0 seq:5-4!
[ 4320.825726] mt7601u 1-1:1.0: Error: RX urb failed:-71
[ 4320.830992] mt7601u 1-1:1.0: Error: MCU resp urb failed:-71
[ 4320.836692] mt7601u 1-1:1.0: Error: MCU resp evt:0 seq:5-4!
[ 4320.846101] mt7601u 1-1:1.0: Error: RX urb failed:-71
[ 4320.851365] mt7601u 1-1:1.0: Error: MCU resp urb failed:-71
[ 4320.857068] mt7601u 1-1:1.0: Error: MCU resp evt:0 seq:5-4!
[ 4320.862737] mt7601u 1-1:1.0: Error: mt7601u_mcu_wait_resp timed out
[ 4321.172156] mt7601u 1-1:1.0: Vendor request req:07 off:0080 failed:-71
[ 4321.482134] mt7601u 1-1:1.0: Vendor request req:02 off:0080 failed:-71
[ 4321.792123] mt7601u 1-1:1.0: Vendor request req:02 off:0080 failed:-71
[ 4321.798838] CPU 0 Unable to handle kernel paging request at virtual address 00000000, epc == 00000000, ra == 801e2e4c
[ 4321.809633] Oops[#1]:
[ 4321.811945] CPU: 0 PID: 122 Comm: kworker/0:1 Not tainted 4.14.44 #0
[ 4321.818477] Workqueue: usb_hub_wq hub_port_debounce [usbcore]
[ 4321.824308] task: 87d80000 task.stack: 87d62000
[ 4321.828895] $ 0   : 00000000 00000001 00000000 00000001
[ 4321.834201] $ 4   : 870fbc20 870ed490 00000001 873be000
[ 4321.839505] $ 8   : 000548b7 000548b6 873bd000 877fd180
[ 4321.844810] $12   : 00000001 00200010 00000000 20726f64
[ 4321.850116] $16   : 870ed480 87d63b08 00000003 870fbc20
[ 4321.855422] $20   : 87d63b08 804a0000 0000000d 87fdbae8
[ 4321.860726] $24   : 00000001 801d1ce8                  
[ 4321.866031] $28   : 87d62000 87d63af8 870fb610 801e2e4c
[ 4321.871338] Hi    : 00000001
[ 4321.874254] Lo    : 00000000
[ 4321.877172] epc   : 00000000   (null)
[ 4321.880901] ra    : 801e2e4c release_nodes+0x1ec/0x200
[ 4321.886105] Status: 1100e403	KERNEL EXL IE 
[ 4321.890356] Cause : 10800008 (ExcCode 02)
[ 4321.894416] BadVA : 00000000
[ 4321.897334] PrId  : 00019655 (MIPS 24KEc)
[ 4321.901393] Modules linked in: pppoe ppp_async cdc_mbim rtl8192cu rtl8192c_common rtl_usb rt2800usb rt2800lib rndis_host pppox ppp_generic nf_conntrack_ipv6 iptable_nat ipt_REJECT ipt_MASQUERADE huawei_cdc_ncm cdc_subset cdc_ncm cdc_ether xt_time xt_tcpudp xt_nat xt_multiport xt_mark xt_mac xt_limit xt_comment xt_TCPMSS xt_REDIRECT xt_LOG xt_FLOWOFFLOAD usbserial usbnet slhc rtlwifi rt2x00usb rt2x00lib nf_reject_ipv4 nf_nat_redirect nf_nat_masquerade_ipv4 nf_conntrack_ipv4 nf_nat_ipv4 nf_nat nf_log_ipv4 nf_flow_table_hw nf_flow_table nf_defrag_ipv6 nf_defrag_ipv4 nf_conntrack_rtcache nf_conntrack mt76x2e mt7603e mt7601u mt76 mac80211 iptable_mangle iptable_filter ip_tables crc_itu_t crc_ccitt cdc_wdm cdc_acm ledtrig_usbport batman_adv libcrc32c cfg80211 compat ip6t_REJECT nf_reject_ipv6 nf_log_ipv6
[ 4321.973297]  nf_log_common ip6table_mangle ip6table_filter ip6_tables x_tables mmc_block usb_storage mtk_sd mmc_core leds_gpio ohci_platform ohci_hcd ehci_platform sd_mod scsi_mod ehci_hcd gpio_button_hotplug usbcore nls_base usb_common crc16 mii crc32c_generic crypto_hash
[ 4321.997873] Process kworker/0:1 (pid: 122, threadinfo=87d62000, task=87d80000, tls=00000000)
[ 4322.006420] Stack : 00000000 876daed0 804a0000 801db9f8 870ed480 870ed280 870fbc20 ffffff6f
[ 4322.014908]         00000000 876daed0 804a0000 801df2c0 870fbc20 00000001 87693c70 801df580
[ 4322.023391]         00000000 87d63b90 801df540 00000001 87693c70 80430000 00000000 801dd7c4
[ 4322.031875]         87d63b58 87d63b58 00000001 873be000 87e0195c 8750f2b4 870fbc20 87fdbb00
[ 4322.040360]         870fbc54 801df114 00000000 80331698 873be000 801dd550 870fbc20 00000001
[ 4322.048845]         ...
[ 4322.051327] Call Trace:
[ 4322.051331] 
[ 4322.055342] [<801db9f8>] device_links_no_driver+0x28/0x40
[ 4322.060859] [<801df2c0>] driver_probe_device+0x158/0x2c4
[ 4322.066266] [<801df580>] __device_attach_driver+0x40/0xd8
[ 4322.071753] [<801df540>] __device_attach_driver+0x0/0xd8
[ 4322.077153] [<801dd7c4>] bus_for_each_drv+0x9c/0xac
[ 4322.082165] [<801df114>] __device_attach+0xac/0xe4
[ 4322.087037] [<80331698>] cleanup_uevent_env+0x0/0x8
[ 4322.091999] [<801dd550>] bus_get+0x28/0x3c
[ 4322.096187] [<801de5c4>] bus_probe_device+0x3c/0xb0
[ 4322.101171] [<801dc8a8>] device_add+0x444/0x550
[ 4322.105827] [<87fca13c>] usb_control_msg+0xdc/0x36c [usbcore]
[ 4322.111668] [<801da654>] get_device+0x18/0x30
[ 4322.116183] [<87fcc848>] usb_set_configuration+0x5e8/0x6cc [usbcore]
[ 4322.122742] [<87fe0000>] scsi_cmd_get_serial+0x0/0x2c [scsi_mod]
[ 4322.128896] [<87fd5790>] usb_choose_configuration+0x230/0x378 [usbcore]
[ 4322.135654] [<801df364>] driver_probe_device+0x1fc/0x2c4
[ 4322.141064] [<801df580>] __device_attach_driver+0x40/0xd8
[ 4322.146555] [<801df540>] __device_attach_driver+0x0/0xd8
[ 4322.151956] [<801dd7c4>] bus_for_each_drv+0x9c/0xac
[ 4322.156969] [<801df114>] __device_attach+0xac/0xe4
[ 4322.161835] [<80331698>] cleanup_uevent_env+0x0/0x8
[ 4322.166834] [<801de5c4>] bus_probe_device+0x3c/0xb0
[ 4322.171819] [<801dc8a8>] device_add+0x444/0x550
[ 4322.176508] [<87fc43ec>] usb_new_device+0x218/0x344 [usbcore]
[ 4322.182377] [<87fe0000>] scsi_cmd_get_serial+0x0/0x2c [scsi_mod]
[ 4322.188570] [<87fc53bc>] hub_port_debounce+0xd3c/0xf78 [usbcore]
[ 4322.194678] [<8771ceb0>] nf_flow_table_iterate+0x1ec/0x6c0 [nf_flow_table]
[ 4322.201660] [<8771cfc4>] nf_flow_table_iterate+0x300/0x6c0 [nf_flow_table]
[ 4322.208680] [<87fe0000>] scsi_cmd_get_serial+0x0/0x2c [scsi_mod]
[ 4322.214845] [<87fe0000>] scsi_cmd_get_serial+0x0/0x2c [scsi_mod]
[ 4322.220979] [<800370f4>] process_one_work+0x1e8/0x318
[ 4322.226136] [<80037f18>] worker_thread+0x2f4/0x424
[ 4322.231080] [<80037c24>] worker_thread+0x0/0x424
[ 4322.235768] [<8003c890>] kthread+0x130/0x138
[ 4322.240124] [<8003c760>] kthread+0x0/0x138
[ 4322.244304] [<800092d8>] ret_from_kernel_thread+0x14/0x1c
[ 4322.249782] 
[ 4322.251290] Code: (Bad address in epc)
[ 4322.255093] 
[ 4322.256665] ---[ end trace 0148a9a23e7b9469 ]---
[ 4322.264447] Kernel panic - not syncing: Fatal exception
[ 4322.271511] Rebooting in 3 seconds..

**Comment by nbd168** [comment]
mt7601u is a different driver, not part of this repository
