### ISSUE TITLE
mt7628: watchdog check stuck loop

### ISSUE THREAD

**Issue by baohavan** [openwrt/mt76#187]
[  165.515104] mt76_wmac 10300000.wmac: mt7603_watchdog_check 4
[ 1280.493376] mt76_wmac 10300000.wmac: mt7603_watchdog_check 4
[ 1912.890075] mt76_wmac 10300000.wmac: mt7603_watchdog_check 4
[ 1915.050060] mt76_wmac 10300000.wmac: mt7603_watchdog_check 3
[ 1925.529983] mt76_wmac 10300000.wmac: mt7603_watchdog_check 4
[ 1944.329848] mt76_wmac 10300000.wmac: mt7603_watchdog_check 4
[ 1946.489852] mt76_wmac 10300000.wmac: mt7603_watchdog_check 3
[ 1948.649813] mt76_wmac 10300000.wmac: mt7603_watchdog_check 3
[ 1950.809809] mt76_wmac 10300000.wmac: mt7603_watchdog_check 3
[ 1952.969866] mt76_wmac 10300000.wmac: mt7603_watchdog_check 3
[ 1955.129795] mt76_wmac 10300000.wmac: mt7603_watchdog_check 3
[ 1957.289761] mt76_wmac 10300000.wmac: mt7603_watchdog_check 3
[ 1959.449748] mt76_wmac 10300000.wmac: mt7603_watchdog_check 3
[ 1961.609740] mt76_wmac 10300000.wmac: mt7603_watchdog_check 3
[ 1972.089656] mt76_wmac 10300000.wmac: mt7603_watchdog_check 4
[ 2030.409170] mt76_wmac 10300000.wmac: mt7603_watchdog_check 4
[ 2143.849140] mt76_wmac 10300000.wmac: mt7603_watchdog_check 4
[ 2146.009120] mt76_wmac 10300000.wmac: mt7603_watchdog_check 3
[ 2389.450400] mt76_wmac 10300000.wmac: mt7603_watchdog_check 4
[ 2392.650395] mt76_wmac 10300000.wmac: mt7603_watchdog_check 3
[ 2395.850399] mt76_wmac 10300000.wmac: mt7603_watchdog_check 3
[ 2399.130502] mt76_wmac 10300000.wmac: mt7603_watchdog_check 3
[ 2402.330402] mt76_wmac 10300000.wmac: mt7603_watchdog_check 3
[ 2405.610367] mt76_wmac 10300000.wmac: mt7603_watchdog_check 3
[ 2408.890399] mt76_wmac 10300000.wmac: mt7603_watchdog_check 3
[ 2412.090350] mt76_wmac 10300000.wmac: mt7603_watchdog_check 3
[ 2415.370349] mt76_wmac 10300000.wmac: mt7603_watchdog_check 3
[ 2417.610346] mt76_wmac 10300000.wmac: mt7603_watchdog_check 3
[ 2419.770338] mt76_wmac 10300000.wmac: mt7603_watchdog_check 3
[ 2422.970448] mt76_wmac 10300000.wmac: mt7603_watchdog_check 3
[ 2426.250365] mt76_wmac 10300000.wmac: mt7603_watchdog_check 3
[ 2429.450321] mt76_wmac 10300000.wmac: mt7603_watchdog_check 3
[ 2432.730320] mt76_wmac 10300000.wmac: mt7603_watchdog_check 3
[ 2436.010311] mt76_wmac 10300000.wmac: mt7603_watchdog_check 3

This my debug code:

static bool
mt7603_watchdog_check(struct mt7603_dev *dev, u8 *counter,
		      enum mt7603_reset_cause cause,
		      bool (*check)(struct mt7603_dev *dev))
{
	if (check) {
		if (!check(dev) && *counter < MT7603_WATCHDOG_TIMEOUT) {
			*counter = 0;
			return false;
		}

		(*counter)++;
	}

	if (*counter < MT7603_WATCHDOG_TIMEOUT)
		return false;

	dev->reset_cause[cause]++;
	dev_info(dev->mt76.dev, "mt7603_watchdog_check %d\n", cause);
	return true;
}

**Comment by nbd168** [comment]
Fixed in current versions
