### ISSUE TITLE
 ramips switch problem

### ISSUE THREAD

**Issue by dimatto** [openwrt/mt76#190]
when change vlan from tagged to untaged or off, dmesg log:
 kern.warn kernel: [  376.655092] vlan egress tag control neither untag nor tag.

I know this should submit to openwrt but  no issues column there, so I submit it here .

**Comment by Mushoz** [comment]
This is the mt76 WiFi driver repository. Switch issues do not belong here, please file a bug report at OpenWRT's Flyspray.
