### ISSUE TITLE
How to set mcast_rate on mt76(mt7628)

### ISSUE THREAD

**Issue by Music802** [openwrt/mt76#191]
How set mcast_rate on mt76(mt7628)?

log:
root@LEDE:/mnt# iw dev wlan0 set mcast_rate 6
command failed: Not supported (-122)

root@LEDE:/mnt# cat /proc/cpuinfo 
system type             : MediaTek MT7628AN ver:1 eco:2
machine                 : MiWiFi Nano
processor               : 0
cpu model               : MIPS 24KEc V5.5
BogoMIPS                : 385.84
wait instruction        : yes
microsecond timers      : yes
tlb_entries             : 32
extra interrupt vector  : yes
hardware watchpoint     : yes, count: 4, address/irw mask: [0x0ffc, 0x0ffc, 0x0ffb, 0x0ffb]
isa                     : mips1 mips2 mips32r1 mips32r2
ASEs implemented        : mips16 dsp
shadow register sets    : 1
kscratch registers      : 0
package                 : 0
core                    : 0
VCED exceptions         : not available
VCEI exceptions         : not available

root@LEDE:/mnt# 
root@LEDE:/mnt# uname  -r
4.4.92
root@LEDE:/mnt#

**Comment by nbd168** [comment]
Please don't use the bug tracker for support questions. You can use the basic_rate option in the uci wifi-iface section
