### ISSUE TITLE
support 1701 openwrt？

### ISSUE THREAD

**Issue by hzjnet** [openwrt/mt76#204]
1  How can we use your code of the newest driver in lede-17.01 ?
2  I wonder why I often find myself offline when using 2.4G?
3  When will the support to chip mt7615 be added ?

thanks

**Comment by LGA1150** [comment]
English please

**Comment by hzjnet** [comment]
看来改成鸟语还是然并卵啊

**Comment by yousong** [comment]
Be professional please.

> 1 How can we use your code of the newest driver in lede-17.01 ?

Version bumps in release code are usually only for bug fixes or security issues, etc.  You are on your own to try and test newest version on lede-17.01 if this is not happening.

> 2 I wonder why I often find myself offline when using 2.4G?

Provide info on your environment, versions of critical components, detailed description of symptoms that can help diagnose the issue and find the cause.

> 3 When will the support to chip mt7615 be added ?

When it comes to open source projects overall, I'd like to it comes when it comes ;)   I will leave this question open to others ;)
