### ISSUE TITLE
build 17016 error

### ISSUE THREAD

**Issue by hzjnet** [openwrt/mt76#210]
log 

rm -f /openwrt/leand20180823v518/staging_dir/target-mipsel_24kc_musl/stamp/.mt76_installed
(cd /openwrt/leand20180823v518/build_dir/target-mipsel_24kc_musl/linux-ramips_mt7620/mt76-2018-07-13-67803752/./; if [ -x ./configure ]; then find /openwrt/leand20180823v518/build_dir/target-mipsel_24kc_musl/linux-ramips_mt7620/mt76-2018-07-13-67803752/ -name config.guess | xargs -r chmod u+w; find /openwrt/leand20180823v518/build_dir/target-mipsel_24kc_musl/linux-ramips_mt7620/mt76-2018-07-13-67803752/ -name config.guess | xargs -r -n1 cp --remove-destination /openwrt/leand20180823v518/scripts/config.guess; find /openwrt/leand20180823v518/build_dir/target-mipsel_24kc_musl/linux-ramips_mt7620/mt76-2018-07-13-67803752/ -name config.sub | xargs -r chmod u+w; find /openwrt/leand20180823v518/build_dir/target-mipsel_24kc_musl/linux-ramips_mt7620/mt76-2018-07-13-67803752/ -name config.sub | xargs -r -n1 cp --remove-destination /openwrt/leand20180823v518/scripts/config.sub; AR="mipsel-openwrt-linux-musl-gcc-ar" AS="mipsel-openwrt-linux-musl-gcc -c -Os -pipe -mno-branch-likely -mips32r2 -mtune=24kc -fno-caller-saves -fno-plt -fhonour-copts -Wno-error=unused-but-set-variable -Wno-error=unused-result -msoft-float -iremap/openwrt/leand20180823v518/build_dir/target-mipsel_24kc_musl/linux-ramips_mt7620/mt76-2018-07-13-67803752:mt76-2018-07-13-67803752 -Wformat -Werror=format-security -fstack-protector -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro" LD=mipsel-openwrt-linux-musl-ld NM="mipsel-openwrt-linux-musl-gcc-nm" CC="mipsel-openwrt-linux-musl-gcc" GCC="mipsel-openwrt-linux-musl-gcc" CXX="mipsel-openwrt-linux-musl-g++" RANLIB="mipsel-openwrt-linux-musl-gcc-ranlib" STRIP=mipsel-openwrt-linux-musl-strip OBJCOPY=mipsel-openwrt-linux-musl-objcopy OBJDUMP=mipsel-openwrt-linux-musl-objdump SIZE=mipsel-openwrt-linux-musl-size CFLAGS="-Os -pipe -mno-branch-likely -mips32r2 -mtune=24kc -fno-caller-saves -fno-plt -fhonour-copts -Wno-error=unused-but-set-variable -Wno-error=unused-result -msoft-float -mips16 -minterlink-mips16 -iremap/openwrt/leand20180823v518/build_dir/target-mipsel_24kc_musl/linux-ramips_mt7620/mt76-2018-07-13-67803752:mt76-2018-07-13-67803752 -Wformat -Werror=format-security -fstack-protector -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro " CXXFLAGS="-Os -pipe -mno-branch-likely -mips32r2 -mtune=24kc -fno-caller-saves -fno-plt -fhonour-copts -Wno-error=unused-but-set-variable -Wno-error=unused-result -msoft-float -mips16 -minterlink-mips16 -iremap/openwrt/leand20180823v518/build_dir/target-mipsel_24kc_musl/linux-ramips_mt7620/mt76-2018-07-13-67803752:mt76-2018-07-13-67803752 -Wformat -Werror=format-security -fstack-protector -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro " CPPFLAGS="-I/openwrt/leand20180823v518/staging_dir/target-mipsel_24kc_musl/usr/include -I/openwrt/leand20180823v518/staging_dir/target-mipsel_24kc_musl/include -I/openwrt/leand20180823v518/staging_dir/toolchain-mipsel_24kc_gcc-7.3.0_musl/usr/include -I/openwrt/leand20180823v518/staging_dir/toolchain-mipsel_24kc_gcc-7.3.0_musl/include/fortify -I/openwrt/leand20180823v518/staging_dir/toolchain-mipsel_24kc_gcc-7.3.0_musl/include " LDFLAGS="-L/openwrt/leand20180823v518/staging_dir/target-mipsel_24kc_musl/usr/lib -L/openwrt/leand20180823v518/staging_dir/target-mipsel_24kc_musl/lib -L/openwrt/leand20180823v518/staging_dir/toolchain-mipsel_24kc_gcc-7.3.0_musl/usr/lib -L/openwrt/leand20180823v518/staging_dir/toolchain-mipsel_24kc_gcc-7.3.0_musl/lib -znow -zrelro "   ./configure --target=mipsel-openwrt-linux --host=mipsel-openwrt-linux --build=x86_64-pc-linux-gnu --program-prefix="" --program-suffix="" --prefix=/usr --exec-prefix=/usr --bindir=/usr/bin --sbindir=/usr/sbin --libexecdir=/usr/lib --sysconfdir=/etc --datadir=/usr/share --localstatedir=/var --mandir=/usr/man --infodir=/usr/info --disable-nls  ; fi; )
touch /openwrt/leand20180823v518/build_dir/target-mipsel_24kc_musl/linux-ramips_mt7620/mt76-2018-07-13-67803752/.configured_68b329da9893e34099c7d8ad5cb9c940
rm -f /openwrt/leand20180823v518/build_dir/target-mipsel_24kc_musl/linux-ramips_mt7620/mt76-2018-07-13-67803752/.built
touch /openwrt/leand20180823v518/build_dir/target-mipsel_24kc_musl/linux-ramips_mt7620/mt76-2018-07-13-67803752/.built_check
cat /dev/null > /openwrt/leand20180823v518/staging_dir/target-mipsel_24kc_musl/pkginfo/mt76.symvers; for subdir in .; do cat /openwrt/leand20180823v518/staging_dir/target-mipsel_24kc_musl/pkginfo/*.symvers 2>/dev/null > /openwrt/leand20180823v518/build_dir/target-mipsel_24kc_musl/linux-ramips_mt7620/mt76-2018-07-13-67803752/$subdir/Module.symvers; done
make  -C "/openwrt/leand20180823v518/build_dir/target-mipsel_24kc_musl/linux-ramips_mt7620/linux-4.4.153" HOSTCFLAGS="-O2 -I/openwrt/leand20180823v518/staging_dir/host/include -I/openwrt/leand20180823v518/staging_dir/hostpkg/include -I/openwrt/leand20180823v518/staging_dir/target-mipsel_24kc_musl/host/include -Wall -Wmissing-prototypes -Wstrict-prototypes" CROSS_COMPILE="mipsel-openwrt-linux-musl-" ARCH="mips" KBUILD_HAVE_NLS=no KBUILD_BUILD_USER="" KBUILD_BUILD_HOST="" KBUILD_BUILD_TIMESTAMP="Thu Aug 23 09:40:23 2018" KBUILD_BUILD_VERSION="0" HOST_LOADLIBES="-L/openwrt/leand20180823v518/staging_dir/host/lib" CONFIG_SHELL="bash" V=''  cmd_syscalls= KERNELRELEASE=4.4.153 SUBDIRS="/openwrt/leand20180823v518/build_dir/target-mipsel_24kc_musl/linux-ramips_mt7620/mt76-2018-07-13-67803752" NOSTDINC_FLAGS="-I/openwrt/leand20180823v518/build_dir/target-mipsel_24kc_musl/linux-ramips_mt7620/mt76-2018-07-13-67803752 -I/openwrt/leand20180823v518/staging_dir/target-mipsel_24kc_musl/usr/include/mac80211-backport/uapi -I/openwrt/leand20180823v518/staging_dir/target-mipsel_24kc_musl/usr/include/mac80211-backport -I/openwrt/leand20180823v518/staging_dir/target-mipsel_24kc_musl/usr/include/mac80211/uapi -I/openwrt/leand20180823v518/staging_dir/target-mipsel_24kc_musl/usr/include/mac80211 -include backport/autoconf.h -include backport/backport.h -DCONFIG_MAC80211_MESH" modules
make[4]: Entering directory '/openwrt/leand20180823v518/build_dir/target-mipsel_24kc_musl/linux-ramips_mt7620/linux-4.4.153'
  CC [M]  /openwrt/leand20180823v518/build_dir/target-mipsel_24kc_musl/linux-ramips_mt7620/mt76-2018-07-13-67803752/mmio.o
  CC [M]  /openwrt/leand20180823v518/build_dir/target-mipsel_24kc_musl/linux-ramips_mt7620/mt76-2018-07-13-67803752/util.o
  CC [M]  /openwrt/leand20180823v518/build_dir/target-mipsel_24kc_musl/linux-ramips_mt7620/mt76-2018-07-13-67803752/trace.o
  CC [M]  /openwrt/leand20180823v518/build_dir/target-mipsel_24kc_musl/linux-ramips_mt7620/mt76-2018-07-13-67803752/dma.o
/openwrt/leand20180823v518/build_dir/target-mipsel_24kc_musl/linux-ramips_mt7620/mt76-2018-07-13-67803752/dma.c: In function 'mt76_dma_rx_fill':
/openwrt/leand20180823v518/build_dir/target-mipsel_24kc_musl/linux-ramips_mt7620/mt76-2018-07-13-67803752/dma.c:257:9: error: implicit declaration of function 'page_frag_alloc'; did you mean 'bpf_prog_alloc'? [-Werror=implicit-function-declaration]
   buf = page_frag_alloc(&q->rx_page, q->buf_size, GFP_ATOMIC);
         ^~~~~~~~~~~~~~~
         bpf_prog_alloc
/openwrt/leand20180823v518/build_dir/target-mipsel_24kc_musl/linux-ramips_mt7620/mt76-2018-07-13-67803752/dma.c:257:7: error: assignment makes pointer from integer without a cast [-Werror=int-conversion]
   buf = page_frag_alloc(&q->rx_page, q->buf_size, GFP_ATOMIC);
       ^
/openwrt/leand20180823v518/build_dir/target-mipsel_24kc_musl/linux-ramips_mt7620/mt76-2018-07-13-67803752/dma.c: In function 'mt76_dma_rx_cleanup':
/openwrt/leand20180823v518/build_dir/target-mipsel_24kc_musl/linux-ramips_mt7620/mt76-2018-07-13-67803752/dma.c:302:2: error: implicit declaration of function '__page_frag_cache_drain' [-Werror=implicit-function-declaration]
  __page_frag_cache_drain(page, q->rx_page.pagecnt_bias);
  ^~~~~~~~~~~~~~~~~~~~~~~
cc1: all warnings being treated as errors
make[5]: *** [/openwrt/leand20180823v518/build_dir/target-mipsel_24kc_musl/linux-ramips_mt7620/mt76-2018-07-13-67803752/dma.o] Error 1
scripts/Makefile.build:269: recipe for target '/openwrt/leand20180823v518/build_dir/target-mipsel_24kc_musl/linux-ramips_mt7620/mt76-2018-07-13-67803752/dma.o' failed
make[4]: *** [_module_/openwrt/leand20180823v518/build_dir/target-mipsel_24kc_musl/linux-ramips_mt7620/mt76-2018-07-13-67803752] Error 2
Makefile:1419: recipe for target '_module_/openwrt/leand20180823v518/build_dir/target-mipsel_24kc_musl/linux-ramips_mt7620/mt76-2018-07-13-67803752' failed
make[4]: Leaving directory '/openwrt/leand20180823v518/build_dir/target-mipsel_24kc_musl/linux-ramips_mt7620/linux-4.4.153'
make[3]: *** [/openwrt/leand20180823v518/build_dir/target-mipsel_24kc_musl/linux-ramips_mt7620/mt76-2018-07-13-67803752/.built] Error 2
Makefile:107: recipe for target '/openwrt/leand20180823v518/build_dir/target-mipsel_24kc_musl/linux-ramips_mt7620/mt76-2018-07-13-67803752/.built' failed
make[3]: Leaving directory '/openwrt/leand20180823v518/package/kernel/mt76'
Command exited with non-zero status 2
time: package/kernel/mt76/compile#4.12#0.86#6.84
make[2]: *** [package/kernel/mt76/compile] Error 2
package/Makefile:107: recipe for target 'package/kernel/mt76/compile' failed
make[2]: Leaving directory '/openwrt/leand20180823v518'
make[1]: *** [/openwrt/leand20180823v518/staging_dir/target-mipsel_24kc_musl/stamp/.package_compile] Error 2
package/Makefile:103: recipe for target '/openwrt/leand20180823v518/staging_dir/target-mipsel_24kc_musl/stamp/.package_compile' failed
make[1]: Leaving directory '/openwrt/leand20180823v518'
make: *** [world] Error 2
/openwrt/leand20180823v518/include/toplevel.mk:216: recipe for target 'world' failed

kernel 4.4.153  
mtk drivers 20180713
what to do ?   
thanks

**Comment by nbd168** [comment]
You need to use the latest mac80211 package from OpenWrt master or 18.06
