### ISSUE TITLE
Frequent occurence of MCU timeout with mt7612

### ISSUE THREAD

**Issue by kristrev** [openwrt/mt76#212]
I am currently having a problem on an mt7621-based device I am working on. If I perform a "dirty" reboot (for example via the hardware watchdog), the mt7612 card will be left in a bad state, the "MCU timeout"-message appears and the 5GHz wifi does not work properly. If I reboot the device cleanly, I do not see the error message and wifi driver works as expected. Also, the mt7603-card in the device is not affected and works irrespective of how I reboot the device.

I suspect there is something flaky with the hardware, but I wondered if it is possible to work around the issue in software and where to start looking? I see that there is a watchdog/reset for MCU-resets in the mt7603-part of the driver, would something similar be possible for mt76x2? I tried to dig in the vendor driver, but came up empty.

I have also tried to mirror the steps that the driver does to shut down the card (on reboot) when the driver is loaded, but I did not have any luck.

**Comment by razvan01** [comment]
Same issue on **DIR-860L B1** with **MediaTek MT7621 ver:1 eco:3** and firmware version **OpenWrt SNAPSHOT r8450-a95bef0579 / LuCI Master (git-18.316.66864-1ca22ec)**
There are over 200 messages in ~12 hours of router running with message like:
> mt76x2e 0000:02:00.0: MCU message 31 (seq 2) timed out

As workaround I've enabled IGMP snooping to see if this still persist. 

The issue seems to be caused by 2.4GHz network when a device who support 2.4GHz wifi only. 

I can provide more logs if needed.

**Comment by sotux** [comment]
My huawei honor 9 mobile phone constantly lose 2.4G wifi. After it lost connections, the 2.4G ssid can't be found by any devices even restart the 2.4G wifi. And the system log has many kernel errors of MCU timed out.
~~~
Tue Nov 27 05:05:14 2018 kern.err kernel: [ 4799.262821] mt7603e 0000:02:00.0: MCU message 8 (seq 3) timed out
Tue Nov 27 05:05:17 2018 kern.err kernel: [ 4802.382760] mt7603e 0000:02:00.0: MCU message 8 (seq 4) timed out
Tue Nov 27 05:05:20 2018 kern.err kernel: [ 4805.502699] mt7603e 0000:02:00.0: MCU message 8 (seq 5) timed out
Tue Nov 27 05:05:24 2018 kern.err kernel: [ 4808.622643] mt7603e 0000:02:00.0: MCU message 8 (seq 6) timed out
~~~

I tested on this commit da666a74a605a44c8cc649fb1e8b8e59e86c9acf
My device is newifi-d2 with 512M ram, 32M spi, mt7603e + mt7612e

**Comment by markuznw** [comment]
Same here on MiR3G, starting a few minutes / hours after a reboot and can't fix it even restarting wifi interfance (needs a router reboot)

> [27011.369960] mt7603e 0000:01:00.0: MCU message 8 (seq 11) timed out
> [27015.049907] mt7603e 0000:01:00.0: MCU message 8 (seq 12) timed out

Using latest openwrt master as of today so current mt76, let's hope @nbd168 can fix it as it renders 2.4ghz totally unusable

**Comment by nbd168** [comment]
Please try the latest version

**Comment by razvan01** [comment]
Still same issue with:
> [28823.629705] mt76x2e 0000:02:00.0: MCU message 31 (seq 3) timed out
[28825.709700] mt76x2e 0000:02:00.0: MCU message 31 (seq 4) timed out
[28827.789686] mt76x2e 0000:02:00.0: MCU message 31 (seq 5) timed out
[28829.869675] mt76x2e 0000:02:00.0: MCU message 31 (seq 6) timed out
[28831.949656] mt76x2e 0000:02:00.0: MCU message 31 (seq 7) timed out

In last ~8 hours from latest update **r8591-56378bc / LuCI Master (git-18.332.46770-98cde82)** there are a lot of that messages and 2.4ghz device is unreachable.

**Comment by lukasz1992** [comment]
@razvan01 You should wait for the next build, you have drivers from 21 Nov.

**Comment by razvan01** [comment]
@lukasz1992 next build will be today or tomorrow?

**Comment by markuznw** [comment]
After more than 24h running on new mt76 pull I didn't notice any timeout in logs and 2.4ghz is still up and running, thanks for super fast resolution Felix, you're awesome as usual

Fixed (for my MiR3G) ;)

**Comment by lukasz1992** [comment]
@razvan01 ready, you can test.

**Comment by razvan01** [comment]
@lukasz1992 I've installed it few mins ago but router get stuck. Working to unbrick it.

**Comment by razvan01** [comment]
Seems latest snapshot update brick router and is needed to go in recovery mode. I am using D-Link DIR-860L B1. I can provide mode logs or infos if needed.

**Comment by lukasz1992** [comment]
I just read that ticket has MT7612 in title, but @razvan01 has problem with MT7602E device.
Last fixes made by @nbd168 were about mt7603 driver.

**Comment by razvan01** [comment]
@lukasz1992 may I create another ticket for my issue?
