### ISSUE TITLE
MT7610 unable to set transmit power

### ISSUE THREAD

**Issue by jameslewisuk** [openwrt/mt76#224]
Hello,

I have complied OpenWRT 18.06 for my WL-WNN575A2 device and it is up and running, but although the 2.4Ghz wifi works fine, the 5Ghz wifi does not because I am having an issue with the TX power, whatever I do it seems to be stuck at 15dbm and will not increase either by the web gui or by command line.

This device is very similar to WL-WN575A3 except it uses MT7610E for 5Ghz instead of MT7612E on the A3 model, so I used the WL-WN575A3 profile to build the firmware but I removed the MT7612E driver and substituted it for MT7610E in Make Menuconfig.  I did not make any other changes apart from including LUCI.

It would be really good if the TX power could be set to the correct level, as it is really too low to be usable at the moment.

If anything can be suggested that I could try that would be most helpful.

**Comment by nbd168** [comment]
Please try the latest version, it should work now.
