### ISSUE TITLE
SD card issue in MT7620

### ISSUE THREAD

**Issue by ObaidAshraf** [openwrt/mt76#23]
I have a ZBT-WE826 router with built-in SD Card slot. I am trying to mount my SD card in my Router. I've openWRT CC with kernel 3.18. I've download mmc_over_gpio and related packages.. But the problem arises, when I run "/etc/init.d/mmc_over_gpio restart", i get this error "no support for SD card's voltages" ..
There is also a ticket open in openWRT for this on, "https://dev.openwrt.org/ticket/21834" ..

How can i solve this error?? i tried multiple SD cards, but no use..

**Comment by blogic** [comment]
This repo is for a wifi driver called MT76. Your bug report has nothing to do with wifi.

**Comment by ObaidAshraf** [comment]
Oops, Sorry .. My bad !! ..

**Comment by blogic** [comment]
On 18/03/2016 11:17, Obaid Ashraf wrote:
> Oops, Sorry .. My bad !! ..
> 
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly or view it on GitHub
> <https://github.com/openwrt/mt76/issues/23#issuecomment-198293465>
> 

https://dev.openwrt.org/ would be the place to post your bug
