### ISSUE TITLE
5g massive packet loss with strange avg_rssi

### ISSUE THREAD

**Issue by dimatto** [openwrt/mt76#231]
75% packet loss back again after being correct at Jun, this time when I cat agc file, avg_rssi is -4 , sometimes is -128, but I only have two clients , one’s signal is -77, the other is -48, as displayed at luci.

**Comment by dimatto** [comment]
It seems that ewma_signal_read() returns wrong value.

**Comment by nbd168** [comment]
Fixed in the latest version, thanks for reporting.
