### ISSUE TITLE
Problems receiving ARP 

### ISSUE THREAD

**Issue by jsj-reseiwe** [openwrt/mt76#24]
Openwrt Version: HEAD (17/3-2016)
mt76: 7059cc27df894a4b845b6deb7c51425ffb4b7c5c
Kernel: 4.4
Hardware: MT7688 (LinkIt)

After hacking the device tree the driver is functional :-)
But ARP requests are not getting through. 
If I look in mac80211.c/mt76_rx_complete I can see that some broadcast packets but not all are getting through.
This might be a firmware issue or just missing configuration.
Any idea on how to track this bug down?

Regards

Jakob

**Comment by nbd168** [comment]
Fixed in 3d36d4b649bed1fb36a95089ffcce2ece83051c4
