### ISSUE TITLE
2.4GHz LED not working

### ISSUE THREAD

**Issue by nickberry17** [openwrt/mt76#240]
SoC is MT7621
2.4GHz is MT7603e on pcie0
5GHz is MT7612e on pcie1

After using this commit bc7ce2a1701ca91a58d661fbb3f9ccc3c99bd32e, the 2.4GHz LED is no longer working.  It used to work with ffccb48c5082b2c6f43a0235b77b62ca388810f0

This is the device tree I have been using. Is there some new change requiring a modification?

```
&pcie {
	status = "okay";

        pcie0 {
	        wifi@0,0 {
	                compatible = "pci14c3,7603";
		        reg = <0x0000 0 0 0 0>;
		        mediatek,mtd-eeprom = <&factory 0x0000>;
		        ieee80211-freq-limit = <2400000 2500000>;
		        
	        };
        };

        pcie1 {
	        wifi@0,0 {
	                compatible = "pci14c3,7662";
		        reg = <0x0000 0 0 0 0>;
		        mediatek,mtd-eeprom = <&factory 0x8000>;
		        ieee80211-freq-limit = <5000000 6000000>;
		        
		        led {
		                led-sources = <2>;   
		            };
	        };
        };

};
```

**Comment by nbd168** [comment]
Fixed in a4ec45c29498ad870ac87695d71608e82675dfac

**Comment by nickberry17** [comment]
Now it seems the 2.4GHz LED works, but the 5GHz LED does not.  Any hints on what to check?

**Comment by nickberry17** [comment]
Happy to confirm that this fixed the LED's
