### ISSUE TITLE
MT76 20190203 version 5G wireless can't run at full speed!

### ISSUE THREAD

**Issue by zxlhhyccc** [openwrt/mt76#244]
MT76 20190203 version 5G wireless can't run at full speed!A maximum of 585Mbit/s

**Comment by nbd168** [comment]
What speed were you expecting?

**Comment by zxlhhyccc** [comment]
Not running at 866.7g

**Comment by nbd168** [comment]
How are you measuring the speed?

**Comment by nbd168** [comment]
Feel free to reopen when you can provide more details
