### ISSUE TITLE
mt7612 not working

### ISSUE THREAD

**Issue by frank-w** [openwrt/mt76#249]
i try to integrate this driver to 4.19-tree

version of 4.19 is working, but version of openwrt hangs on

    Association Response to the STA has already been sent, but no TX status yet known - ignore Class 3 frame issue with <mac>

any idea?

**Comment by nbd168** [comment]
Please try the latest version

**Comment by frank-w** [comment]
can you say me till which version (git hash) the driver is compatible with 4.19?
current version fails because there is some ieee-functions for tx shedule which are not present in 4.19
