### ISSUE TITLE
The reason of my 2.4g lag

### ISSUE THREAD

**Issue by dimatto** [openwrt/mt76#252]
My 2.4g is mt7603e on mir3g. For long time it's laggy. I compiled older commits to find reason, and the reason is commit 9d009be. I can't figure out what's wrong with that commit, for now, I simply comment mt7603_false_cca_check() to wipe out  lag.

**Comment by nbd168** [comment]
Thanks for tracking this down. Could you please show me a few snapshots of the contents of the "radio" debugfs file while it's lagging?

**Comment by dimatto** [comment]
now I'm running code without mt7603_false_cca_check() and lag, I remember when it's lagging Sensitivity is -72 while my signal is -46 displayed at luci , not clear about ofdm and cck, if you need more accurate data, I'll try it tomorrow.

**Comment by nbd168** [comment]
I’ve pushed a change to disable this by default. I found out that the vendor driver also does not enable this code

**Comment by dimatto** [comment]
ok, it's fine.
