### ISSUE TITLE
TP-Link 6.0/6.1/6.2/14 Support

### ISSUE THREAD

**Issue by sanitariu** [openwrt/mt76#254]
I have patches for supporting these TP-link routers. (TP-Link 6.0/6.1/6.2/14)
All routers are with 4MB flash size and 32MB ram.
nbd168, if you are interested please contact me to send you patches.
Sorry for creating issue but i do not know where is better to post them for 
checking and confirming ?
If it is okay i will do it here ?

**Comment by nbd168** [comment]
Not sure what routers you are referring to, but if you're talking about openwrt patches, they should be posted to the OpenWrt list or github instead of here. This project is only about the mt76 wifi drivers
