### ISSUE TITLE
The latest version of the MT76 5G will not be able to operate at a slow speed, with a top speed of only 433.3m

### ISSUE THREAD

**Issue by zxlhhyccc** [openwrt/mt76#264]
The latest version of the MT76 5G will not be able to operate at a slow speed, with a top speed of only 433.3m

**Comment by nbd168** [comment]
I don't understand what you mean by "will not be able to operate at a slow speed". Could you please provide some details?

**Comment by zxlhhyccc** [comment]
The latest 5G of MT76 can't run at high speed. I made a mistake

**Comment by nbd168** [comment]
How did you measure that speed?

**Comment by zxlhhyccc** [comment]
The speed displayed on the routing page is less than 866.67m

**Comment by lukasz1992** [comment]
@zxlhhyccc Do you have a device with 2x2 spatial streams? Did it worked on 866 Mbps previously? Please show us:
`iw dev wlan1 station dump`
