### ISSUE TITLE
Problem with WPA2-EAP

### ISSUE THREAD

**Issue by gareth41** [openwrt/mt76#27]
Router is ZBT-WG3526 running openwrt trunk 4b4446b5f1a1bce2a7c7de90d5a6884212492da2 with wpad full installed.

5g: MT7612
2.4g MT7603

WPA2-EAP produces the following when enabled on either or both radios and router becomes unstable, WPA2-PSK works fine.

[   23.310000] ------------[ cut here ]------------
[   23.310000] WARNING: CPU: 2 PID: 71 at /home/gareth/openwrt/build_dir/target-mipsel_1004kc+dsp_musl-1.1.14/linux-ramips_mt7621/mt76-2016-03-04/mt7603_mac.c:1202 mt7603_mac_work+0x204/0x280 [mt7603e]()
[   23.330000] Modules linked in: pppoe ppp_async iptable_nat pppox ppp_generic nf_nat_ipv4 nf_conntrack_ipv6 nf_conntrack_ipv4 ipt_REJECT ipt_MASQUERADE xt_time xt_tcpudp xt_tcpmss xt_statistic xt_state xt_quota xt_pkttype xt_owner xt_nat xt_multiport xt_mark xt_mac xt_limit xt_length xt_id xt_hl xt_ecn xt_dscp xt_conntrack xt_comment xt_addrtype xt_TCPMSS xt_REDIRECT xt_NETMAP xt_LOG xt_HL xt_DSCP xt_CT xt_CLASSIFY slhc nf_reject_ipv4 nf_nat_redirect nf_nat_masquerade_ipv4 nf_nat nf_log_ipv4 nf_defrag_ipv6 nf_defrag_ipv4 nf_conntrack_rtcache nf_conntrack iptable_raw iptable_mangle iptable_filter ipt_ECN ip_tables crc_ccitt mt7603e mt76x2e mt76 mac80211 cfg80211 compat ledtrig_usbdev ip6t_REJECT nf_reject_ipv6 nf_log_ipv6 nf_log_common ip6table_raw ip6table_mangle ip6table_filter ip6_tables x_tables leds_gpio xhci_mtk xhci_plat_hcd xhci_pci xhci_hcd ahci libahci libata sd_mod scsi_mod gpio_button_hotplug usbcore nls_base usb_common
[   23.410000] CPU: 2 PID: 71 Comm: kworker/u8:3 Not tainted 4.4.6 #9
[   23.420000] Workqueue: phy1 mt7603_mac_work [mt7603e]
[   23.420000] Stack : 8f918100 80450000 803cc84c 000004b2 8edbd224 00000000 8f804614 8f918118
          00000088 80063244 803cc84c 00000002 00000047 804a365c 803e803c 8f99fd54
          80450000 80060fcc 80450000 804c0000 80452118 8045211c 803d1130 8f99fd54
          80450000 80040bf0 8f804614 8f99fd8c 00000447 00000000 00000000 0099fd74
          8edbd020 8f9c1900 8f9c1a00 31796870 00000000 00000000 00000000 00000000
          ...
[   23.460000] Call Trace:
[   23.460000] [<80016640>] show_stack+0x50/0x84
[   23.470000] [<801aa5dc>] dump_stack+0x84/0xbc
[   23.470000] [<8002bb3c>] warn_slowpath_common+0xa0/0xd0
[   23.470000] [<8002bbf0>] warn_slowpath_null+0x18/0x24
[   23.480000] [<8edbd224>] mt7603_mac_work+0x204/0x280 [mt7603e]
[   23.490000] [<8003e858>] process_one_work+0x214/0x358
[   23.490000] [<8003f740>] worker_thread+0x2dc/0x444
[   23.500000] [<80043e78>] kthread+0xdc/0xe8
[   23.500000] [<80005478>] ret_from_kernel_thread+0x14/0x1c
[   23.500000]
[   23.510000] ---[ end trace e9c12d70b1d00a36 ]---

**Comment by nbd168** [comment]
Please try the latest version, it should be more stable now.
