### ISSUE TITLE
mt76x0e - problem with 5GHz

### ISSUE THREAD

**Issue by podtor** [openwrt/mt76#275]
I've bought a D-Link DWR-118 A1 and I have a huge problem with 5GHz. On original firmware, 5GHz works well. With snapshot (4.14.111-1) OpenWrt firmware only 2 meters range signal 5GHz. 2.4GHz work ok on OpenWrt and on the original firmware.

**Comment by podtor** [comment]
On OpenWrt forum is a similar issue regarding ASUS RT-AC51U [mt76x0e - support for 5ghz](https://forum.openwrt.org/t/asus-rt-ac51u-support-for-5ghz/35041)

**Comment by CHKDSK88** [comment]
Please try patch from https://github.com/openwrt/mt76/issues/286 .

**Comment by ffrediani** [comment]
This router (Rev A1) uses the same radio as TP-Link C20 v4 and 5Ghz has serious issues to the point it doesn't work with snapshot versions so far. Seems this driver in mt76 hasn't been touched for a while, at least there was no apparent improvements.
There is another issue about this, please check: #227 and feedback there if your still persist.

**Comment by ffrediani** [comment]
Have updated to r10348-577174cf60 and now it seems to be able to control the Transmit Power correctly. Also the Scan button that has never worked correctly seems now to work.

**Comment by podtor** [comment]
Yes, I confirm. 5GHz works well.
