### ISSUE TITLE
Openwrt commits/sync time

### ISSUE THREAD

**Issue by sanitariu** [openwrt/mt76#292]
When fixes from here goes to openwrt main tree ?
I think syncing is too long or at least some months away ?

**Comment by everloop2** [comment]
see: https://git.openwrt.org/?p=openwrt%2Fopenwrt.git&a=search&h=HEAD&st=commit&s=mt76
for latest commits to master branch

trunk images for testing: http://downloads.openwrt.org/snapshots/targets/
-> use https://openwrt.org/docs/guide-user/additional-software/opkg to install additional mt76 packages

or short way -> https://openwrt.org/docs/guide-user/additional-software/imagebuilder
"The Image Builder (previously called the Image Generator) is a pre-compiled environment suitable for creating custom images without the need for compiling them from source.
It downloads pre-compiled packages and integrates them in a single flashable image."

long way -> build OpenWrt from source: https://openwrt.org/docs/guide-developer/build-system/install-buildsystem
