### ISSUE TITLE
mt76x2e: more than two SSID fails.

### ISSUE THREAD

**Issue by pparent76** [openwrt/mt76#293]
Whenever I try to get more than two SSID in hostapd, I get the following:

> Using interface wlan1 with hwaddr 78:a3:51:35:1c:89 and ssid "dsfq"
> Using interface wlan1_0 with hwaddr 06:a4:51:35:1c:80 and ssid "WIfi test"
> Could not set interface wlan1_1 flags (UP): Resource busy
> Failed to add BSS (BSSID=06:a5:51:35:1c:80)

Any idea how to solve this?

**Comment by sgruszka** [comment]
Try to use  'use_driver_iface_addr=1' option instead of using custom 'bssid= ' addresses in your hostapd config.

**Comment by pparent76** [comment]
Ok thanks so much, it works!
