### ISSUE TITLE
Support "vendor" and "product" parameters

### ISSUE THREAD

**Issue by ndoo** [openwrt/mt76#30]
It would be nice to be able to test mt76 on unsupported/rare mt76xx hardware via vendor and product parameters.

Right now:
mt76x2e: unknown parameter 'vendor' ignored
mt76x2e: unknown parameter 'product' ignored

**Comment by nbd168** [comment]
Such a module parameter is unnecessary. You can already add new PCI IDs to a driver at runtime using sysfs.
