### ISSUE TITLE
Support for 4.19 kernel

### ISSUE THREAD

**Issue by rodrigo-sm2** [openwrt/mt76#300]
We are having problems with the old kernel version (4.14), especially in sqm (related in openwrt forum), where it is no longer possible to use qdisc cake because of recent changes, so is there any prediction for mt76x8 devices to support kernel 4.19?

**Comment by orangepizza** [comment]
that's not in scope of this driver, but main repository of openwrt/openwrt, this is for wireless chip drivers, and already support newer kernels.
