### ISSUE TITLE
build dc14ac64e7f375078373c11d1196f4ae0ad393ab  fails to run on mt7615

### ISSUE THREAD

**Issue by nicefile** [openwrt/mt76#319]
unable to load foss mt7615e module  on R6260 kernel 4.14.141 and lastest mac80211
[ 8000.641320] bus=0x1, slot = 0x0, irq=0x18
[ 8000.672692] mt7615e 0000:01:00.0: Direct firmware load for mediatek/mt7615_n9.bin failed with error -2
[ 8000.691263] mt7615e 0000:01:00.0: Falling back to user helper
[ 8000.778417] firmware mediatek!mt7615_n9.bin: firmware_loading_store: map pages failed
[ 8000.794559] mt7615e: probe of 0000:01:00.0 failed with error -11

Previous version (15.09) did run fine . Also  I have no problem with  closed source driver .

**Comment by Borromini** [comment]
I'm seeing the same with a 330e8324 checkout on OpenWrt 19.07 and MT7615E. It used to work fine on earlier checkouts, but now the driver seems to be looking in /lib/firmware/mediatek/ instead of just /lib/firmware/.

```
[   33.648927] mt7615e 0000:01:00.0: Direct firmware load for mediatek/mt7615_rom_patch.bin failed with error -2
[   33.668906] mt7615e 0000:01:00.0: Falling back to user helper
[   33.971828] firmware mediatek!mt7615_rom_patch.bin: firmware_loading_store: map pages failed
[   33.989211] mt7615e: probe of 0000:01:00.0 failed with error -11
[   34.026170] mt7615e 0000:02:00.0: Direct firmware load for mediatek/mt7615_rom_patch.bin failed with error -2
[   34.045955] mt7615e 0000:02:00.0: Falling back to user helper
[   34.097277] firmware mediatek!mt7615_rom_patch.bin: firmware_loading_store: map pages failed
[   34.114739] mt7615e: probe of 0000:02:00.0 failed with error -11
```
