### ISSUE TITLE
MT7615 LED

### ISSUE THREAD

**Issue by dengqf6** [openwrt/mt76#330]
I got a router whose wireless LED is connected to MT7615 GPIO#14 directly, but the LED is not working with mt76 driver.

Is `led-sources` required in the DTS?

**Comment by LorenzoBianconi** [comment]
@dengqf6 mt7615 has some pwm led pins, are you sure the led is connected to a generic gpio? (I have no 7615 pin layout)

**Comment by LorenzoBianconi** [comment]
@dengqf6 now I think I got the point, GPIO14 should be a led pin. I will send you a patch to test.

**Comment by dengqf6** [comment]
@LorenzoBianconi Yes. AKA pin 35.

**Comment by LorenzoBianconi** [comment]
@dengqf6 could you please try this [patch](https://github.com/LorenzoBianconi/wireless-drivers-next/commit/60b1c72208c634d48d89c23cbcf382e2c4f74651)? I do not think you need to add any node in the device tree since the default LED is 0

**Comment by dengqf6** [comment]
Tried. Did not work.

**Comment by LorenzoBianconi** [comment]
Hi,

thx for testing..could you please double check the led entry is properly
created in /sys/class/leds/mt76-phyX?
Moreover, could you please double check the trigger?
You can try to change led pin and polarity in debug filesystem led_pin and
led_active

Regards,
Lorenzo

**Comment by dengqf6** [comment]
@LorenzoBianconi The mt76-phyX were not registered.
The mt76 version is openwrt/mt76@d3a58958 (in OpenWrt master). Is that the cause?

**Comment by LorenzoBianconi** [comment]
Have you applied the patch I pointed out in the previous message?

**Comment by dengqf6** [comment]
Yes

**Comment by LorenzoBianconi** [comment]
@dengqf6 : got it, we are missing this [patch](https://github.com/LorenzoBianconi/mt76/commit/e1cb717eb6c5f0f5f616edfd77670e00dcad1391) for mt76 github repo.
Could you please try to use this [mt76](https://github.com/LorenzoBianconi/mt76/tree/mt76-devel) branch?

**Comment by dengqf6** [comment]
It's working now. Thanks!

**Comment by i3roly** [comment]
hi,

i am having the same issue with no WIFI LEDS. 

> obj-$(CPTCFG_MT7615E) += mt7615e.o
EXTRA_CFLAGS += -Werror -DCONFIG_MT76_LEDS

mt7615e-y := pci.o init.o dma.o eeprom.o main.o mmio.o mcu.o mac.o \
             trace.o debugfs.o


is present in the makefile. could you please give some suggestions as to why the LEDs are not working? i am surprised they work for dengqf6 but not myself...
