### ISSUE TITLE
When I set WAP3 for the 2.4G wireless of the MT7620A, the 2.4G wireless of the MT7620A will not work for me.

### ISSUE THREAD

**Issue by daiaji** [openwrt/mt76#335]
Even if I change the 2.4G wireless encryption method of MT7620A device from WPA2-PSK / WPA3-SAE Mixed Mode back to WPA-PSK / WPA2-PSK Mixed Mode, the 2.4G wireless of MT7620A will not work for me unless I am after this reboot the router.
The ACRH17 I used for ipq40xx did not have this problem.

**Comment by lukasz1992** [comment]
mt7620a is not supported by mt76 driver

**Comment by dangowrt** [comment]
Please report this problem at the right place, which for the rt2x00 driver is the linux-wireless mailing list http://vger.kernel.org/vger-lists.html#linux-wireless
