### ISSUE TITLE
Wifi error automatically disconnected

### ISSUE THREAD

**Issue by 9000000** [openwrt/mt76#337]
Xiaomi r3g v1
I see the recent updates very much error about wifi, wifi even automatically turned off

daemon.notice hostapd: wlan0: AP-STA-DISCONNECTED 10:98:c3:12:0f:1c
Sun Dec 22 14:39:50 2019 daemon.info hostapd: wlan0: STA 10:98:c3:12:0f:1c IEEE 802.11: disassociated
Sun Dec 22 14:39:51 2019 daemon.info hostapd: wlan0: STA 10:98:c3:12:0f:1c IEEE 802.11: deauthenticated due to inactivity (timer DEAUTH/REMOVE)
Sun Dec 22 14:40:43 2019 daemon.info hostapd: wlan0: STA 10:98:c3:12:0f:1c IEEE 802.11: authenticated
Sun Dec 22 14:40:43 2019 daemon.info hostapd: wlan0: STA 10:98:c3:12:0f:1c IEEE 802.11: associated (aid 4)
Sun Dec 22 14:40:43 2019 daemon.notice hostapd: wlan0: AP-STA-CONNECTED 10:98:c3:12:0f:1c
Sun Dec 22 14:40:43 2019 daemon.info hostapd: wlan0: STA 10:98:c3:12:0f:1c WPA: pairwise key handshake completed (RSN)
Sun Dec 22 14:40:43 2019 daemon.warn omcproxy: mld: ignoring invalid MLD-message of type 143 from :: on 0
Sun Dec 22 14:40:43 2019 daemon.info dnsmasq-dhcp[3201]: DHCPREQUEST(br-lan) 192.168.7.190 10:98:c3:12:0f:1c
Sun Dec 22 14:40:43 2019 daemon.info dnsmasq-dhcp[3201]: DHCPACK(br-lan) 192.168.7.190 10:98:c3:12:0f:1c Galaxy-Note-9
Sun Dec 22 14:40:44 2019 daemon.warn omcproxy: mld: ignoring invalid MLD-message of type 143 from :: on 0
Sun Dec 22 14:48:22 2019 daemon.notice hostapd: wlan0: AP-STA-DISCONNECTED 10:98:c3:12:0f:1c
Sun Dec 22 14:48:22 2019 daemon.info hostapd: wlan0: STA 10:98:c3:12:0f:1c IEEE 802.11: disassociated
Sun Dec 22 14:48:23 2019 daemon.info hostapd: wlan0: STA 10:98:c3:12:0f:1c IEEE 802.11: deauthenticated due to inactivity (timer DEAUTH/REMOVE)
Sun Dec 22 15:06:45 2019 daemon.info hostapd: wlan0: STA 10:98:c3:12:0f:1c IEEE 802.11: authenticated
Sun Dec 22 15:06:45 2019 daemon.info hostapd: wlan0: STA 10:98:c3:12:0f:1c IEEE 802.11: associated (aid 4)
Sun Dec 22 15:06:45 2019 daemon.notice hostapd: wlan0: AP-STA-CONNECTED 10:98:c3:12:0f:1c
Sun Dec 22 15:06:45 2019 daemon.info hostapd: wlan0: STA 10:98:c3:12:0f:1c WPA: pairwise key handshake completed (RSN)
Sun Dec 22 15:06:45 2019 daemon.warn omcproxy: mld: ignoring invalid MLD-message of type 143 from :: on 0
Sun Dec 22 15:06:45 2019 daemon.info dnsmasq-dhcp[3201]: DHCPREQUEST(br-lan) 192.168.7.190 10:98:c3:12:0f:1c
Sun Dec 22 15:06:45 2019 daemon.info dnsmasq-dhcp[3201]: DHCPACK(br-lan) 192.168.7.190 10:98:c3:12:0f:1c Galaxy-Note-9
Sun Dec 22 15:06:46 2019 daemon.warn omcproxy: mld: ignoring invalid MLD-message of type 143 from :: on 0
Sun Dec 22 15:10:19 2019 daemon.notice hostapd: wlan0: AP-STA-DISCONNECTED 34:ce:00:d3:c8:5c
Sun Dec 22 15:10:19 2019 daemon.info hostapd: wlan0: STA 34:ce:00:d3:c8:5c IEEE 802.11: authenticated
Sun Dec 22 15:10:19 2019 daemon.info hostapd: wlan0: STA 34:ce:00:d3:c8:5c IEEE 802.11: associated (aid 1)
Sun Dec 22 15:10:20 2019 daemon.notice hostapd: wlan0: AP-STA-CONNECTED 34:ce:00:d3:c8:5c
Sun Dec 22 15:10:20 2019 daemon.info hostapd: wlan0: STA 34:ce:00:d3:c8:5c WPA: pairwise key handshake completed (RSN)
Sun Dec 22 15:10:21 2019 daemon.info dnsmasq-dhcp[3201]: DHCPDISCOVER(br-lan) 34:ce:00:d3:c8:5c
Sun Dec 22 15:10:21 2019 daemon.info dnsmasq-dhcp[3201]: DHCPOFFER(br-lan) 192.168.7.229 34:ce:00:d3:c8:5c
Sun Dec 22 15:10:21 2019 daemon.info dnsmasq-dhcp[3201]: DHCPREQUEST(br-lan) 192.168.7.229 34:ce:00:d3:c8:5c
Sun Dec 22 15:10:21 2019 daemon.info dnsmasq-dhcp[3201]: DHCPACK(br-lan) 192.168.7.229 34:ce:00:d3:c8:5c
Sun Dec 22 15:11:24 2019 daemon.notice hostapd: wlan0: AP-STA-DISCONNECTED 78:00:9e:b4:27:ea
Sun Dec 22 15:11:24 2019 daemon.info hostapd: wlan0: STA 78:00:9e:b4:27:ea IEEE 802.11: disassociated due to inactivity
Sun Dec 22 15:11:25 2019 daemon.info hostapd: wlan0: STA 78:00:9e:b4:27:ea IEEE 802.11: deauthenticated due to inactivity (timer DEAUTH/REMOVE)
Sun Dec 22 15:35:56 2019 daemon.notice hostapd: wlan0: AP-STA-DISCONNECTED 10:98:c3:12:0f:1c
Sun Dec 22 15:35:56 2019 daemon.info hostapd: wlan0: STA 10:98:c3:12:0f:1c IEEE 802.11: disassociated
Sun Dec 22 15:35:57 2019 daemon.info hostapd: wlan0: STA 10:98:c3:12:0f:1c IEEE 802.11: deauthenticated due to inactivity (timer DEAUTH/REMOVE)
Sun Dec 22 15:36:06 2019 daemon.info hostapd: wlan0: STA 78:00:9e:b4:27:ea IEEE 802.11: authenticated
Sun Dec 22 15:36:06 2019 daemon.info hostapd: wlan0: STA 78:00:9e:b4:27:ea IEEE 802.11: associated (aid 3)
Sun Dec 22 15:36:06 2019 daemon.notice hostapd: wlan0: AP-STA-CONNECTED 78:00:9e:b4:27:ea
Sun Dec 22 15:36:06 2019 daemon.info hostapd: wlan0: STA 78:00:9e:b4:27:ea WPA: pairwise key handshake completed (RSN)
Sun Dec 22 15:36:06 2019 daemon.warn omcproxy: mld: ignoring invalid MLD-message of type 143 from :: on 0
Sun Dec 22 15:36:07 2019 daemon.info dnsmasq-dhcp[3201]: DHCPDISCOVER(br-lan) 78:00:9e:b4:27:ea
Sun Dec 22 15:36:07 2019 daemon.info dnsmasq-dhcp[3201]: DHCPOFFER(br-lan) 192.168.7.163 78:00:9e:b4:27:ea
Sun Dec 22 15:36:07 2019 daemon.info dnsmasq-dhcp[3201]: DHCPREQUEST(br-lan) 192.168.7.163 78:00:9e:b4:27:ea
Sun Dec 22 15:36:07 2019 daemon.info dnsmasq-dhcp[3201]: DHCPACK(br-lan) 192.168.7.163 78:00:9e:b4:27:ea Galaxy-A5-2016
Sun Dec 22 15:53:09 2019 daemon.notice hostapd: wlan0: STA 8c:86:1e:da:95:a1 IEEE 802.11: did not acknowledge authentication response
Sun Dec 22 15:53:10 2019 daemon.info hostapd: wlan0: STA 8c:86:1e:da:95:a1 IEEE 802.11: associated (aid 4)
Sun Dec 22 15:53:10 2019 daemon.notice hostapd: wlan0: AP-STA-CONNECTED 8c:86:1e:da:95:a1
Sun Dec 22 15:53:10 2019 daemon.info hostapd: wlan0: STA 8c:86:1e:da:95:a1 WPA: pairwise key handshake completed (RSN)
Sun Dec 22 15:58:17 2019 daemon.notice hostapd: wlan0: AP-STA-DISCONNECTED 8c:86:1e:da:95:a1
Sun Dec 22 15:58:17 2019 daemon.info hostapd: wlan0: STA 8c:86:1e:da:95:a1 IEEE 802.11: disassociated due to inactivity
Sun Dec 22 15:58:18 2019 daemon.in

**Comment by lukasz1992** [comment]
which version of openwrt?
