### ISSUE TITLE
How to max tx power from 19dbm to 30dbm?

### ISSUE THREAD

**Issue by usama7628674** [openwrt/mt76#341]
I've edup-ac1605 mt76x2u(2T2R).Running a quick iwconfig command shows tx-power=19dbm.I've tried increasing it but it does not go beyond 19dbm.Its stuck there.

**Comment by usama7628674** [comment]
This is dmesg output when i connect device to my laptop
![mt76x2u](https://user-images.githubusercontent.com/29252277/71759811-aedec180-2ed4-11ea-9c35-f98d6f35d300.png)

Is it old version looking at ROM patch build and Build Time which says 2014 and 2015 respectively.Should I update my driver?
Right now its plug and play on kali linux.

**Comment by rufengsuixing** [comment]
try to set country to Australia

**Comment by usama7628674** [comment]
`iwlist wlan1 txpower` shows

`Txpower=19dbm    (79dbm)`  which is very low.

**Comment by usama7628674** [comment]
@rufengsuixing It does not work this way

**Comment by usama7628674** [comment]
This is tied to eeprom and I think devs havent implemented tx-power control.

**Comment by usama7628674** [comment]
RTL8812au is the best chipset mediatek is shit full of bugs
