### ISSUE TITLE
mt7615 on netgear r6260

### ISSUE THREAD

**Issue by bricco1981** [openwrt/mt76#351]
iw dev
phy#1
	Interface wlan1
		ifindex 11
		wdev 0x100000005
		addr 8c:3b:ad:xx:xx:xx
		ssid relle-5ghz
		type managed
		channel 100 (5500 MHz), width: 80 MHz, center1: 5530 MHz
		txpower 4.00 dBm
		multicast TXQ:
			qsz-byt	qsz-pkt	flows	drops	marks	overlmt	hashcoltx-bytes	tx-packets
			0	0	0	0	0	0	0	00

phy#0
	Interface wlan0
		ifindex 3
		wdev 0x1
		addr 8c:3b:ad:xx:xx:xx
		type managed
		txpower 23.00 dBm
		multicast TXQ:
			qsz-byt	qsz-pkt	flows	drops	marks	overlmt	hashcoltx-bytes	tx-packets
			0	0	0	0	0	0	0	00

iw reg get
global
country 00: DFS-UNSET
	(2402 - 2472 @ 40), (N/A, 20), (N/A)
	(2457 - 2482 @ 20), (N/A, 20), (N/A), AUTO-BW, PASSIVE-SCAN
	(2474 - 2494 @ 20), (N/A, 20), (N/A), NO-OFDM, PASSIVE-SCAN
	(5170 - 5250 @ 80), (N/A, 20), (N/A), AUTO-BW
	(5250 - 5330 @ 80), (N/A, 20), (0 ms), DFS, AUTO-BW, PASSIVE-SCAN
	(5490 - 5730 @ 160), (N/A, 20), (0 ms), DFS, PASSIVE-SCAN
	(5735 - 5835 @ 80), (N/A, 20), (N/A), PASSIVE-SCAN
	(57240 - 63720 @ 2160), (N/A, 0), (N/A)

`hi, txpower on mt 7615 only 4dbm, also the rx rate still low and only at 20/40 Mhz, tx rate looks good.

**Comment by nicefile** [comment]
Got no problem using recent official 19.07.01 @R6260
 I have region IN (India) under OpenWrt and 22db output for 5Ghz no problem

**Comment by bricco1981** [comment]
still same problem on last snapshot, i don't see any 19.07.01 for this device, mabie you used image for r 6350

**Comment by bricco1981** [comment]
i'm trying to compile and install snapshot every day but this problem still here, very bad range, the radio mt7603 is over the top, working really good.
