### ISSUE TITLE
wlan0/pcie0 with both 2.4/5GHz (wlan1/pcie1 with only 5GHz), but unusable on MT7615

### ISSUE THREAD

**Issue by i3roly** [openwrt/mt76#356]
hi,

i am just curious as to why the first pcie interface for the MT7615 is capable of doing 5GHz, is reported in the kernel as capable of doing so, but is actually unable to do it.

i noticed this peculiarity when playing with the 'auto' settings in hostapd for interface 0. hostapd liked the 5Ghz channels better than the 2Ghz ones, and thus selected that and actually put it in vht160. iw dev reports things fine, aside from the strange low dBm for a 5Ghz band, but i cannot connect.

> root@DD-WRT:~# iw dev
phy#1
        Interface ath1
                ifindex 11
                wdev 0x100000002
                addr 74:da:da:cb:59:b1
                ssid AGT1337-5.0G
                type AP
                channel 104 (5520 MHz), width: 160 MHz, center1: 5590 MHz
                txpower 24.00 dBm
                multicast TXQ:
                        qsz-byt qsz-pkt flows   drops   marks   overlmt hashcol tx-bytes        tx-packets
                        0       0       0       0       0       0       0       0               0
phy#0
        Interface ath0
                ifindex 10
                wdev 0x2
                addr 74:da:da:cb:59:b0
                ssid AGT1337-2.4G
                type AP
                channel 36 (5180 MHz), width: 40 MHz, center1: 5190 MHz
                txpower 16.00 dBm
                multicast TXQ:
                        qsz-byt qsz-pkt flows   drops   marks   overlmt hashcol tx-bytes        tx-packets
                        0       0       0       0       0       0       0       0               0

i locked down this radio using the ieee-freq-limit so users can enjoy auto settings, but i wanted to get some insight as to what is limiting/stopping this device from going dual 5GHz or 2.4GHz.

it is stranger that (in my other ticket) interface 1 does not report any 2.4GHz bands, yet interface 0 will report 5.0GHz bands. this lack of symmetry is something i was hoping to get comments on.

**Comment by nbd168** [comment]
Many manufacturers don't bother to program the EEPROM properly to limit the bands.
Just because the chipset supports both bands doesn't mean that the extra band actually works. There might just be a frontend missing on the hardware side.
Either way, this does not appear to be a mt76 bug...
