### ISSUE TITLE
To add support for mt7610e.

### ISSUE THREAD

**Issue by hero18688** [openwrt/mt76#36]
I hope this was in your schedule.

**Comment by nbd168** [comment]
It's currently not on my schedule

**Comment by srdjanrosic** [comment]
Hi, looking for an update, is it likely that mt76 will be made to work with mt7610e?

**Comment by grantg182** [comment]
Just wondering if there's been any headway on this?

**Comment by ptpt52** [comment]
@nbd168 hi
I noticed that the latest code adds support for mt7610, will it support mt7610e? Is the support of soc already available. How long does it take for pcie support? Can I do something?

**Comment by LorenzoBianconi** [comment]
>
> @nbd168 <https://github.com/nbd168> hi
> I noticed that the latest code adds support for mt7610, will it support
> mt7610e? Is the support of soc already available. How long does it take for
> pcie support? Can I do something?
>

Hi,

we are currently working on mt7610e/mt7650e support. For the moment just
STA mode is supported, but I will work on AP support soon.
Regards,

Lorenzo

-- 
UNIX is Sexy: who | grep -i blonde | talk; cd ~; wine; talk; touch; unzip;
touch; strip; gasp; finger; gasp; mount; fsck; more; yes; gasp; umount;
make clean; sleep

**Comment by jsantala** [comment]
Please also keep adhoc and mesh in mind, thanks! :)
