### ISSUE TITLE
MT7621|MT7612E: 5GHz low bitrait and poor speed.

### ISSUE THREAD

**Issue by Openwrtfunboy** [openwrt/mt76#365]
Only one device (TV box) is connected to my 5 GHz network, the first time after rebooting the router (or chip) the bitrate is from 130 to 450 mbs, which gives the entire speed of my connection, but after a while (about a day) the bitrate drops to 30- 60, which gives an extremely low speed even for viewing in 720. Is there any way to fix the bitrate on the 5GHz channel?

I change many channels and countries(current US), but that dont solve the problem.

It is also worth mentioning that the connection goes through a thick concrete wall and the router shows only 2 sticks of 4 (-82 dBm).

**Comment by Openwrtfunboy** [comment]
I also noticed that the bitrait stopped at 65 megabits.

**Comment by Openwrtfunboy** [comment]
I noticed that if several clients are connected to the network, then there is no problem. Perhaps i can somehow manually fixate the minimum bitrate?

**Comment by Openwrtfunboy** [comment]
@JFtico Can you test 5Ghz?

**Comment by carras** [comment]
any luck with this? I have issues too.
