### ISSUE TITLE
mt7621:  samba 4 : downloading files from the server is very slowly since kernel-4.14.171

### ISSUE THREAD

**Issue by siwind** [openwrt/mt76#372]
Device: newifi-d2,  there is a usb disk connected to the router,  samba 4.11-4(4.11-6) running on the router.

Files downloading has been very slowly since the kernel version was upgraded to 4.14.171+ in openwrt master branch.  Openwrt-v19.07.2 is the same problem.  

The reason is not known whether it is caused by kernel, mt76 driver or samba4 software.

After the router downgrade to openwrt-19.07.1 or lower,  files transfer to and from the samba4 server (in router) is normal.

**Comment by lukasz1992** [comment]
Try transfer on LAN network - we'll see if it is because of mt76 driver.

**Comment by siwind** [comment]
It is caused by enable "tcp_bbr" kernel module.  After remove tcp_bbr, the performance is normal.
So i close this issue.
