### ISSUE TITLE
mt 7628 - 2.4G wifi very low range, unreliable, auth problems

### ISSUE THREAD

**Issue by nx518** [openwrt/mt76#378]
```
Model	TP-Link Archer C50 v4
Architecture	MediaTek MT7628AN ver:1 eco:2
Firmware Version	OpenWrt 19.07.0 r10860-a3ffeb413b / LuCI openwrt-19.07 branch git-20.081.71863-12f0dac
Kernel Version	4.14.162
```

The 2.4G wifi has several issus on this device: Range is really low,  >4m results in disconnect, auth fails often, speed is low.

I tried disabling Legacy Rates, WMM, Crack, Disass on low ack, but it did not help.

Anyone has this device running with 2.4G successfully?

**Comment by Vonger** [comment]
Try this patch https://github.com/openwrt/mt76/pull/426

**Comment by dtrautmann** [comment]
Could you please try if this fixes your problem: #442

**Comment by nx518** [comment]
Thanks for the note, I will try it within 1 month and report here.

**Comment by nx518** [comment]
Tested #442 on my Archer C50 v4.
Fixed the issues for me, thanks!

**Comment by rotanid** [comment]
@nx518 please don't close an issue as long as the fix is not merged into the code base, the issue still exists

**Comment by nx518** [comment]
ok

**Comment by adelton** [comment]
@rotanid Given https://github.com/openwrt/mt76/pull/442 seems to have been merged, should this issues still be open?

**Comment by rotanid** [comment]
@adelton ok @nx518

**Comment by Sivanand-vp** [comment]
Hiiii,


How to fix this issue ?

**Comment by adelton** [comment]
@Sivanand-vp I'm no longer actively using that hardware but I'd recommend opening a new issue with full information about the hardware and software you use and the exact symptoms you see. You say "this issue" but I find it unlikely that you are on 19.07.0 that the original poster used six years ago. In which case you simply don't have the same issue.
