### ISSUE TITLE
Support of MT7615D available?

### ISSUE THREAD

**Issue by jneuhauser** [openwrt/mt76#383]
Hello @nbd168,

firstly thanks for your efforts to this great open source driver.
I want to switch my apu2 board from qualcomm wireless to mt76 based minipcie cards.

Is the mt7615d hw configuration (2x2 5 ghz ac and 2x2 2.4 ghz n) supported by this driver?
Here is one miniPCIe board from AsiaRF:
https://www.asiarf.com/shop/wifi-wlan/wifi_mini_pcie/wifi-mini-pcie-module-mtk-mt7615-4x4-11ac-5g-ws3294-manufacturer/

Many thanks,
Johann

**Comment by mrkiko** [comment]
DBDC is supported but is experimental.

Personal curiosity: why the switch?

thanks!

Enrico

**Comment by jneuhauser** [comment]
Thank you for the info...

Because is dislike qualcomm ;-)
And because a friend with a apu2c4 would by my used ones, but i need a replacement.

**Comment by qiuzi** [comment]
@mrkiko How to open the experimental DBDC?
