### ISSUE TITLE
WHICH ONE SHOULD BE USED FOR  MT7630e? FROM github.com/neurobin/MT7630E THERE HAVE TWO ERREOS

### ISSUE THREAD

**Issue by JUPITER-KOU** [openwrt/mt76#396]
WHICH ONE SHOULD BE USED FOR  MT7630e? 
FROM github.com/neurobin/MT7630E,WHEN WE MAKE, THERE HAVE TWO ERREOS.

MY OS IS KALI LINUX 5.4.19 (KALI LINUX 2020.1B VERSION)

**Comment by nbd168** [comment]
Use this one, not the one from the repository you linked to.
