### ISSUE TITLE
MT7630e 's TWO ERRORS!

### ISSUE THREAD

**Issue by JUPITER-KOU** [openwrt/mt76#397]
root@X550CC:/home/gjp/MT7630E-pie-fix# ./install
make -C /lib/modules/5.4.0-kali4-rt-amd64/build M=/home/gjp/MT7630E-pie-fix/rt2x00 modules
make[1]: 进入目录“/usr/src/linux-headers-5.4.0-kali4-rt-amd64”
  CC [M]  /home/gjp/MT7630E-pie-fix/rt2x00/rt2x00dev.o
In file included from /home/gjp/MT7630E-pie-fix/rt2x00/rt2x00dev.c:32:
/home/gjp/MT7630E-pie-fix/rt2x00/rt2x00.h: In function ‘rt2x00_rf_read’:
/home/gjp/MT7630E-pie-fix/rt2x00/rt2x00.h:98:19: error: expected ‘(’ before ‘static’
   98 | #define __inline  static inline
      |                   ^~~~~~
/usr/src/linux-headers-5.4.0-kali4-common-rt/include/linux/compiler_types.h:210:24: note: in expansion of macro ‘__inline’
  210 | #define asm_inline asm __inline
      |                        ^~~~~~~~
/usr/src/linux-headers-5.4.0-kali4-common-rt/arch/x86/include/asm/bug.h:35:2: note: in expansion of macro ‘asm_inline’
   35 |  asm_inline volatile("1:\t" ins "\n"    \
      |  ^~~~~~~~~~
/usr/src/linux-headers-5.4.0-kali4-common-rt/arch/x86/include/asm/bug.h:73:2: note: in expansion of macro ‘_BUG_FLAGS’
   73 |  _BUG_FLAGS(ASM_UD2, 0);     \
      |  ^~~~~~~~~~
/usr/src/linux-headers-5.4.0-kali4-common-rt/include/asm-generic/bug.h:62:57: note: in expansion of macro ‘BUG’
   62 | #define BUG_ON(condition) do { if (unlikely(condition)) BUG(); } while (0)
      |                                                         ^~~
/home/gjp/MT7630E-pie-fix/rt2x00/rt2x00.h:2453:2: note: in expansion of macro ‘BUG_ON’
 2453 |  BUG_ON(word < 1 || word > rt2x00dev->ops->rf_size / sizeof(u32));
      |  ^~~~~~
In file included from /usr/src/linux-headers-5.4.0-kali4-common-rt/include/linux/bug.h:5,
                 from /usr/src/linux-headers-5.4.0-kali4-common-rt/include/linux/thread_info.h:12,
                 from /usr/src/linux-headers-5.4.0-kali4-common-rt/arch/x86/include/asm/preempt.h:7,
                 from /usr/src/linux-headers-5.4.0-kali4-common-rt/include/linux/preempt.h:78,
                 from /usr/src/linux-headers-5.4.0-kali4-common-rt/include/linux/spinlock.h:51,
                 from /usr/src/linux-headers-5.4.0-kali4-common-rt/include/linux/seqlock.h:36,
                 from /usr/src/linux-headers-5.4.0-kali4-common-rt/include/linux/time.h:6,
                 from /usr/src/linux-headers-5.4.0-kali4-common-rt/include/linux/stat.h:19,
                 from /usr/src/linux-headers-5.4.0-kali4-common-rt/include/linux/module.h:10,
                 from /home/gjp/MT7630E-pie-fix/rt2x00/rt2x00dev.c:28:
/usr/src/linux-headers-5.4.0-kali4-common-rt/arch/x86/include/asm/bug.h:35:22: error: expected identifier or ‘(’ before string constant
   35 |  asm_inline volatile("1:\t" ins "\n"    \
      |                      ^~~~~~
/usr/src/linux-headers-5.4.0-kali4-common-rt/arch/x86/include/asm/bug.h:73:2: note: in expansion of macro ‘_BUG_FLAGS’
   73 |  _BUG_FLAGS(ASM_UD2, 0);     \
      |  ^~~~~~~~~~
/usr/src/linux-headers-5.4.0-kali4-common-rt/include/asm-generic/bug.h:62:57: note: in expansion of macro ‘BUG’
   62 | #define BUG_ON(condition) do { if (unlikely(condition)) BUG(); } while (0)
      |                                                         ^~~
/home/gjp/MT7630E-pie-fix/rt2x00/rt2x00.h:2453:2: note: in expansion of macro ‘BUG_ON’
 2453 |  BUG_ON(word < 1 || word > rt2x00dev->ops->rf_size / sizeof(u32));
      |  ^~~~~~
In file included from /home/gjp/MT7630E-pie-fix/rt2x00/rt2x00dev.c:32:
/home/gjp/MT7630E-pie-fix/rt2x00/rt2x00.h:98:19: warning: ISO C90 forbids mixed declarations and code [-Wdeclaration-after-statement]
   98 | #define __inline  static inline
      |                   ^~~~~~
/usr/src/linux-headers-5.4.0-kali4-common-rt/include/linux/compiler_types.h:210:24: note: in expansion of macro ‘__inline’
  210 | #define asm_inline asm __inline
      |                        ^~~~~~~~
/usr/src/linux-headers-5.4.0-kali4-common-rt/arch/x86/include/asm/bug.h:35:2: note: in expansion of macro ‘asm_inline’
   35 |  asm_inline volatile("1:\t" ins "\n"    \
      |  ^~~~~~~~~~
/usr/src/linux-headers-5.4.0-kali4-common-rt/arch/x86/include/asm/bug.h:73:2: note: in expansion of macro ‘_BUG_FLAGS’
   73 |  _BUG_FLAGS(ASM_UD2, 0);     \
      |  ^~~~~~~~~~
/usr/src/linux-headers-5.4.0-kali4-common-rt/include/asm-generic/bug.h:62:57: note: in expansion of macro ‘BUG’
   62 | #define BUG_ON(condition) do { if (unlikely(condition)) BUG(); } while (0)
      |                                                         ^~~
/home/gjp/MT7630E-pie-fix/rt2x00/rt2x00.h:2453:2: note: in expansion of macro ‘BUG_ON’
 2453 |  BUG_ON(word < 1 || word > rt2x00dev->ops->rf_size / sizeof(u32));
      |  ^~~~~~
/home/gjp/MT7630E-pie-fix/rt2x00/rt2x00.h: In function ‘rt2x00_rf_write’:
/home/gjp/MT7630E-pie-fix/rt2x00/rt2x00.h:98:19: error: expected ‘(’ before ‘static’
   98 | #define __inline  static inline
      |                   ^~~~~~
/usr/src/linux-headers-5.4.0-kali4-common-rt/include/linux/compiler_types.h:210:24: note: in expansion of macro ‘__inline’
  210 | #define asm_inline asm __inline
      |                        ^~~~~~~~
/usr/src/linux-headers-5.4.0-kali4-common-rt/arch/x86/include/asm/bug.h:35:2: note: in expansion of macro ‘asm_inline’
   35 |  asm_inline volatile("1:\t" ins "\n"    \
      |  ^~~~~~~~~~
/usr/src/linux-headers-5.4.0-kali4-common-rt/arch/x86/include/asm/bug.h:73:2: note: in expansion of macro ‘_BUG_FLAGS’
   73 |  _BUG_FLAGS(ASM_UD2, 0);     \
      |  ^~~~~~~~~~
/usr/src/linux-headers-5.4.0-kali4-common-rt/include/asm-generic/bug.h:62:57: note: in expansion of macro ‘BUG’
   62 | #define BUG_ON(condition) do { if (unlikely(condition)) BUG(); } while (0)
      |                                                         ^~~
/home/gjp/MT7630E-pie-fix/rt2x00/rt2x00.h:2460:2: note: in expansion of macro ‘BUG_ON’
 2460 |  BUG_ON(word < 1 || word > rt2x00dev->ops->rf_size / sizeof(u32));
      |  ^~~~~~
In file included from /usr/src/linux-headers-5.4.0-kali4-common-rt/include/linux/bug.h:5,
                 from /usr/src/linux-headers-5.4.0-kali4-common-rt/include/linux/thread_info.h:12,
                 from /usr/src/linux-headers-5.4.0-kali4-common-rt/arch/x86/include/asm/preempt.h:7,
                 from /usr/src/linux-headers-5.4.0-kali4-common-rt/include/linux/preempt.h:78,
                 from /usr/src/linux-headers-5.4.0-kali4-common-rt/include/linux/spinlock.h:51,
                 from /usr/src/linux-headers-5.4.0-kali4-common-rt/include/linux/seqlock.h:36,
                 from /usr/src/linux-headers-5.4.0-kali4-common-rt/include/linux/time.h:6,
                 from /usr/src/linux-headers-5.4.0-kali4-common-rt/include/linux/stat.h:19,
                 from /usr/src/linux-headers-5.4.0-kali4-common-rt/include/linux/module.h:10,
                 from /home/gjp/MT7630E-pie-fix/rt2x00/rt2x00dev.c:28:
/usr/src/linux-headers-5.4.0-kali4-common-rt/arch/x86/include/asm/bug.h:35:22: error: expected identifier or ‘(’ before string constant
   35 |  asm_inline volatile("1:\t" ins "\n"    \
      |                      ^~~~~~
/usr/src/linux-headers-5.4.0-kali4-common-rt/arch/x86/include/asm/bug.h:73:2: note: in expansion of macro ‘_BUG_FLAGS’
   73 |  _BUG_FLAGS(ASM_UD2, 0);     \
      |  ^~~~~~~~~~
/usr/src/linux-headers-5.4.0-kali4-common-rt/include/asm-generic/bug.h:62:57: note: in expansion of macro ‘BUG’
   62 | #define BUG_ON(condition) do { if (unlikely(condition)) BUG(); } while (0)
      |                                                         ^~~
/home/gjp/MT7630E-pie-fix/rt2x00/rt2x00.h:2460:2: note: in expansion of macro ‘BUG_ON’
 2460 |  BUG_ON(word < 1 || word > rt2x00dev->ops->rf_size / sizeof(u32));
      |  ^~~~~~
In file included from /home/gjp/MT7630E-pie-fix/rt2x00/rt2x00dev.c:32:
/home/gjp/MT7630E-pie-fix/rt2x00/rt2x00.h:98:19: warning: ISO C90 forbids mixed declarations and code [-Wdeclaration-after-statement]
   98 | #define __inline  static inline
      |                   ^~~~~~
/usr/src/linux-headers-5.4.0-kali4-common-rt/include/linux/compiler_types.h:210:24: note: in expansion of macro ‘__inline’
  210 | #define asm_inline asm __inline
      |                        ^~~~~~~~
/usr/src/linux-headers-5.4.0-kali4-common-rt/arch/x86/include/asm/bug.h:35:2: note: in expansion of macro ‘asm_inline’
   35 |  asm_inline volatile("1:\t" ins "\n"    \
      |  ^~~~~~~~~~
/usr/src/linux-headers-5.4.0-kali4-common-rt/arch/x86/include/asm/bug.h:73:2: note: in expansion of macro ‘_BUG_FLAGS’
   73 |  _BUG_FLAGS(ASM_UD2, 0);     \
      |  ^~~~~~~~~~
/usr/src/linux-headers-5.4.0-kali4-common-rt/include/asm-generic/bug.h:62:57: note: in expansion of macro ‘BUG’
   62 | #define BUG_ON(condition) do { if (unlikely(condition)) BUG(); } while (0)
      |                                                         ^~~
/home/gjp/MT7630E-pie-fix/rt2x00/rt2x00.h:2460:2: note: in expansion of macro ‘BUG_ON’
 2460 |  BUG_ON(word < 1 || word > rt2x00dev->ops->rf_size / sizeof(u32));
      |  ^~~~~~
/home/gjp/MT7630E-pie-fix/rt2x00/rt2x00dev.c: In function ‘rt2x00lib_beaconupdate_iter’:
/home/gjp/MT7630E-pie-fix/rt2x00/rt2x00.h:98:19: error: expected ‘(’ before ‘static’
   98 | #define __inline  static inline
      |                   ^~~~~~
/usr/src/linux-headers-5.4.0-kali4-common-rt/include/linux/compiler_types.h:210:24: note: in expansion of macro ‘__inline’
  210 | #define asm_inline asm __inline
      |                        ^~~~~~~~
/usr/src/linux-headers-5.4.0-kali4-common-rt/arch/x86/include/asm/bug.h:35:2: note: in expansion of macro ‘asm_inline’
   35 |  asm_inline volatile("1:\t" ins "\n"    \
      |  ^~~~~~~~~~
/usr/src/linux-headers-5.4.0-kali4-common-rt/arch/x86/include/asm/bug.h:79:2: note: in expansion of macro ‘_BUG_FLAGS’
   79 |  _BUG_FLAGS(ASM_UD2, BUGFLAG_WARNING|(flags));  \
      |  ^~~~~~~~~~
/usr/src/linux-headers-5.4.0-kali4-common-rt/include/asm-generic/bug.h:90:19: note: in expansion of macro ‘__WARN_FLAGS’
   90 | #define __WARN()  __WARN_FLAGS(BUGFLAG_TAINT(TAINT_WARN))
      |                   ^~~~~~~~~~~~
/usr/src/linux-headers-5.4.0-kali4-common-rt/include/asm-generic/bug.h:115:3: note: in expansion of macro ‘__WARN’
  115 |   __WARN();      \
      |   ^~~~~~
/home/gjp/MT7630E-pie-fix/rt2x00/rt2x00dev.c:259:2: note: in expansion of macro ‘WARN_ON’
  259 |  WARN_ON(rt2x00_is_usb(rt2x00dev));
      |  ^~~~~~~
In file included from /usr/src/linux-headers-5.4.0-kali4-common-rt/include/linux/bug.h:5,
                 from /usr/src/linux-headers-5.4.0-kali4-common-rt/include/linux/thread_info.h:12,
                 from /usr/src/linux-headers-5.4.0-kali4-common-rt/arch/x86/include/asm/preempt.h:7,
                 from /usr/src/linux-headers-5.4.0-kali4-common-rt/include/linux/preempt.h:78,
                 from /usr/src/linux-headers-5.4.0-kali4-common-rt/include/linux/spinlock.h:51,
                 from /usr/src/linux-headers-5.4.0-kali4-common-rt/include/linux/seqlock.h:36,
                 from /usr/src/linux-headers-5.4.0-kali4-common-rt/include/linux/time.h:6,
                 from /usr/src/linux-headers-5.4.0-kali4-common-rt/include/linux/stat.h:19,
                 from /usr/src/linux-headers-5.4.0-kali4-common-rt/include/linux/module.h:10,
                 from /home/gjp/MT7630E-pie-fix/rt2x00/rt2x00dev.c:28:
/usr/src/linux-headers-5.4.0-kali4-common-rt/arch/x86/include/asm/bug.h:35:22: error: expected identifier or ‘(’ before string constant
   35 |  asm_inline volatile("1:\t" ins "\n"    \
      |                      ^~~~~~
/usr/src/linux-headers-5.4.0-kali4-common-rt/arch/x86/include/asm/bug.h:79:2: note: in expansion of macro ‘_BUG_FLAGS’
   79 |  _BUG_FLAGS(ASM_UD2, BUGFLAG_WARNING|(flags));  \
      |  ^~~~~~~~~~
/usr/src/linux-headers-5.4.0-kali4-common-rt/include/asm-generic/bug.h:90:19: note: in expansion of macro ‘__WARN_FLAGS’
   90 | #define __WARN()  __WARN_FLAGS(BUGFLAG_TAINT(TAINT_WARN))
      |                   ^~~~~~~~~~~~
/usr/src/linux-headers-5.4.0-kali4-common-rt/include/asm-generic/bug.h:115:3: note: in expansion of macro ‘__WARN’
  115 |   __WARN();      \
      |   ^~~~~~
/home/gjp/MT7630E-pie-fix/rt2x00/rt2x00dev.c:259:2: note: in expansion of macro ‘WARN_ON’
  259 |  WARN_ON(rt2x00_is_usb(rt2x00dev));
      |  ^~~~~~~
In file included from /home/gjp/MT7630E-pie-fix/rt2x00/rt2x00dev.c:32:
/home/gjp/MT7630E-pie-fix/rt2x00/rt2x00.h:98:19: warning: ISO C90 forbids mixed declarations and code [-Wdeclaration-after-statement]
   98 | #define __inline  static inline
      |                   ^~~~~~
/usr/src/linux-headers-5.4.0-kali4-common-rt/include/linux/compiler_types.h:210:24: note: in expansion of macro ‘__inline’
  210 | #define asm_inline asm __inline
      |                        ^~~~~~~~
/usr/src/linux-headers-5.4.0-kali4-common-rt/arch/x86/include/asm/bug.h:35:2: note: in expansion of macro ‘asm_inline’
   35 |  asm_inline volatile("1:\t" ins "\n"    \
      |  ^~~~~~~~~~
/usr/src/linux-headers-5.4.0-kali4-common-rt/arch/x86/include/asm/bug.h:79:2: note: in expansion of macro ‘_BUG_FLAGS’
   79 |  _BUG_FLAGS(ASM_UD2, BUGFLAG_WARNING|(flags));  \
      |  ^~~~~~~~~~
/usr/src/linux-headers-5.4.0-kali4-common-rt/include/asm-generic/bug.h:90:19: note: in expansion of macro ‘__WARN_FLAGS’
   90 | #define __WARN()  __WARN_FLAGS(BUGFLAG_TAINT(TAINT_WARN))
      |                   ^~~~~~~~~~~~
/usr/src/linux-headers-5.4.0-kali4-common-rt/include/asm-generic/bug.h:115:3: note: in expansion of macro ‘__WARN’
  115 |   __WARN();      \
      |   ^~~~~~
/home/gjp/MT7630E-pie-fix/rt2x00/rt2x00dev.c:259:2: note: in expansion of macro ‘WARN_ON’
  259 |  WARN_ON(rt2x00_is_usb(rt2x00dev));
      |  ^~~~~~~
make[3]: *** [/usr/src/linux-headers-5.4.0-kali4-common-rt/scripts/Makefile.build:271：/home/gjp/MT7630E-pie-fix/rt2x00/rt2x00dev.o] 错误 1
make[2]: *** [/usr/src/linux-headers-5.4.0-kali4-common-rt/Makefile:1665：/home/gjp/MT7630E-pie-fix/rt2x00] 错误 2
make[1]: *** [/usr/src/linux-headers-5.4.0-kali4-common-rt/Makefile:179：sub-make] 错误 2
make[1]: 离开目录“/usr/src/linux-headers-5.4.0-kali4-rt-amd64”
make: *** [Makefile:9：all] 错误 2
root@X550CC:/home/gjp/MT7630E-pie-fix# make clean
make -C /lib/modules/`uname -r`/build M=/home/gjp/MT7630E-pie-fix/rt2x00 clean
make[1]: 进入目录“/usr/src/linux-headers-5.4.0-kali4-rt-amd64”
make[1]: 离开目录“/usr/src/linux-headers-5.4.0-kali4-rt-amd64”
make -C /lib/modules/`uname -r`/build M=/home/gjp/MT7630E-pie-fix/btloader clean
make[1]: 进入目录“/usr/src/linux-headers-5.4.0-kali4-rt-amd64”
make[1]: 离开目录“/usr/src/linux-headers-5.4.0-kali4-rt-amd64”
root@X550CC:/home/gjp/MT7630E-pie-fix#

**Comment by nbd168** [comment]
That's a different driver than the one in this repo.
