### ISSUE TITLE
MT7620A Slow 2.4Ghz N Speed - Archer C5W V4

### ISSUE THREAD

**Issue by leonardcoutinho** [openwrt/mt76#404]
Guys, My device with mt7620a have slow 2.4Ghz speed with devices, I can't past 20megabit in one stream, in stock firmware it easily beat 35megabit. My Archer C5W run an 19.07.3 build.

**Comment by dangowrt** [comment]
MT7620A is supported only by `rt2x00` driver, so this is the wrong place for this report.
https://wireless.wiki.kernel.org/en/users/drivers/rt2800pci
rt2x00 is known to not reach the same performance as the vendor driver, it's still missing a bunch of features (though things have improved quite a bit in the past years, from less than 6 MBit/s to 20 MBit/s in AP mode is already quite an improvement)
