### ISSUE TITLE
mt7603 error when wmm mode is turned off

### ISSUE THREAD

**Issue by 9000000** [openwrt/mt76#424]
I want to turn off wmm to use the 2.4 GHz band more stable, but the download speed is too low, the download speed is only 6 Mbp

@nbd168 Can you fix this error?

I use the latest build on xiaomi router mir3g v1

**Comment by nbd168** [comment]
Disabling WMM is incompatible with 802.11n.

**Comment by 9000000** [comment]
i used the latest version but still got the error, i know wmm socks won't support n band, But I need the above stability in g band rather than a flicker connection on n band, I switch to g band but the download speed is too low only 6MBit, then want the maximum speed on g band is 54Mb Can you fix that, thanks for your contributions very much
@nbd168
