### ISSUE TITLE
Xiaomi Mi Router 3 Pro switch   mt7530   BUG

### ISSUE THREAD

**Issue by 643406834** [openwrt/mt76#437]
![photo_2020-08-15_18-57-27](https://user-images.githubusercontent.com/39716940/90325711-9ded4700-dfb1-11ea-96e6-96279e003eec.jpg)

![批注 2020-08-16 111445](https://user-images.githubusercontent.com/39716940/90325722-b9f0e880-dfb1-11ea-8e22-7b6a33adc0b9.png)

**Comment by dengqf6** [comment]
mt76 is a wireless driver, it has nothing to do with mt7530.
