### ISSUE TITLE
MT7615 stopped functioning (Redmi AC2100, Dumb AP, OpenWrt SNAPSHOT r14538-d643b10a76)

### ISSUE THREAD

**Issue by morhimi** [openwrt/mt76#451]
Hi all,

I was advised to this repo after posting on the OpenWrt forum here:
https://forum.openwrt.org/t/new-xiaomi-router-ac2100/48101/865?u=morhimi

I'm running 4 Dumb APs, all the same hardware - Redmi AC2100.
In the last 2 months, they were pretty stable and 5ghz worked mostly flawlessly.

I usually update them to latest master once a week, starting with 1 AP and if everything goes well continue with the rest.

In the last 7-10 days, I 4 different snapshots have 5ghz completely broken for me, the latest snapshot that is running fine for me is: `OpenWrt SNAPSHOT r14423-be9694aaa2`

basically clients connect successfully and stay connected, but there is no traffic at all, the 2.4ghz works fine.

let me know how can I assist with identifying the regression
my wireless config:

root@OpenWrt_RM2100_Kids:~# cat /etc/config/wireless

config wifi-device 'radio0'
	option type 'mac80211'
	option hwmode '11g'
	option path '1e140000.pcie/pci0000:00/0000:00:01.0/0000:02:00.0'
	option htmode 'HT20'
	option channel 'auto'
	option country 'IL'
	option legacy_rates '0'

config wifi-iface 'default_radio0'
	option device 'radio0'
	option network 'lan'
	option mode 'ap'
	option ssid 'StayAway'
	option key '********'
	option ieee80211r '1'
	option ft_over_ds '1'
	option ft_psk_generate_local '1'
	option nasid '88C3973DE8AE'
	option ieee80211k '1'
	option bss_transition '1'
	option time_advertisement '2'
	option time_zone 'IST-2IDT,M3.4.4/26,M10.5.0'
	option ieee80211v '1'
	option wnm_sleep_mode '1'
	option encryption 'psk2'

config wifi-device 'radio1'
	option type 'mac80211'
	option hwmode '11a'
	option path '1e140000.pcie/pci0000:00/0000:00:00.0/0000:01:00.0'
	option legacy_rates '0'
	option country 'IL'
	option htmode 'VHT80'
	option channel '52'
	option disabled '1'

config wifi-iface 'default_radio1'
	option device 'radio1'
	option network 'lan'
	option mode 'ap'
	option ssid 'StayAway'
	option key '********'
	option ieee80211r '1'
	option nasid '88C3973DE8AF'
	option ft_over_ds '1'
	option ft_psk_generate_local '1'
	option ieee80211k '1'
	option bss_transition '1'
	option time_advertisement '2'
	option time_zone 'IST-2IDT,M3.4.4/26,M10.5.0'
	option ieee80211v '1'
	option wnm_sleep_mode '1'
	option encryption 'psk2'
	option disabled '1'

**Comment by morhimi** [comment]
root@OpenWrt_RM2100_Kids:~# dmesg
[    0.000000] Linux version 5.4.66 (builder@buildhost) (gcc version 8.4.0 (OpenWrt GCC 8.4.0 r14538-d643b10a76)) #0 SMP Mon Sep 21 19:27:56 2020
[    0.000000] SoC Type: MediaTek MT7621 ver:1 eco:3
[    0.000000] printk: bootconsole [early0] enabled
[    0.000000] CPU0 revision is: 0001992f (MIPS 1004Kc)
[    0.000000] MIPS: machine is Xiaomi Redmi Router AC2100
[    0.000000] Initrd not found or empty - disabling initrd
[    0.000000] VPE topology {2,2} total 4
[    0.000000] Primary instruction cache 32kB, VIPT, 4-way, linesize 32 bytes.
[    0.000000] Primary data cache 32kB, 4-way, PIPT, no aliases, linesize 32 bytes
[    0.000000] MIPS secondary cache 256kB, 8-way, linesize 32 bytes.
[    0.000000] Zone ranges:
[    0.000000]   Normal   [mem 0x0000000000000000-0x0000000007ffffff]
[    0.000000]   HighMem  empty
[    0.000000] Movable zone start for each node
[    0.000000] Early memory node ranges
[    0.000000]   node   0: [mem 0x0000000000000000-0x0000000007ffffff]
[    0.000000] Initmem setup node 0 [mem 0x0000000000000000-0x0000000007ffffff]
[    0.000000] On node 0 totalpages: 32768
[    0.000000]   Normal zone: 288 pages used for memmap
[    0.000000]   Normal zone: 0 pages reserved
[    0.000000]   Normal zone: 32768 pages, LIFO batch:7
[    0.000000] percpu: Embedded 14 pages/cpu s26768 r8192 d22384 u57344
[    0.000000] pcpu-alloc: s26768 r8192 d22384 u57344 alloc=14*4096
[    0.000000] pcpu-alloc: [0] 0 [0] 1 [0] 2 [0] 3
[    0.000000] Built 1 zonelists, mobility grouping on.  Total pages: 32480
[    0.000000] Kernel command line: console=ttyS0,115200n8 rootfstype=squashfs,jffs2
[    0.000000] Dentry cache hash table entries: 16384 (order: 4, 65536 bytes, linear)
[    0.000000] Inode-cache hash table entries: 8192 (order: 3, 32768 bytes, linear)
[    0.000000] Writing ErrCtl register=00068400
[    0.000000] Readback ErrCtl register=00068400
[    0.000000] mem auto-init: stack:off, heap alloc:off, heap free:off
[    0.000000] Memory: 120584K/131072K available (5930K kernel code, 206K rwdata, 1272K rodata, 1284K init, 238K bss, 10488K reserved, 0K cma-reserved, 0K highmem)
[    0.000000] SLUB: HWalign=32, Order=0-3, MinObjects=0, CPUs=4, Nodes=1
[    0.000000] rcu: Hierarchical RCU implementation.
[    0.000000] rcu: RCU calculated value of scheduler-enlistment delay is 25 jiffies.
[    0.000000] NR_IRQS: 256
[    0.000000] random: get_random_bytes called from start_kernel+0x340/0x558 with crng_init=0
[    0.000000] CPU Clock: 880MHz
[    0.000000] clocksource: GIC: mask: 0xffffffffffffffff max_cycles: 0xcaf478abb4, max_idle_ns: 440795247997 ns
[    0.000000] clocksource: MIPS: mask: 0xffffffff max_cycles: 0xffffffff, max_idle_ns: 4343773742 ns
[    0.000008] sched_clock: 32 bits at 440MHz, resolution 2ns, wraps every 4880645118ns
[    0.007804] Calibrating delay loop... 583.68 BogoMIPS (lpj=1167360)
[    0.042001] pid_max: default: 32768 minimum: 301
[    0.046776] Mount-cache hash table entries: 1024 (order: 0, 4096 bytes, linear)
[    0.054003] Mountpoint-cache hash table entries: 1024 (order: 0, 4096 bytes, linear)
[    0.064447] rcu: Hierarchical SRCU implementation.
[    0.069892] smp: Bringing up secondary CPUs ...
[    2.311728] Primary instruction cache 32kB, VIPT, 4-way, linesize 32 bytes.
[    2.311739] Primary data cache 32kB, 4-way, PIPT, no aliases, linesize 32 bytes
[    2.311751] MIPS secondary cache 256kB, 8-way, linesize 32 bytes.
[    2.311853] CPU1 revision is: 0001992f (MIPS 1004Kc)
[    0.102665] Synchronize counters for CPU 1: done.
[    2.373061] Primary instruction cache 32kB, VIPT, 4-way, linesize 32 bytes.
[    2.373070] Primary data cache 32kB, 4-way, PIPT, no aliases, linesize 32 bytes
[    2.373079] MIPS secondary cache 256kB, 8-way, linesize 32 bytes.
[    2.373139] CPU2 revision is: 0001992f (MIPS 1004Kc)
[    0.167394] Synchronize counters for CPU 2: done.
[    2.434459] Primary instruction cache 32kB, VIPT, 4-way, linesize 32 bytes.
[    2.434467] Primary data cache 32kB, 4-way, PIPT, no aliases, linesize 32 bytes
[    2.434476] MIPS secondary cache 256kB, 8-way, linesize 32 bytes.
[    2.434538] CPU3 revision is: 0001992f (MIPS 1004Kc)
[    0.225260] Synchronize counters for CPU 3: done.
[    0.255142] smp: Brought up 1 node, 4 CPUs
[    0.263552] clocksource: jiffies: mask: 0xffffffff max_cycles: 0xffffffff, max_idle_ns: 7645041785100000 ns
[    0.273243] futex hash table entries: 1024 (order: 3, 32768 bytes, linear)
[    0.280318] pinctrl core: initialized pinctrl subsystem
[    0.287222] NET: Registered protocol family 16
[    0.302798] FPU Affinity set after 4688 emulations
[    0.319064] workqueue: max_active 576 requested for napi_workq is out of range, clamping between 1 and 512
[    0.330183] random: fast init done
[    0.333682] clocksource: Switched to clocksource GIC
[    0.340589] NET: Registered protocol family 2
[    0.346561] tcp_listen_portaddr_hash hash table entries: 512 (order: 0, 6144 bytes, linear)
[    0.354986] TCP established hash table entries: 1024 (order: 0, 4096 bytes, linear)
[    0.362573] TCP bind hash table entries: 1024 (order: 1, 8192 bytes, linear)
[    0.369568] TCP: Hash tables configured (established 1024 bind 1024)
[    0.376008] UDP hash table entries: 256 (order: 1, 8192 bytes, linear)
[    0.382491] UDP-Lite hash table entries: 256 (order: 1, 8192 bytes, linear)
[    0.389738] NET: Registered protocol family 1
[    0.394060] PCI: CLS 0 bytes, default 32
[    0.489621] 4 CPUs re-calibrate udelay(lpj = 1163264)
[    0.496146] workingset: timestamp_bits=14 max_order=15 bucket_order=1
[    0.513890] squashfs: version 4.0 (2009/01/31) Phillip Lougher
[    0.519671] jffs2: version 2.2 (NAND) (SUMMARY) (LZMA) (RTIME) (CMODE_PRIORITY) (c) 2001-2006 Red Hat, Inc.
[    0.530979] Block layer SCSI generic (bsg) driver version 0.4 loaded (major 251)
[    0.540086] mt7621_gpio 1e000600.gpio: registering 32 gpios
[    0.545986] mt7621_gpio 1e000600.gpio: registering 32 gpios
[    0.551766] mt7621_gpio 1e000600.gpio: registering 32 gpios
[    0.558215] Serial: 8250/16550 driver, 16 ports, IRQ sharing enabled
[    0.568243] printk: console [ttyS0] disabled
[    0.572544] 1e000c00.uartlite: ttyS0 at MMIO 0x1e000c00 (irq = 19, base_baud = 3125000) is a 16550A
[    0.581529] printk: console [ttyS0] enabled
[    0.589792] printk: bootconsole [early0] disabled
[    0.601712] mt7621-nand 1e003000.nand: Using programmed access timing: 31c07388
[    0.609270] nand: device found, Manufacturer ID: 0xc8, Chip ID: 0xd1
[    0.615617] nand: ESMT PSU1GA30DT
[    0.618934] nand: 128 MiB, SLC, erase size: 128 KiB, page size: 2048, OOB size: 64
[    0.626494] mt7621-nand 1e003000.nand: ECC strength adjusted to 4 bits
[    0.633042] mt7621-nand 1e003000.nand: Using programmed access timing: 21005134
[    0.640341] mt7621-nand 1e003000.nand: Using programmed access timing: 21005134
[    0.647637] Scanning device for bad blocks
[    2.628950] 10 fixed-partitions partitions found on MTD device mt7621-nand
[    2.635819] Creating 10 MTD partitions on "mt7621-nand":
[    2.641134] 0x000000000000-0x000000080000 : "Bootloader"
[    2.647794] 0x000000080000-0x0000000c0000 : "Config"
[    2.654272] 0x0000000c0000-0x000000100000 : "Bdata"
[    2.660598] 0x000000100000-0x000000140000 : "factory"
[    2.666935] 0x000000140000-0x000000180000 : "crash"
[    2.673218] 0x000000180000-0x0000001c0000 : "crash_syslog"
[    2.679973] 0x0000001c0000-0x000000200000 : "reserved0"
[    2.686688] 0x000000200000-0x000000600000 : "kernel_stock"
[    2.693465] 0x000000600000-0x000000a00000 : "kernel"
[    2.699923] 0x000000a00000-0x000007f80000 : "ubi"
[    2.707897] libphy: Fixed MDIO Bus: probed
[    2.736036] libphy: mdio: probed
[    2.739499] mt7530 mdio-bus:1f: MT7530 adapts as multi-chip module
[    2.747279] mtk_soc_eth 1e100000.ethernet eth0: mediatek frame engine at 0xbe100000, irq 21
[    2.757844] mt7621-pci 1e140000.pcie: Parsing DT failed
[    2.765820] NET: Registered protocol family 10
[    2.771918] Segment Routing with IPv6
[    2.775759] NET: Registered protocol family 17
[    2.780323] bridge: filtering via arp/ip/ip6tables is no longer available by default. Update your scripts to load br_netfilter if you need this.
[    2.793520] 8021q: 802.1Q VLAN Support v1.8
[    2.799585] mt7530 mdio-bus:1f: MT7530 adapts as multi-chip module
[    2.816782] libphy: dsa slave smi: probed
[    2.821248] mt7530 mdio-bus:1f wan (uninitialized): PHY [dsa-0.0:00] driver [Generic PHY]
[    2.831123] mt7530 mdio-bus:1f lan1 (uninitialized): PHY [dsa-0.0:02] driver [Generic PHY]
[    2.840862] mt7530 mdio-bus:1f lan2 (uninitialized): PHY [dsa-0.0:03] driver [Generic PHY]
[    2.850624] mt7530 mdio-bus:1f lan3 (uninitialized): PHY [dsa-0.0:04] driver [Generic PHY]
[    2.860444] mt7530 mdio-bus:1f: configuring for fixed/rgmii link mode
[    2.871693] DSA: tree 0 setup
[    2.874990] rt2880-pinmux pinctrl: pcie is already enabled
[    2.880491] mt7621-pci 1e140000.pcie: Error applying setting, reverse things back
[    2.888117] mt7621-pci-phy 1e149000.pcie-phy: PHY for 0xbe149000 (dual port = 1)
[    2.895701] mt7621-pci-phy 1e14a000.pcie-phy: PHY for 0xbe14a000 (dual port = 0)
[    3.002881] mt7621-pci-phy 1e149000.pcie-phy: Xtal is 40MHz
[    3.008464] mt7621-pci-phy 1e14a000.pcie-phy: Xtal is 40MHz
[    3.113744] mt7621-pci 1e140000.pcie: pcie2 no card, disable it (RST & CLK)
[    3.120696] mt7621-pci 1e140000.pcie: PCIE0 enabled
[    3.125572] mt7621-pci 1e140000.pcie: PCIE1 enabled
[    3.130457] mt7621-pci 1e140000.pcie: PCI coherence region base: 0x60000000, mask/settings: 0xf0000002
[    3.139906] mt7621-pci 1e140000.pcie: PCI host bridge to bus 0000:00
[    3.146274] pci_bus 0000:00: root bus resource [io  0x1e160000-0x1e16ffff]
[    3.153142] pci_bus 0000:00: root bus resource [mem 0x60000000-0x6fffffff]
[    3.160012] pci_bus 0000:00: root bus resource [bus 00-ff]
[    3.165541] pci 0000:00:00.0: [0e8d:0801] type 01 class 0x060400
[    3.171579] pci 0000:00:00.0: reg 0x10: [mem 0x00000000-0x7fffffff]
[    3.177850] pci 0000:00:00.0: reg 0x14: [mem 0x60400000-0x6040ffff]
[    3.184181] pci 0000:00:00.0: supports D1
[    3.188195] pci 0000:00:00.0: PME# supported from D0 D1 D3hot
[    3.194298] pci 0000:00:01.0: [0e8d:0801] type 01 class 0x060400
[    3.200338] pci 0000:00:01.0: reg 0x10: [mem 0x00000000-0x7fffffff]
[    3.206608] pci 0000:00:01.0: reg 0x14: [mem 0x60410000-0x6041ffff]
[    3.212927] pci 0000:00:01.0: supports D1
[    3.216940] pci 0000:00:01.0: PME# supported from D0 D1 D3hot
[    3.224090] pci 0000:01:00.0: [14c3:7615] type 00 class 0x000280
[    3.230165] pci 0000:01:00.0: reg 0x10: [mem 0x00000000-0x000fffff 64bit]
[    3.237111] pci 0000:01:00.0: 2.000 Gb/s available PCIe bandwidth, limited by 2.5 GT/s x1 link at 0000:00:00.0 (capable of 4.000 Gb/s with 5 GT/s x1 link)
[    3.252099] pci 0000:00:00.0: PCI bridge to [bus 01-ff]
[    3.257339] pci 0000:00:00.0:   bridge window [io  0x0000-0x0fff]
[    3.263432] pci 0000:00:00.0:   bridge window [mem 0x60000000-0x600fffff]
[    3.270217] pci 0000:00:00.0:   bridge window [mem 0x60100000-0x601fffff pref]
[    3.277434] pci_bus 0000:01: busn_res: [bus 01-ff] end is updated to 01
[    3.284254] pci 0000:02:00.0: [14c3:7603] type 00 class 0x028000
[    3.290324] pci 0000:02:00.0: reg 0x10: [mem 0x00000000-0x000fffff]
[    3.296722] pci 0000:02:00.0: PME# supported from D0 D3hot D3cold
[    3.304038] pci 0000:00:01.0: PCI bridge to [bus 02-ff]
[    3.309283] pci 0000:00:01.0:   bridge window [io  0x0000-0x0fff]
[    3.315375] pci 0000:00:01.0:   bridge window [mem 0x60200000-0x602fffff]
[    3.322159] pci 0000:00:01.0:   bridge window [mem 0x60300000-0x603fffff pref]
[    3.329374] pci_bus 0000:02: busn_res: [bus 02-ff] end is updated to 02
[    3.336030] pci 0000:00:00.0: BAR 0: no space for [mem size 0x80000000]
[    3.342643] pci 0000:00:00.0: BAR 0: failed to assign [mem size 0x80000000]
[    3.349620] pci 0000:00:01.0: BAR 0: no space for [mem size 0x80000000]
[    3.356224] pci 0000:00:01.0: BAR 0: failed to assign [mem size 0x80000000]
[    3.363182] pci 0000:00:00.0: BAR 8: assigned [mem 0x60000000-0x600fffff]
[    3.369969] pci 0000:00:00.0: BAR 9: assigned [mem 0x60100000-0x601fffff pref]
[    3.377184] pci 0000:00:01.0: BAR 8: assigned [mem 0x60200000-0x602fffff]
[    3.383971] pci 0000:00:01.0: BAR 9: assigned [mem 0x60300000-0x603fffff pref]
[    3.391190] pci 0000:00:00.0: BAR 1: assigned [mem 0x60400000-0x6040ffff]
[    3.397981] pci 0000:00:01.0: BAR 1: assigned [mem 0x60410000-0x6041ffff]
[    3.404766] pci 0000:00:00.0: BAR 7: assigned [io  0x1e160000-0x1e160fff]
[    3.411553] pci 0000:00:01.0: BAR 7: assigned [io  0x1e161000-0x1e161fff]
[    3.418355] pci 0000:01:00.0: BAR 0: assigned [mem 0x60000000-0x600fffff 64bit]
[    3.425668] pci 0000:00:00.0: PCI bridge to [bus 01]
[    3.430634] pci 0000:00:00.0:   bridge window [io  0x1e160000-0x1e160fff]
[    3.437414] pci 0000:00:00.0:   bridge window [mem 0x60000000-0x600fffff]
[    3.444197] pci 0000:00:00.0:   bridge window [mem 0x60100000-0x601fffff pref]
[    3.451421] pci 0000:02:00.0: BAR 0: assigned [mem 0x60200000-0x602fffff]
[    3.458206] pci 0000:00:01.0: PCI bridge to [bus 02]
[    3.463171] pci 0000:00:01.0:   bridge window [io  0x1e161000-0x1e161fff]
[    3.469954] pci 0000:00:01.0:   bridge window [mem 0x60200000-0x602fffff]
[    3.476735] pci 0000:00:01.0:   bridge window [mem 0x60300000-0x603fffff pref]
[    3.484500] mt7530 mdio-bus:1f: Link is Up - 1Gbps/Full - flow control off
[    3.485675] UBI: auto-attach mtd9
[    3.494713] ubi0: attaching mtd9
[    4.711524] ubi0: scanning is finished
[    4.732696] ubi0: attached mtd9 (name "ubi", size 117 MiB)
[    4.738228] ubi0: PEB size: 131072 bytes (128 KiB), LEB size: 126976 bytes
[    4.745091] ubi0: min./max. I/O unit sizes: 2048/2048, sub-page size 2048
[    4.751869] ubi0: VID header offset: 2048 (aligned 2048), data offset: 4096
[    4.758819] ubi0: good PEBs: 940, bad PEBs: 0, corrupted PEBs: 0
[    4.764816] ubi0: user volume: 2, internal volumes: 1, max. volumes count: 128
[    4.772028] ubi0: max/mean erase counter: 5/2, WL threshold: 4096, image sequence number: 1594157890
[    4.781139] ubi0: available PEBs: 0, total reserved PEBs: 940, PEBs reserved for bad PEB handling: 20
[    4.790368] ubi0: background thread "ubi_bgt0d" started, PID 491
[    4.792786] block ubiblock0_0: created from ubi0:0(rootfs)
[    4.801899] ubiblock: device ubiblock0_0 (rootfs) set to be root filesystem
[    4.808858] hctosys: unable to open rtc device (rtc0)
[    4.821222] VFS: Mounted root (squashfs filesystem) readonly on device 254:0.
[    4.832650] Freeing unused kernel memory: 1284K
[    4.837204] This architecture does not have kernel memory protection.
[    4.843631] Run /sbin/init as init process
[    5.392859] init: Console is alive
[    5.396517] init: - watchdog -
[    6.003765] kmodloader: loading kernel modules from /etc/modules-boot.d/*
[    6.092581] kmodloader: done loading kernel modules from /etc/modules-boot.d/*
[    6.110000] init: - preinit -
[    6.765947] mtk_soc_eth 1e100000.ethernet eth0: configuring for fixed/rgmii link mode
[    6.774266] mtk_soc_eth 1e100000.ethernet eth0: Link is Up - 1Gbps/Full - flow control rx/tx
[    6.782770] IPv6: ADDRCONF(NETDEV_CHANGE): eth0: link becomes ready
[    6.927907] random: jshn: uninitialized urandom read (4 bytes read)
[    6.989594] random: jshn: uninitialized urandom read (4 bytes read)
[    7.032542] random: jshn: uninitialized urandom read (4 bytes read)
[    7.263118] mt7530 mdio-bus:1f lan1: configuring for phy/gmii link mode
[    7.270158] 8021q: adding VLAN 0 to HW filter on device lan1
[   11.362170] mt7530 mdio-bus:1f lan1: Link is Up - 1Gbps/Full - flow control off
[   11.369549] IPv6: ADDRCONF(NETDEV_CHANGE): lan1: link becomes ready
[   11.451383] UBIFS (ubi0:1): Mounting in unauthenticated mode
[   11.457300] UBIFS (ubi0:1): background thread "ubifs_bgt0_1" started, PID 609
[   11.539362] UBIFS (ubi0:1): recovery needed
[   11.725342] UBIFS (ubi0:1): recovery completed
[   11.729952] UBIFS (ubi0:1): UBIFS: mounted UBI device 0, volume 1, name "rootfs_data"
[   11.737766] UBIFS (ubi0:1): LEB size: 126976 bytes (124 KiB), min./max. I/O unit sizes: 2048 bytes/2048 bytes
[   11.747654] UBIFS (ubi0:1): FS size: 111611904 bytes (106 MiB, 879 LEBs), journal size 5586944 bytes (5 MiB, 44 LEBs)
[   11.758231] UBIFS (ubi0:1): reserved for root: 4952683 bytes (4836 KiB)
[   11.764831] UBIFS (ubi0:1): media format: w5/r0 (latest is w5/r0), UUID 6D39EE83-557A-446A-A695-6284B09DB315, small LPT model
[   11.790050] mount_root: switching to ubifs overlay
[   11.811366] overlayfs: upper fs does not support xattr, falling back to index=off and metacopy=off.
[   11.827083] urandom-seed: Seeding with /etc/urandom.seed
[   11.976124] mt7530 mdio-bus:1f lan1: Link is Down
[   11.993907] procd: - early -
[   11.996883] procd: - watchdog -
[   12.609797] procd: - watchdog -
[   12.613271] procd: - ubus -
[   12.675717] procd: - init -
[   13.727735] kmodloader: loading kernel modules from /etc/modules.d/*
[   13.751611] Loading modules backported from Linux version v5.8-0-gbcf876870b95
[   13.758927] Backport generated by backports.git v5.8-1-0-g79400d9e
[   13.781782] xt_time: kernel timezone is -0000
[   13.843625] mt7621-pci 1e140000.pcie: bus=2 slot=1 irq=24
[   13.849085] pci 0000:00:01.0: enabling device (0006 -> 0007)
[   13.854772] mt7603e 0000:02:00.0: enabling device (0000 -> 0002)
[   13.861051] mt7603e 0000:02:00.0: ASIC revision: 76030010
[   13.948323] urngd: v1.0.2 started.
[   14.086976] random: crng init done
[   14.090383] random: 7 urandom warning(s) missed due to ratelimiting
[   14.486943] mt7603e 0000:02:00.0: Firmware Version: ap_pcie
[   14.492540] mt7603e 0000:02:00.0: Build Time: 20160107100755
[   14.525644] mt7603e 0000:02:00.0: firmware init done
[   14.702769] ieee80211 phy0: Selected rate control algorithm 'minstrel_ht'
[   14.715327] mt7621-pci 1e140000.pcie: bus=1 slot=0 irq=23
[   14.720791] pci 0000:00:00.0: enabling device (0006 -> 0007)
[   14.726477] mt7615e 0000:01:00.0: enabling device (0000 -> 0002)
[   14.748858] ieee80211 phy1: Selected rate control algorithm 'minstrel_ht'
[   14.778630] PPP generic driver version 2.4.2
[   14.786290] NET: Registered protocol family 24
[   14.807547] kmodloader: done loading kernel modules from /etc/modules.d/*
[   14.873049] mt7615e 0000:01:00.0: HW/SW Version: 0x8a108a10, Build Time: 20180518100604a
[   14.873049]
[   15.175394] mt7615e 0000:01:00.0: N9 Firmware Version: _reserved_, Build Time: 20200814163649
[   15.226163] mt7615e 0000:01:00.0: CR4 Firmware Version: _reserved_, Build Time: 20190121161307
[   19.620970] mtk_soc_eth 1e100000.ethernet eth0: Link is Down
[   19.636372] mtk_soc_eth 1e100000.ethernet eth0: configuring for fixed/rgmii link mode
[   19.644629] mtk_soc_eth 1e100000.ethernet eth0: Link is Up - 1Gbps/Full - flow control rx/tx
[   19.648208] mt7530 mdio-bus:1f lan1: configuring for phy/gmii link mode
[   19.660438] 8021q: adding VLAN 0 to HW filter on device lan1
[   19.668995] IPv6: ADDRCONF(NETDEV_CHANGE): eth0: link becomes ready
[   19.676277] br-lan: port 1(lan1) entered blocking state
[   19.681717] br-lan: port 1(lan1) entered disabled state
[   19.687944] device lan1 entered promiscuous mode
[   19.692668] device eth0 entered promiscuous mode
[   19.711765] mt7530 mdio-bus:1f lan2: configuring for phy/gmii link mode
[   19.718954] 8021q: adding VLAN 0 to HW filter on device lan2
[   19.728275] br-lan: port 2(lan2) entered blocking state
[   19.733620] br-lan: port 2(lan2) entered disabled state
[   19.739997] device lan2 entered promiscuous mode
[   19.754051] mt7530 mdio-bus:1f lan3: configuring for phy/gmii link mode
[   19.761304] 8021q: adding VLAN 0 to HW filter on device lan3
[   19.770374] br-lan: port 3(lan3) entered blocking state
[   19.775745] br-lan: port 3(lan3) entered disabled state
[   19.782777] device lan3 entered promiscuous mode
[   19.802892] mt7530 mdio-bus:1f wan: configuring for phy/gmii link mode
[   19.810130] 8021q: adding VLAN 0 to HW filter on device wan
[   22.722161] mt7530 mdio-bus:1f lan1: Link is Up - 1Gbps/Full - flow control off
[   24.214549] br-lan: port 1(lan1) entered blocking state
[   24.219811] br-lan: port 1(lan1) entered forwarding state
[   24.226489] IPv6: ADDRCONF(NETDEV_CHANGE): br-lan: link becomes ready
[   24.233429] br-lan: port 4(wlan1) entered blocking state
[   24.238825] br-lan: port 4(wlan1) entered disabled state
[   24.244868] device wlan1 entered promiscuous mode
[   25.401452] br-lan: port 5(wlan0) entered blocking state
[   25.406988] br-lan: port 5(wlan0) entered disabled state
[   25.413181] device wlan0 entered promiscuous mode
[   32.933967] IPv6: ADDRCONF(NETDEV_CHANGE): wlan0: link becomes ready
[   32.940583] br-lan: port 5(wlan0) entered blocking state
[   32.945921] br-lan: port 5(wlan0) entered forwarding state
[   88.287189] IPv6: ADDRCONF(NETDEV_CHANGE): wlan1: link becomes ready
[   88.293927] br-lan: port 4(wlan1) entered blocking state
[   88.299304] br-lan: port 4(wlan1) entered forwarding state
[ 6637.501027] device wlan1 left promiscuous mode
[ 6637.505827] br-lan: port 4(wlan1) entered disabled state
[ 6638.239206] device wlan0 left promiscuous mode
[ 6638.243886] br-lan: port 5(wlan0) entered disabled state
[ 6643.317438] br-lan: port 4(wlan0) entered blocking state
[ 6643.322974] br-lan: port 4(wlan0) entered disabled state
[ 6643.328875] device wlan0 entered promiscuous mode
[ 6650.736871] IPv6: ADDRCONF(NETDEV_CHANGE): wlan0: link becomes ready
[ 6650.743501] br-lan: port 4(wlan0) entered blocking state
[ 6650.748846] br-lan: port 4(wlan0) entered forwarding state

**Comment by stevenxed** [comment]
Try the latest snapshot uploaded today. It has this fix included: https://github.com/openwrt/mt76/commit/73301065ac320b691e074b230a05ce24b26794f3

**Comment by morhimi** [comment]
10x, looks like the issue is indeed resolved for me:
![IMG_20200924_084434](https://user-images.githubusercontent.com/174977/94105657-74da9480-fe42-11ea-9f29-1dfc9c2b9d82.jpg)
