### ISSUE TITLE
MKT7688 AD-HOC Beacon timeout

### ISSUE THREAD

**Issue by jsj-reseiwe** [openwrt/mt76#46]
preconditions:
mt76 at git c3127d2acc354b4a27c8604716b0591093601971
/etc/config/wireless:
config wifi-iface
        option ifname 'wlan0-1'
        option device   radio0
        option network  lan
        option mode     adhoc
        option ssid     OpenWrt
        option bssid    'ac:22:0b:07:22:97'
        option encryption none

config wifi-device  radio0
        option type     mac80211
        option channel  11
        option hwmode   11g
        option path     'platform/10300000.wmac'
        option htmode   HT20
        # REMOVE THIS LINE TO ENABLE WIFI:
        # option disabled 1

Gets the following output:
[    9.494218] Loading modules backported from Linux version v4.4-rc5-1913-gc8fdf68
[    9.508940] Backport generated by backports.git backports-20151218-0-g2f58d9d
[    9.573606] mt76_wmac 10300000.wmac: ASIC revision: 76280001
[   11.628287] mt76_wmac 10300000.wmac: Firmware Version: _e2_mp
[   11.639733] mt76_wmac 10300000.wmac: Build Time: 20150211175503
[   11.666270] firmware init done
[   11.842048] ieee80211 phy0: Selected rate control algorithm 'minstrel_ht'
[   11.860581] ip_tables: (C) 2000-2006 Netfilter Core Team
[   11.892436] nf_conntrack version 0.5.0 (1967 buckets, 7868 max)
[   11.976023] xt_time: kernel timezone is -0000
[   11.997760] PPP generic driver version 2.4.2
[   12.009256] NET: Registered protocol family 24
[   18.880956] device eth0 entered promiscuous mode
[   18.906770] br-lan: port 1(eth0) entered forwarding state
[   18.917562] br-lan: port 1(eth0) entered forwarding state
[   20.916256] br-lan: port 1(eth0) entered forwarding state
[   21.217803] IPv6: ADDRCONF(NETDEV_UP): wlan0-1: link is not ready
[   21.247589] wlan0-1: Created IBSS using preconfigured BSSID ac:22:0b:07:22:97
[   21.261797] wlan0-1: Creating new IBSS network, BSSID ac:22:0b:07:22:97
[   21.308589] IPv6: ADDRCONF(NETDEV_CHANGE): wlan0-1: link becomes ready
[   48.051451] random: nonblocking pool is initialized
[   61.416283] ------------[ cut here ]------------
[   61.425520] WARNING: CPU: 0 PID: 7 at /home/jsj/dev/mt7688/openwrt/build_dir/target-mipsel_24kec+dsp_musl-1.1.14/linux-ramips_mt7688/mt76-master/mt7603_mac.c:1208 mt7603_mac_work+0x208/0x280 [mt7603e]()
[   61.461183] Modules linked in: pppoe ppp_async iptable_nat pppox ppp_generic nf_nat_ipv4 nf_conntrack_ipv6 nf_conntrack_ipv4 ipt_REJECT ipt_MASQUERADE xt_time xt_tcpudp xt_state xt_nat xt_multiport xt_mark xt_mac xt_limit xt_id xt_conntrack xt_comment xt_TCPMSS xt_REDIRECT xt_LOG xt_CT slhc nf_reject_ipv4 nf_nat_redirect nf_nat_masquerade_ipv4 nf_nat nf_log_ipv4 nf_defrag_ipv6 nf_defrag_ipv4 nf_conntrack_rtcache nf_conntrack iptable_raw iptable_mangle iptable_filter ip_tables crc_ccitt mt7603e mt76x2e mt76 mac80211 cfg80211 compat ip6t_REJECT nf_reject_ipv6 nf_log_ipv6 nf_log_common ip6table_raw ip6table_mangle ip6table_filter ip6_tables x_tables leds_gpio ohci_platform ohci_hcd ehci_platform ehci_hcd gpio_button_hotplug usbcore nls_base usb_common
[   61.593243] CPU: 0 PID: 7 Comm: kworker/u2:1 Not tainted 4.4.7 #3
[   61.605341] Workqueue: phy0 mt7603_mac_work [mt7603e]
[   61.615346] Stack : 87803410 87887e18 00000088 8004a070 8782a080 80390d43 8032df80 00000007
[   61.615346]    80356e5c 878a9d64 80390000 80048028 00000088 8004a070 80333458 80390000
[   61.615346]    00000003 878a9d64 80390000 80038338 00000088 878a9d9c 00000100 00000000
[   61.615346]    00000001 00000000 8713d020 87b7f800 87b7f700 30796870 00000000 00000000
[   61.615346]    00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000
[   61.615346]    ...
[   61.685998] Call Trace:
[   61.690861] [<8001451c>] show_stack+0x50/0x84
[   61.699498] [<80024e34>] warn_slowpath_common+0xa0/0xd0
[   61.709853] [<80024ee8>] warn_slowpath_null+0x18/0x24
[   61.719884] [<8713d228>] mt7603_mac_work+0x208/0x280 [mt7603e]
[   61.731483] [<8003628c>] process_one_work+0x1f8/0x334
[   61.741508] [<80037088>] worker_thread+0x2b4/0x408
[   61.751007] [<8003b3c0>] kthread+0xdc/0xe8
[   61.759144] [<80004478>] ret_from_kernel_thread+0x14/0x1c
[   61.769848]  
[   61.772859] ---[ end trace 5332c8b2834da861 ]---

Beacon interval set to 500, default just gets the error faster.

**Comment by nbd168** [comment]
Please test the latest version
