### ISSUE TITLE
how to enable hwnat on MT7620?

### ISSUE THREAD

**Issue by Sean2379607955** [openwrt/mt76#468]
MT7620 support hwnat based on switch chipset.
I not found hwnat module on openWRT.
Is there any plan to support hwnat?

Thanks
Sean

**Comment by dangowrt** [comment]
Your question is related to OpenWrt. This is the repository of the mt76 wifi driver (ie. unrelated to the MT7620 chip), hence you are asking in the wrong place.
Apart from that, I don't think there is any ongoing effort to make more recent Ethernet driver with offloading features work on MT7620 (though that could be done in theory).
