### ISSUE TITLE
How about bridge mode with wifi repeater?

### ISSUE THREAD

**Issue by Sean2379607955** [openwrt/mt76#469]
I find no option to join wifi client interface to sw bridge. 
It means wifi can uplink to a ap and lan can access uplink under bridge mode.
Can we setup openWRT like that?

Thanks
Sean

**Comment by Sean2379607955** [comment]
I Have see some solution. Will try it.

**Comment by dangowrt** [comment]
I recommend you to use forum.openwrt.org , not only your are spamming the wrong repository, chance for you to get useful answers are also much higher if you actually ask in the right place.
