### ISSUE TITLE
build error caused by missing bitfield.h

### ISSUE THREAD

**Issue by psyborg55** [openwrt/mt76#47]
just tried compiling trunk with last mt76 commit and get this error:

> In file included from /home/ubuntu/openwrt/build_dir/target-mipsel_24kec+dsp_musl-1.1.14/linux-ramips_mt7620/mt76-2016-03-04/mt76.h:25:0,
                 from /home/ubuntu/openwrt/build_dir/target-mipsel_24kec+dsp_musl-1.1.14/linux-ramips_mt7620/mt76-2016-03-04/mmio.c:17:
/home/ubuntu/openwrt/build_dir/target-mipsel_24kec+dsp_musl-1.1.14/linux-ramips_mt7620/mt76-2016-03-04/util.h:20:28: fatal error: linux/bitfield.h: No such file or directory
compilation terminated.

**Comment by nbd168** [comment]
LEDE r1513 has that header file (as part of the mac80211 package)

**Comment by psyborg55** [comment]
the solution referenced above worked
