### ISSUE TITLE
Does this driver work for MT7620A

### ISSUE THREAD

**Issue by changyuheng** [openwrt/mt76#49]
Hi there, does this driver work for MT7620A? Or should I use [mtk-wifi-gpl](https://github.com/openwrt/mtk-wifi-gpl) or rt2800?
I also have rt2860v2 driver, which we bought from the licensed module vendor. Somebody leaked it [here](https://github.com/wuqiong/rt2860v2-for-openwrt-mt7620). Do you know which one is the best Wi-Fi driver for MT7620A?

**Comment by nbd168** [comment]
MT7620 is not supported by mt76, but rt2x00 has some support for it
