### ISSUE TITLE
mt7615 160mhz tx speed problem

### ISSUE THREAD

**Issue by MeIsReallyBa** [openwrt/mt76#509]
iperf3 client speed result:
80mhz download 550Mb upload 630Mb.
160mhz download 400Mb upload 850Mb.

**Comment by MeIsReallyBa** [comment]
mt76: mt7615: add rx checksum offload support 

This commit increased a lot of rx performance(450Mb to 850Mb).It's even faster than proprietary driver.So is there any hope to increase the TX speed  to 850Mbps at 160MHZ?

**Comment by i3roly** [comment]
@meisreallyba so you think it's ready now? i wonder if it is. i've had nothing but issues with it for some time.

stop being a uighiur and at least respond to my "@"s! jerk!
