### ISSUE TITLE
mt7603 ssid cannot stop

### ISSUE THREAD

**Issue by ptpt52** [openwrt/mt76#516]
on chip mt7603
create ssid1 ssid2
reload
uci set wireless.radio0.disabled='1'
uci commit wireless
reload wifi

but ssid still exist and can be scan by phone

**Comment by nbd168** [comment]
If that happens on mt7603, I don't think this is an mt76 issue. mt7603 does not offload beaconing to the firmware, so if the phone still shows the network, then either the interface is still active, or the phone is showing stale results. Did you check the wlan* interfaces on the AP?

**Comment by ptpt52** [comment]
I check again, all interface down
iwinfo show nothing.

**Comment by ptpt52** [comment]
Sorry, I misunderstood, it's a signal from another AP
