### ISSUE TITLE
mt76x2 led control (is work)

### ISSUE THREAD

**Issue by p055877632** [openwrt/mt76#55]
mt76x2_mcu.h
..........................................
# define MT_MCU_LED_CTRL         0x0770

.........................................

so..........................

mt76x2_init.c   add

LED ON
mt76_wr(dev, MT_MCU_LED_CTRL, 0x800000);

LED OFF
mt76_wr(dev, MT_MCU_LED_CTRL, 0x820000);

LED TX BLINK
mt76_wr(dev, MT_MCU_LED_CTRL, 0x840000);

**Comment by nbd168** [comment]
mt76 now has proper mac80211 LED support for 7612 and 7603
