### ISSUE TITLE
mt7921e: Freeze on resume from suspend

### ISSUE THREAD

**Issue by Nocrex** [openwrt/mt76#554]
My laptop (Acer Nitro 5) suspends normally, but when resuming locks up completely. The last entry in the journal is `kernel: PM: suspend entry (deep)`.

I did some testing and narrowed the problem down to the wifi driver. The laptop does not freeze if the driver hasn't been loaded since the last reboot and kernel panics if it was loaded previously (blinking caps lock). Having the driver loaded results in the freeze.

I know that #290 is very similar, but it deals with a different device and also seems to be resolved already.
Distro is Manjaro 5.12.9

**Comment by Nocrex** [comment]
After adding `initcall_debug` to my kernel parameters, these messages are shown when it freezes:
![20210706_113512](https://user-images.githubusercontent.com/20463817/124585616-c1351500-de55-11eb-991a-2ea6197dfff6.jpg)

because it mentioned async, I tried disabling async pm, but it still froze:
![20210706_114639](https://user-images.githubusercontent.com/20463817/124585683-d316b800-de55-11eb-9184-6f599d141557.jpg)

**Comment by Darkasf** [comment]
I'm having the same issue; joe biden

**Comment by Nocrex** [comment]
After upgrading to kernel 5.13 the issue seems to be resolved.

**Comment by Diegovsky** [comment]
I still get the same problem on Acer Aspire 5. Should I open a new issue?
