### ISSUE TITLE
when i set wifi the system will reboot.

### ISSUE THREAD

**Issue by xamofb-xsk** [openwrt/mt76#558]
root@SmartWSN:/# wifi up
root@SmartWSN:/# [  537.016045] wlan0: deauthenticating from b0:89:00:0a:13:94 by local choice (Reason: 3=DEAUTH_LEAVING)
[  537.044778] CPU 0 Unable to handle kernel paging request at virtual address 00000000, epc == 8036bb88, ra == 86db0410
[  537.055586] Oops[#1]:
[  537.057896] CPU: 0 PID: 9 Comm: kworker/u2:1 Not tainted 4.14.95 #0
[  537.064274] Workqueue: phy0 mt76u_init [mt76_usb]
[  537.069046] task: 87c22c00 task.stack: 87ce4000
[  537.073632] $ 0   : 00000000 804a0000 00000000 00000000
[  537.078936] $ 4   : 86d92170 00000002 87c22c00 fffffff8
[  537.084240] $ 8   : fffffffd 0000a400 00000094 00000001
[  537.089544] $12   : 0001a390 00000000 77fe4000 002625a0
[  537.094849] $16   : 86d92170 86d91460 87ce5da8 86d92174
[  537.100154] $20   : 86f1f900 00000002 87cab218 00000088
[  537.105458] $24   : 80447020 faffddd6
[  537.110762] $28   : 87ce4000 87ce5d88 80460000 86db0410
[  537.116069] Hi    : 0039ecdb
[  537.118984] Lo    : c892f43b
[  537.121916] epc   : 8036bb88 __mutex_lock.isra.0+0x124/0x34c
[  537.127656] ra    : 86db0410 mt76u_single_wr+0x21c/0x72c [mt76_usb]
[  537.134004] Status: 1100a403 KERNEL EXL IE
[  537.138251] Cause : 0080040c (ExcCode 03)
[  537.142310] BadVA : 00000000
[  537.145228] PrId  : 00019655 (MIPS 24KEc)
[  537.149286] Modules linked in: rt2800pci rt2800mmio rt2800lib pppoe ppp_async option l2tp_ppp uvcvideo usb_wwan rt2x00pci rt2x00mmio rt2x00lib pptp pppox ppp_mppe ppp_generic nf_nat_pptp nf_conntrack_pptp nf_conntrack_ipv6 mt76x2u mt76x2_common mt76x02_usb mt76x02_lib mt76_usb mt76 mac80211 iptable_nat ipt_REJECT ipt_MASQUERADE ch341 cfg80211 xt_time xt_tcpudp xt_tcpmss xt_statistic xt_state xt_recent xt_policy xt_nat xt_multiport xt_mark xt_mac xt_limit xt_length xt_hl xt_helper xt_esp xt_ecn xt_dscp xt_conntrack xt_connmark xt_connlimit xt_connbytes xt_comment xt_TCPMSS xt_REDIRECT xt_LOG xt_HL xt_FLOWOFFLOAD xt_DSCP xt_CT xt_CLASSIFY videobuf2_v4l2 usbserial usbhid ums_usbat ums_sddr55 ums_sddr09 ums_karma ums_jumpshot ums_isd200 ums_freecom ums_datafab ums_cypress ums_alauda ts_fsm ts_bm slhc
[  537.221012]  rtc_pcf8563 qmi_wwan nf_reject_ipv4 nf_nat_tftp nf_nat_snmp_basic nf_nat_sip nf_nat_redirect nf_nat_proto_gre nf_nat_masquerade_ipv4 nf_nat_irc nf_conntrack_ipv4 nf_nat_ipv4 nf_nat_h323 nf_nat_amanda nf_nat nf_log_ipv4 nf_flow_table_hw nf_flow_table nf_defrag_ipv6 nf_defrag_ipv4 nf_conntrack_tftp nf_conntrack_snmp nf_conntrack_sip nf_conntrack_rtcache nf_conntrack_proto_gre nf_conntrack_irc nf_conntrack_h323 nf_conntrack_broadcast ts_kmp nf_conntrack_amanda iptable_raw iptable_mangle iptable_filter ipt_ah ipt_ECN ip_tables hid_generic crc_itu_t crc_ccitt compat cdc_wdm cdc_ether fuse act_connmark nf_conntrack act_skbedit act_mirred em_u32 cls_u32 cls_tcindex cls_flow cls_route cls_fw sch_tbf sch_htb sch_hfsc sch_ingress videobuf2_vmalloc videobuf2_memops videobuf2_core hid v4l2_common
[  537.292784]  videodev evdev input_core i2c_mt7621 i2c_dev i2c_core ledtrig_oneshot ledtrig_heartbeat ledtrig_gpio gobiNet usbnet xt_set ip_set_list_set ip_set_hash_netiface ip_set_hash_netport ip_set_hash_netnet ip_set_hash_net ip_set_hash_netportnet ip_set_hash_mac ip_set_hash_ipportnet ip_set_hash_ipportip ip_set_hash_ipport ip_set_hash_ipmark ip_set_hash_ip ip_set_bitmap_port ip_set_bitmap_ipmac ip_set_bitmap_ip ip_set nfnetlink ip6t_REJECT nf_reject_ipv6 nf_log_ipv6 nf_log_common ip6table_mangle ip6table_filter ip6_tables x_tables ip_gre gre ifb l2tp_netlink l2tp_core udp_tunnel ip6_udp_tunnel ipcomp6 xfrm6_tunnel xfrm6_mode_tunnel xfrm6_mode_transport xfrm6_mode_beet esp6 ah6 ipcomp xfrm4_tunnel xfrm4_mode_tunnel xfrm4_mode_transport xfrm4_mode_beet esp4 ah4 tunnel6 tunnel4 ip_tunnel tun af_key
[  537.364735]  xfrm_user xfrm_ipcomp xfrm_algo vfat fat autofs4 nls_utf8 nls_iso8859_1 nls_cp936 nls_cp437 eeprom_93cx6 dma_shared_buffer sha256_generic sha1_generic jitterentropy_rng drbg md5 hmac echainiv ecb des_generic deflate zlib_inflate zlib_deflate cbc authenc crypto_acompress mmc_block usb_storage sdhci_pltfm sdhci mtk_sd mmc_core leds_gpio ledtrig_transient ehci_platform sd_mod scsi_mod ehci_hcd gpio_button_hotplug ext4 jbd2 mbcache exfat usbcore nls_base usb_common crc16 mii aead crypto_null cryptomgr crc32c_generic crypto_hash
[  537.413070] Process kworker/u2:1 (pid: 9, threadinfo=87ce4000, task=87c22c00, tls=00000000)
[  537.421530] Stack : 0000012c 86d91460 80000280 00001704 0000000a 00000007 000000c0 86db00bc
[  537.430016]         86d92174 00000000 87cab218 00000088 86d92170 86d91460 00001798 00000000
[  537.438499]         86f1f900 00000002 87cab218 00000088 80460000 86db0410 00001704 00000000
[  537.446983]         86f1f900 00000002 87ce5e30 87ce5e5f 86d91460 86e025a4 0000004e 1e4200f8
[  537.455467]         00000000 86afcb30 86d91460 87ce5e5f 86d91460 86e05334 87c22e84 87c05014
[  537.463952]         ...
[  537.466433] Call Trace:
[  537.468919] [<8036bb88>] __mutex_lock.isra.0+0x124/0x34c
[  537.474318] [<86db0410>] mt76u_single_wr+0x21c/0x72c [mt76_usb]
[  537.480411] Code: ac920008  afb30020  afa20024 <ac520000> 8f820000  afa20028  8c820004  14520006  00000000
[  537.490315]
[  537.491916] ---[ end trace b50512de2cfdbeb0 ]---
[  537.499749] Kernel panic - not syncing: Fatal exception
[  537.506479] Rebooting in 3 seconds..

**Comment by nbd168** [comment]
Should be fixed in the latest version
