### ISSUE TITLE
WiTiBoard 2GHz wifi too slow

### ISSUE THREAD

**Issue by elkablo** [openwrt/mt76#58]
Current LEDE master compiled for WiTiBoard gives slow 2GHz wifi (MT7602E)
I have configured N mode through Luci on 20MHz (channel 11), but download speed is 2.5 MB/s at most.

**Comment by nbd168** [comment]
What does "Current" mean? Please post a revision number of commit hash

**Comment by elkablo** [comment]
LEDE commit 578f7b9c597b0ea9bcf0726cc681713c0672edfe
LEDE .config: http://blackhole.sk/~kabel/tmp/witi-lede-config

**Comment by nbd168** [comment]
What kind of client are you using? Did you try different channels (maybe the one you're using is busy)? Please post the rate control stats from /sys/kernel/debug/ieee80211/phy*/netdev:wlan*/stations/*/rc_stats

**Comment by elkablo** [comment]
You can find the rc_stats files on http://blackhole.sk/~kabel/tmp/witislow2/
names are in the form rc_stats.n_C_F_A.txt where C is channel number (I tried for 9 and 5 in this test, the default, 11, was also slow), F is frequency (20mhz or 40mhz as set in luci) and A is the average download speed (downloading a file from the router's SSD via wget).
I am testing this on my Thinkpad X230 with iwl7260 ac card.

**Comment by elkablo** [comment]
Can you reproduce this error? Or should I do more tests?

**Comment by nbd168** [comment]
Is the second antenna port for the 2 GHz wifi soldered and connected properly on your device? It seems that single-stream rates work well and dual-stream rates don't.
As far as I know, WiTi boards used to ship with only 2 of 4 antenna connectors soldered onto the board.

**Comment by elkablo** [comment]
Yes, I have soldered the second connector and bought antenna for it. Should I remove the antenna, or do I need to unsolder the connector as well?

**Comment by nbd168** [comment]
You should not remove the antenna, but I'm thinking that maybe the connector is not soldered properly

**Comment by neheb** [comment]
2.4ghz on the witi does not work right for me. Adding a second antenna causes 2.4ghz to completely die. Strictly speaking that has nothing to do with mt76. Just thought I'd mention it.

**Comment by nbd168** [comment]
Seems like a hardware issue to me so I'll close this report.
