### ISSUE TITLE
"Add LED Action" button hangs forever after disabling "Enable VLAN functionality" in Switch section

### ISSUE THREAD

**Issue by KerryGee** [openwrt/mt76#616]
The LED Configuration Button keeps on spinning forever after pressing "Add LED Action" with no dialog shown. This seems to be directly related to the deactivation of the "Enable VLAN functionality" inside the Switch section. Re-Enabling the "Enable VLAN functionality" makes the "Add LED Action" button work again by showing the configuration dialog for the device LEDs.

Affected system is:

WAVLINK WL-WN577A2 (branded "MAGINON WLR-755 AC" device)
MediaTek MT7628AN ver:1 eco:2
OpenWrt 21.02.1 r16325-88151b8303 / LuCI openwrt-21.02 branch git-21.295.67054-13df80d
Kernel Version	5.4.154

**Comment by Mushoz** [comment]
This is the mt76 driver github, which is a WiFi driver. The problem you are experiencing sounds like an OpenWRT issue, so you might want to open a bug ticket on their bug tracker.
