### ISSUE TITLE
mt76x2, mt76x3, mt7615: tx power with mt76 driver is lower than with mediatek driver

### ISSUE THREAD

**Issue by csharper2005** [openwrt/mt76#657]
Hi everybody,

I have had many mt7621 router with different combinations of wireless chips:
- mt7603 + mt7615n
- mt7602 + mt7612
- mt7603 + mt7612
- mt7603 + mt7613
- mt7615dn (dbdc)

**Problem:**
- In all cases tx power with mt76 driver (OpenWrt) is 4-10 dBm lower than with mediatek driver (OEM firmwares, Padavan, AsusWrt). I roughly check that using [WiFi Analyzer ](https://play.google.com/store/apps/details?id=com.farproc.wifi.analyzer&hl=pl&gl=US)app on my phone

**Example**
2 routers mt7603 + mt7615. 
OpenWrt config - 20 dBm TX power
Stock config - according to documentation router has 100 mWt tx power (also 20 dBm).
Routers are in the same place. OpenWrt real TX power is lower:
![image](https://user-images.githubusercontent.com/82600916/160300272-5118fa1e-28ce-4961-a49c-dff0338215df.png)

**Possible root causes**
- TX power in mt76 is ok. The vendors (Xiaomi, Sercomm, Arcadyan etc) violates the maximum allowable power. 
- TX power with mt76 is not enough for different reasons (i.e. stock use file eeprom, not on Flash). We correctly use various hacks (changes country to Venezuela, change eeprom data, make own patches) to get the full power.

Do you have similar user experience? I found many similar tickets here and would like to take a closer look at this issue. Maybe someone has more accurate devices for estimating power than a phone. 

@nbd168 maybe it's possible to define +delta dBm via dts or some configs? It would be safer than another hacks.
@ptpt52 what do you think?

**Comment by JFtico** [comment]
I have the same experience with a MT7621 SoC with a 7612 + 7603e Wifi chips (ZBT WE3526).

OEM firmware (OpenWRT derived) with the MediaTek drivers is 4 to 10dB stronger.

I also note the OEM 7603 related code loads the 'eeprom' from a file, not the actual flash. So maybe an override is needed in DTS?

This issue is also related to what is discussed in https://github.com/openwrt/mt76/issues/633

**Comment by csharper2005** [comment]
> Or, use a unii-1 channel (like 44) on both routers, that way you can set the openwrt output to 23 legally. Unii-1 is 23dbi global and China.

Hmm... Channel 44 + driver default power in OpenWrt gives approximately the same EIRP as stock firmware.

**Comment by dekomote** [comment]
> > Or, use a unii-1 channel (like 44) on both routers, that way you can set the openwrt output to 23 legally. Unii-1 is 23dbi global and China.
> 
> Hmm... Channel 44 + driver default power in OpenWrt gives approximately the same EIRP as stock firmware.

Just as I suspected. If you now set the country to China, set a Unii 2 channel and set the output to 26dbi, i think you'll see the same.

**Comment by levshutov** [comment]
Done some measurements.

Two Xiaomi AX3200 routers.
1. OpenWrt SNAPSHOT r19309 with included mt76 driver.
2. OpenWrt SNAPSHOT r19309 with MTK driver (https://forum.openwrt.org/t/adding-openwrt-support-for-xiaomi-redmi-router-ax6s-xiaomi-router-ax3200/111085/336).

MTK wifi settings are default (maximum power).
mt76 power varys.

Signal measured through 3 brick walls. 
Channel width - 80 MHz.
Scan interval - 5 seconds.

<details>
  <summary>Channel 36, mt76 power 20 dBm</summary>
  <img src="https://user-images.githubusercontent.com/71168646/161429044-f1e99a5e-69e8-41bf-b7a4-709ef8b86dfa.png" width="300">
</details>
<details>
  <summary>Channel 36, mt76 power 23 dBm</summary>
  <img src="https://user-images.githubusercontent.com/71168646/161429045-5b534aa3-6942-4e2e-8cf0-a3fdb1e1034e.png" width="300">
</details>
<details>
  <summary>Channel 36, mt76 power 27 dBm</summary>
  <img src="https://user-images.githubusercontent.com/71168646/161429046-8fc2f5cd-fd07-4a7b-adc8-ce092f015b2f.png" width="300">
</details>
<details>
  <summary>Channel 52, mt76 power 20 dBm</summary>
  <img src="https://user-images.githubusercontent.com/71168646/161429047-53209b56-d7c6-4779-8999-3b8f35c13293.png" width="300">
</details>
<details>
  <summary>Channel 52, mt76 power 23 dBm</summary>
  <img src="https://user-images.githubusercontent.com/71168646/161429048-04d9b633-e858-4225-a1a4-524a6722aae4.png" width="300">
</details>
<details>
  <summary>Channel 52, mt76 power 27 dBm</summary>
  <img src="https://user-images.githubusercontent.com/71168646/161429050-ae35a83f-190c-4fc7-8af8-ca029a00cc82.png" width="300">
</details>
<details>
  <summary>Channel 149, mt76 power 20 dBm</summary>
  <img src="https://user-images.githubusercontent.com/71168646/161429052-2e35d04f-2ae2-4ae4-a2dd-7fa744859ff2.png" width="300">
</details>
<details>
  <summary>Channel 149, mt76 power 23 dBm</summary>
  <img src="https://user-images.githubusercontent.com/71168646/161429055-f8043417-4b04-480e-859e-b7f13e07cc4c.png" width="300">
</details>
<details>
  <summary>Channel 149, mt76 power 27 dBm</summary>
  <img src="https://user-images.githubusercontent.com/71168646/161429056-8f3632b1-543f-4b24-8ca0-9ae3a2a92dc4.png" width="300">
</details>

**Comment by mog422** [comment]
I am also experiencing this problem in mt7915. so I am using a workaround by modifying wireless-regdb.

**Comment by MeIsReallyBa** [comment]
> Done some measurements.
> 
> Two Xiaomi AX3200 routers.
> 
> 1. OpenWrt SNAPSHOT r19309 with included mt76 driver.
> 2. OpenWrt SNAPSHOT r19309 with MTK driver (https://forum.openwrt.org/t/adding-openwrt-support-for-xiaomi-redmi-router-ax6s-xiaomi-router-ax3200/111085/336).
> 
> MTK wifi settings are default (maximum power). mt76 power varys.
> 
> Signal measured through 3 brick walls. Channel width - 80 MHz. Scan interval - 5 seconds.
> 
> Channel 36, mt76 power 20 dBm
> Channel 36, mt76 power 23 dBm
> Channel 36, mt76 power 27 dBm
> Channel 52, mt76 power 20 dBm
> Channel 52, mt76 power 23 dBm
> Channel 52, mt76 power 27 dBm
> Channel 149, mt76 power 20 dBm
> Channel 149, mt76 power 23 dBm
> Channel 149, mt76 power 27 dBm

can you try to turn off sky like this and make another test?

https://github.com/MeIsReallyBa/mt76/commit/e73be47c93b800e1c0a24ce5a044526754d31a4c

**Comment by levshutov** [comment]
> can you try to turn off sku like this and make another test?
> 
> [MeIsReallyBa@e73be47](https://github.com/MeIsReallyBa/mt76/commit/e73be47c93b800e1c0a24ce5a044526754d31a4c)

No difference compared with previous results

**Comment by phil2sat** [comment]
So then youre not capped by the regdb, its either the chipset does max 27dbm or some antenna gain like 3dbi
you could ty:
"iw phy "$phy" set antenna_gain 0" 
to get to 30dbi 
or 
it could be that some calibration data or even coext settings are different for your device, im no dev but i dived a little bit trough the eeprom.c and what i saw was that the coext settings wasnt implemented fully (as far as my knowledge can say)

in this case there only the devs can help

**Comment by sinancetinkaya** [comment]
I have MT7602E and MT76 open source driver is giving me headaches. Low power output is one of them but I can live with it,
The main problem is that after some time (in 1 or 2 days), wireless becomes unstable, stuttering, slow.
Restarting wireless card solves the problem temporarily.
I can't see anything in the logs.

**Comment by d-me3** [comment]
> > Done some measurements.
> > Two Xiaomi AX3200 routers.
> > 
> > 1. OpenWrt SNAPSHOT r19309 with included mt76 driver.
> > 2. OpenWrt SNAPSHOT r19309 with MTK driver (https://forum.openwrt.org/t/adding-openwrt-support-for-xiaomi-redmi-router-ax6s-xiaomi-router-ax3200/111085/336).
> > 
> > MTK wifi settings are default (maximum power). mt76 power varys.
> > Signal measured through 3 brick walls. Channel width - 80 MHz. Scan interval - 5 seconds.
> > Channel 36, mt76 power 20 dBm
> > Channel 36, mt76 power 23 dBm
> > Channel 36, mt76 power 27 dBm
> > Channel 52, mt76 power 20 dBm
> > Channel 52, mt76 power 23 dBm
> > Channel 52, mt76 power 27 dBm
> > Channel 149, mt76 power 20 dBm
> > Channel 149, mt76 power 23 dBm
> > Channel 149, mt76 power 27 dBm
> 
> can you try to turn off sku like this and make another test?
> 
> [MeIsReallyBa@e73be47](https://github.com/MeIsReallyBa/mt76/commit/e73be47c93b800e1c0a24ce5a044526754d31a4c)

Interesting results, thanks for sharing.

One question: did you use 802.11**ax** or 802.11**ac** in your tests?

I'm asking this because I also have two AX6S and one AX3200 (same device), and while testing 802.11**ax** performance through a brick wall I've noticed that the 802.11**ax** performance is **worse** than 802.11**ac** (it happens with multiple ax devices, but with an iPhone 13 the problem is even worse). See more details of my test [in the forum here](https://forum.openwrt.org/t/802-11ax-worse-than-802-11ac-with-mt76-driver/126466/14?u=dsouza)).

My hypothesis is that mt76 drivers may not be enabling beamforming in 802.11**ax** that could explain the instability of the signal strength in your tests *if* you used 802.11ax. If so, you may want to repeat your tests with 802.11ac to compare the results.

**Comment by rodsmar** [comment]
Looking at MediaTek's GPL code, the EEPROM size on the MT7663 is 1536 (0x600). I made the change in the MT76 driver and noticed an average 5dbm increase in signal strength.

My config:

config wifi-device 'radio1'
        option type 'mac80211'
        option path '1e140000.pcie/pci0000:00/0000:00:01.0/0000:02:00.0'
        option channel '149'
        option band '5g'
        option htmode 'VHT80'
        option disabled '0'
        option country 'BR'
        option noscan '1'


I've tested on my TP-Link Archer C6 v3. Not sure if work on other devices.

[patch.txt](https://github.com/openwrt/mt76/files/9912770/patch.txt)

**Comment by jamesmcguirepro** [comment]
> My hypothesis is that mt76 drivers may not be enabling beamforming in 802.11**ax** that could explain the instability of the signal strength in your tests _if_ you used 802.11ax. If so, you may want to repeat your tests with 802.11ac to compare the results.

I have a MT7621-equipped router (DIR-2640) that does not support 802.11ax. It does not appear beamforming is enabled:
```
# grep vht_capab /var/run/hostapd*.conf
/var/run/hostapd-phy1.conf:vht_capab=[RXLDPC][SHORT-GI-80][SHORT-GI-160][TX-STBC-2BY1][RX-ANTENNA-PATTERN][TX-ANTENNA-PATTERN][RX-STBC-1][VHT160-80PLUS80][MAX-A-MPDU-LEN-EXP7]
```

Capturing beacon frames confirm it's not advertising support for beamforming.

**Comment by Anteus** [comment]
> > My hypothesis is that mt76 drivers may not be enabling beamforming in 802.11**ax** that could explain the instability of the signal strength in your tests _if_ you used 802.11ax. If so, you may want to repeat your tests with 802.11ac to compare the results.
> 
> 
> 
> I have a MT7621-equipped router (DIR-2640) that does not support 802.11ax. It does not appear beamforming is enabled:
> 
> ```
> 
> # grep vht_capab /var/run/hostapd*.conf
> 
> /var/run/hostapd-phy1.conf:vht_capab=[RXLDPC][SHORT-GI-80][SHORT-GI-160][TX-STBC-2BY1][RX-ANTENNA-PATTERN][TX-ANTENNA-PATTERN][RX-STBC-1][VHT160-80PLUS80][MAX-A-MPDU-LEN-EXP7]
> 
> ```
> 
> 
> 
> Capturing beacon frames confirm it's not advertising support for beamforming.

Seems to be enabled on MT7622, a RT3200

var/run/hostapd-wl1.conf:vht_capab=[RXLDPC][SHORT-GI-80][SHORT-GI-160][TX-STBC-2BY1][SU-BEAMFORMER][SU-BEAMFORMEE][MU-BEAMFORMER][MU-BEAMFORMEE][RX-ANTENNA-PATTERN][TX-ANTENNA-PATTERN][RX-STBC-1][SOUNDING-DIMENSION-4][BF-ANTENNA-4][VHT160-80PLUS80][MAX-MPDU-7991][MAX-A-MPDU-LEN-EXP7]

**Comment by EugeneKey** [comment]
> Looking at MediaTek's GPL code, the EEPROM size on the MT7663 is 1536 (0x600). I made the change in the MT76 driver and noticed an average 5dbm increase in signal strength.
> 
> My config:
> 
> ` config` wifi-device 'radio1' option type 'mac80211' option path '1e140000.pcie/pci0000:00/0000:00:01.0/0000:02:00.0' option channel '149' option band '5g' option htmode 'VHT80' option disabled '0' option country 'BR' option noscan '1' `
> 
> I've tested on my TP-Link Archer C6 v3. Not sure if work on other devices.
> 
> [patch.txt](https://github.com/openwrt/mt76/files/9912770/patch.txt)

Sounds great, maybe you could create pull request with this diff?

**Comment by ptpt52** [comment]
> Looking at MediaTek's GPL code, the EEPROM size on the MT7663 is 1536 (0x600). I made the change in the MT76 driver and noticed an average 5dbm increase in signal strength.
> 
> My config:
> 
> ` config` wifi-device 'radio1' option type 'mac80211' option path '1e140000.pcie/pci0000:00/0000:00:01.0/0000:02:00.0' option channel '149' option band '5g' option htmode 'VHT80' option disabled '0' option country 'BR' option noscan '1' `
> 
> I've tested on my TP-Link Archer C6 v3. Not sure if work on other devices.
> 
> [patch.txt](https://github.com/openwrt/mt76/files/9912770/patch.txt)

ping @nbd168 
what do you think about this

**Comment by rodsmar** [comment]
> 

Yes. But I need testers to see if there are improvements in all equipment that uses the MT7663/MT7613 chip.

**Comment by rodsmar** [comment]
> > Looking at MediaTek's GPL code, the EEPROM size on the MT7663 is 1536 (0x600). I made the change in the MT76 driver and noticed an average 5dbm increase in signal strength.
> > My config:
> > ` config` wifi-device 'radio1' option type 'mac80211' option path '1e140000.pcie/pci0000:00/0000:00:01.0/0000:02:00.0' option channel '149' option band '5g' option htmode 'VHT80' option disabled '0' option country 'BR' option noscan '1' `
> > I've tested on my TP-Link Archer C6 v3. Not sure if work on other devices.
> > [patch.txt](https://github.com/openwrt/mt76/files/9912770/patch.txt)
> 
> Sounds great, maybe you could create pull request with this diff?


Yes. But I need testers to see if there are improvements in all equipment that uses the MT7663/MT7613 chip.

**Comment by EugeneKey** [comment]
> Yes. But I need testers to see if there are improvements in all equipment that uses the MT7663/MT7613 chip.

I use Xiaomi AX3200 (MT7622/MT7615) Could there be similar changes for this chip? How to find out the EEPROM size for MT7622?

**Comment by thelinuxdude** [comment]
Is the EEPROM_SIZE for the mt7615 1024 or 1536 (same as mt7663)?

**Comment by nbd168** [comment]
If you have a MT7613/MT7663 based device, please test latest OpenWrt master. I've increased the EEPROM size without affecting MT7615

**Comment by csharper2005** [comment]
@nbd168 [MT7615 eeprom](https://mega.nz/file/d4IyADAb#63evCKQMoVzQA4vIDxnKJ7jr5x9kCzsGBSgyzgt1Fjk) can be even bigger (0x2600 bytes). [This](https://openwrt.org/inbox/toh/beeline/smartbox_turbo_plus?s[]=turbo&s[]=plus) device.

**Comment by rodsmar** [comment]
> @nbd168 [MT7615 eeprom](https://mega.nz/file/d4IyADAb#63evCKQMoVzQA4vIDxnKJ7jr5x9kCzsGBSgyzgt1Fjk) can be even bigger (0x2600 bytes). [This](https://openwrt.org/inbox/toh/beeline/smartbox_turbo_plus?s%5B%5D=turbo&s%5B%5D=plus) device. Upd. And [this](https://openwrt.org/toh/beeline/smartbox_turbo) too.

Hey, you may look at GPL code for your device. It's out of my knowledge, but MT7615 EEPROM has iPAiLNA, iPAeLNA, ePAiLNA and ePAeLNA.

Maybe the stock rom assembled all EEPROM binaries in a single file.

**Comment by rodsmar** [comment]
> If you have a MT7613/MT7663 based device, please test latest OpenWrt master. I've increased the EEPROM size without affecting MT7615

Apparently everything is fine!

**Comment by sinancetinkaya** [comment]
Can #575 be related to this?

**Comment by csharper2005** [comment]
I noticed that mt7663 tx power is really good. Very nice and very closer to stock. Thanks, @nbd168!

Also noticed that speed approximately the same with 40 and 80 MHz width.
40 MHz:
![image](https://user-images.githubusercontent.com/82600916/208309921-9159cea0-c102-49a7-b04c-4163ee4388ac.png)

80 Mhz: 
![image](https://user-images.githubusercontent.com/82600916/208310076-29a1160a-7ba3-4b97-a2ae-880aa13d786c.png)

So 40 MHz might be even better. Can anyone else confirm this observations for 7612, 7615?

**Comment by csharper2005** [comment]
7603, 20 MHz:
![image](https://user-images.githubusercontent.com/82600916/208310378-acae5927-db3e-4b60-9bd3-ff477e37bab7.png)

7603, 40 MHz
![image](https://user-images.githubusercontent.com/82600916/208310458-6aef5a66-db2a-4e4f-adc8-b6748e103c6b.png)

**Comment by sinancetinkaya** [comment]
> I noticed that mt7663 tx power is really good with the current SNAPSHOT. Very nice and very closer to stock. Thanks, @nbd168!
> 
> Also noticed that speed approximately the same with 40 and 80 MHz width. 40 MHz: ![image](https://user-images.githubusercontent.com/82600916/208309921-9159cea0-c102-49a7-b04c-4163ee4388ac.png)
> 
> 80 Mhz: ![image](https://user-images.githubusercontent.com/82600916/208310076-29a1160a-7ba3-4b97-a2ae-880aa13d786c.png)
> 
> So 40 MHz might be even better. Can anyone else confirm this observations for 7612, 7615?

I have mt7612e (movie card) does it count? Should I test it?

**Comment by csharper2005** [comment]
> I have mt7612e (mpcie card) does it count? Should I test it?

I guess so.  Let's test them all.

**Comment by sinancetinkaya** [comment]
@csharper2005  Sorry, I accidentally removed my post. Is it the latest snapshot?

**Comment by csharper2005** [comment]
@sinancetinkaya, I've made a table:
Model | SNAPSHOT | Driver (mt76) | 7602 | 7603 | 7612 | 7613 | 7615 | 7615dbdc | 2g, 20 MHz | 2g, 40 MHz | 5g, 40 MHz | 5g, 80 MHz | Test conditions
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
Beeline   SmartBox GIGA | r21523-4609228432 | 2022-12-09 |   | x |   | x |   |   | 88 / 53 | 60 / 87 | 144 / 140 | 110 / 168 | Walls, Intel(R)   Wireless-AC 9560
Etisalat S3 | r21549-963c77158c | 2022-12-09 |   | x |   |   | x |   | 63 / 7 | 49 / 8 | 182 / 228 | 303 / 326 | Walls, Intel(R)   Wireless-AC 9560

**Comment by sinancetinkaya** [comment]
I have [UniElec u7621-06 16M](https://openwrt.org/toh/hwdata/unielec/unielec_u7621-06_256m_16m) with mini-PCIe cards: [MT7602E](https://tr.aliexpress.com/item/32457332512.html), [MT7612E](https://www.aliexpress.com/item/32816737559.html) 10 dbi antennas attached
These cards suppose to have excellent signal strength but my old cheap ISP provided modem's internal wifi has better signal

**Comment by csharper2005** [comment]
Guys, I tested 7602, 7603, 7612, 7615 myself and didn't find any problems with TX power with current SNAPSHOT. So I decided to close to issue. 

The finding with strange speed on 7613 and 40MHz / 80 MHz channel width should be investigated separately.
