### ISSUE TITLE
Why is there no mt7622 driver

### ISSUE THREAD

**Issue by tangyf20142016** [openwrt/mt76#674]
I used the bpi-r64 cpe, but the wireless didn't work. I found that there was no mt7622 driver.How to add mt7622 driver?

**Comment by lukasz1992** [comment]
mt7615 driver should handle mt7622 (CONFIG_MT7622_WMAC option needs to be enabled).
Check your kernel config, update kernel or compile driver manually.

**Comment by tangyf20142016** [comment]
CONFIG_MT7622_WMAC has been enabled, but mt7622 wifi still does not work

**Comment by nbd168** [comment]
If you have issues, please check how the driver is used in OpenWrt - it works there
