### ISSUE TITLE
Mt7915 5ghz 802.11s mesh is not working

### ISSUE THREAD

**Issue by mezzovide** [openwrt/mt76#675]
My device is totolink X5000R and im using OpenWrt SNAPSHOT r19700-90e4c8c6e6, any chance to get it to work? Tried 5ghz first but it wont make a connection between devices,  decided to try 2.4ghz, and its been working for a while

**Comment by mezzovide** [comment]
apparently the issue is same mac addresses on each devices, as described here #630
as a workaround i try changing mac address on each devices ssid and it works now.

**Comment by rsps1008** [comment]
@mezzovide Hi, can you tell me how do you change mac address on the device of router?

**Comment by mezzovide** [comment]
fixed per this commit
https://github.com/openwrt/openwrt/commit/212632540043cc9b911c2efb86156479f2710836
