### ISSUE TITLE
Netgear R6100: 5G no signal but everything else seems well...

### ISSUE THREAD

**Issue by recolic** [openwrt/mt76#69]
I've try to:
- Change firmware-4.bin to firmware-2.bin and firmware-2-ct-....bin;
- Change every possible channel;
- Change country code;(I'm in China)
- Restart Radio1(5GHz) and reboot, re-plug the power;
However, the 5G signal is constantly 0%...(Everything else is correct, 2.4GHz is OK.)

# LuCI interface info:
(disabled) ---------------------
Qualcomm Atheros QCA9880 802.11nac (radio1)
 Scan  Add
Signal: 0 dBm / Noise: 0 dBm
0%	SSID: RecolicPrivateWlan_5G | Mode: Master
Wireless is disabled or not associated
(enabled) -------------------------
Qualcomm Atheros QCA9880 802.11nac (radio1)
 Scan  Add
Signal: 0 dBm / Noise: 0 dBm
0%	SSID: RecolicPrivateWlan_5G | Mode: Master
Wireless is disabled or not associated
(enabled, sometimes looks like this) ------------------
Qualcomm Atheros QCA9880 802.11nac (radio1)
 Scan  Add
Signal: 0 dBm / Noise: 0 dBm
0%	SSID: RecolicPrivateWlan_5G | Mode: Master
BSSID: 04:A1:51:88:2E:** | Encryption: mixed WPA/WPA2 PSK (CCMP)

# Openwrt starting log: (after 'opkg install kmod-ath10k' and reboot)
root@OpenWrt:~# dmesg | grep 'ath10k'
[   14.380000] ath10k_pci 0000:00:00.0: pci irq legacy interrupts 0 irq_mode 0 reset_mode 0
[   14.600000] ath10k_pci 0000:00:00.0: Direct firmware load for ath10k/cal-pci-0000:00:00.0.bin failed with error -2
[   14.610000] ath10k_pci 0000:00:00.0: Falling back to user helper
[   14.710000] firmware ath10k!cal-pci-0000:00:00.0.bin: firmware_loading_store: map pages failed
[   14.890000] ath10k_pci 0000:00:00.0: otp stream is empty, using board.bin contents
[   15.920000] ath10k_pci 0000:00:00.0: qca988x hw2.0 (0x4100016c, 0x043222ff) fw 10.2.4.45 api 4 htt 2.1 wmi 5 cal otp max_sta 128
[   15.930000] ath10k_pci 0000:00:00.0: debug 0 debugfs 1 tracing 0 dfs 1 testmode 1
[   28.350000] ath10k_pci 0000:00:00.0: otp stream is empty, using board.bin contents

# Tried install method:
opkg install kmod-ath10k
wifi detect >> /etc/config/wireless

Download firmware from: http://www.candelatech.com/ath10k-10.1.php

# Openwrt wiki:
https://wiki.openwrt.org/toh/netgear/netgear_r6100

**Comment by nbd168** [comment]
This has nothing to do with mt76...
