### ISSUE TITLE
USB device cause throughput drop

### ISSUE THREAD

**Issue by psyborg55** [openwrt/mt76#70]
running trunk image i've noticed when USB device is enabled throughput drops 25-30% in both directions.

without USB device plugged in (or with disabled USB power) iperf reports ~85Mbps, as soon as the USB device is activated this drops to ~65Mbps

device xiaomi mini, r49946

**Comment by nbd168** [comment]
Please try the latest version, it should be fixed now.

**Comment by iancd** [comment]
@psyborg55 Could you report back if this is fixed in the trunk build and if so consider closing the issue?
