### ISSUE TITLE
Please add support for wlan 2,4 and 5 GHz leds on Asus rt-ax-53u

### ISSUE THREAD

**Issue by lukjod** [openwrt/mt76#705]
Please add suport for both wlan leds controlled by thos gpios below
```
GPIO PIN MAP in ASUS RT-AX53U:
WLAN2G -- MT7905 GPIO18
WLAN5G -- MT7905 GPIO26
```

_Originally posted by @DragonBluep in https://github.com/openwrt/openwrt/issues/11068#issuecomment-1288178843_

**Comment by Djfe** [comment]
pls close this issue. This support was added already added to the MT76 driver and will be activated by the following PR in openwrt for the actual device :)
It might be activated for all devices using the driver (generally), that's still being discussed.
https://github.com/openwrt/openwrt/pull/11601#discussion_r1059124071

**Comment by Doldak** [comment]
not fixed!
