### ISSUE TITLE
 Belkin RT3200/MT7622: Latest snapshot abysmal downspeed on 2.4GHz

### ISSUE THREAD

**Issue by RSpliet** [openwrt/mt76#757]
With the latest snapshot, download speeds on 2.4GHz don't exceed 6Mbps despite the Wifi link being for a much higher bandwidth. Upload also isn't great with ~65Mbps, but less problematic. Reverting to snapshot OpenWrt SNAPSHOT r22124-bfa5e4e4eb / LuCI Master git-23.039.28596-41e9b8d ("mcp85xx: Switch TP-Link TL-WDR4900 v1 to DSA") resolves the issue.

Router:
* Belkin RT3200
* OpenWrt SNAPSHOT r22190-12a3c863d2 ("bmips: loader-lzma: drop unused RAMSIZE parameter")
* Kernel 5.15.96
* WPA2
* 2.4GHz: .n, 40MHz (both with and without forced 40MHz mode)
* Tried WED enabled and disabled, no difference

Client
* Windows 11
* Intel AX200

**Comment by nbd168** [comment]
Fixed in r22191-f6a7ce2501ec
