### ISSUE TITLE
Preamble settings mixed up?

### ISSUE THREAD

**Issue by neheb** [openwrt/mt76#78]
From reading the code, OFDM uses a long preamble while CCK uses a short one. Should this not be the opposite?

**Comment by nbd168** [comment]
OFDM always uses a short preamble, for CCK it is optional, so the CCK rates have a short preamble flag.

**Comment by neheb** [comment]
You say that but the witi on 5ghz uses a long preamble on all connections for me. Can be verified with: iw dev wlan0 station dump

**Comment by neheb** [comment]
Oh I see what happens. When just a single device decides to use a long preamble (iPhone) all the others follow suit.
