### ISSUE TITLE
RX rate reverts to 6mbit/20MHz periodically or semi-permanently

### ISSUE THREAD

**Issue by VA1DER** [openwrt/mt76#796]
Devices: mt7915, mt7986
Modes: 2.4GHz & 5GHz AC and AX modes
Symptoms: RX speeds in either AP or STA modes will periodically (once per minute) revert to 6mbit/20MHz, regardless of SNR or signal strength.

Typically once every 60 seconds the RX speed will revert to 6mbit/20MHz, stay there for 4 or 5 seconds, then increase back to an expected rate.  In some instances the RX rate will remain at 6mbit/20MHz for extended periods, only briefly increasing to expected rates.

![6mbit-1](https://github.com/openwrt/mt76/assets/6966600/27803048-ae74-4c8f-acb8-3e233da6907f)

This happens on both 2.4GHz and 5GHz connections on affected devices.  So far affected devices are mt7915 and mt7986. 

Originally believed to be associated with openwrt/openwrt#13003 but now appears separate.

**Comment by danpawlik** [comment]
Is it not something related to the WNM? What wpad version (basic/full) you have installed?

**Comment by jww-cw** [comment]
I am only seeing this on some devices on the 2.4GHz MT7622

Samsung A33 5G  has the issue.

Xiaomi Mi Lite 5G does not have the issue.

@VA1DER have you tested with multiple 2.4GHZ devices.

**Comment by fightforlife** [comment]
I just found the same issue. Client is a Xiaomi Poco F1 with latest Lineage os 20. I also have a camera which shows the same behaviour. Dcs6100

Model GL-MT300N-V2
Architecture MediaTek MT7628AN ver:1 eco:2
Target Platform ramips/mt76x8
Firmware Version OpenWrt SNAPSHOT r23589-08607da37c / LuCI Master git-23.158.78004-23a246e
Kernel Version 5.15.120

**Comment by gca31** [comment]
I've got the same issue with a BPI-R3 (mt7986, snapshot r23589-08607da37c) configured as AP and various STA clients (netgear WAX206 with mt7622 and mt7975 running OEM firmware, apple devices, windows devices and ESP32 devices) whatever the Wifi (N,AC,AX).  I've got also a variant with TX at 6mbits/20MHz and another variant with RX at 24mbits/20MHz
All pictures captured from the BPI-R3 AP

RX rate at 6Mbits/20MHz - Wifi N
<img width="337" alt="Capture d’écran 2023-07-23 à 16 00 12" src="https://github.com/openwrt/mt76/assets/81360260/e15747cf-0be7-4ac9-a36f-2ccde9986313">

TX rate at 6Mbits/20MHz - Wifi N
<img width="337" alt="Capture d’écran 2023-07-23 à 15 59 58" src="https://github.com/openwrt/mt76/assets/81360260/47708d15-5dbd-4e4f-8d4d-e8222199c488">

Variant RX rate at 24Mbits/20MHz - Wifi AC
<img width="337" alt="Capture d’écran 2023-07-23 à 15 59 48" src="https://github.com/openwrt/mt76/assets/81360260/9625dacf-aff4-4d7c-bef7-55e9e88f377f">

RX rate at 6Mbits/20MHz - Wifi AX
<img width="337" alt="Capture d’écran 2023-07-23 à 15 59 36" src="https://github.com/openwrt/mt76/assets/81360260/e11c8e26-4427-4797-9d79-d5231c68ce45">

**Comment by fightforlife** [comment]
I think this might be power saving initiated by the clients. 
I can reproduce it by putting my Android phone into standby. Lock and leave for 15secs.
When I unlock it again and open the browser the speed goes up again.

**Comment by lukasz1992** [comment]
Yes, it is power saving and not the issue.

Device and driver can only report what was received - if device wishes to transmit frames at lowest possible speed, you see 6mbit.

**Comment by gca31** [comment]
Ok, thanks for the explanation.
Therefore, if we all agree on this, does it make sense this issue has to be closed ? @VA1DER ?

**Comment by Djfe** [comment]
This is also likely what happens, when you don't run your wireless adapter on "maximum performance" on windows.
I noticed decreased performance to an AP (not openwrt), but this setting lowers power consumption (great for battery but at the cost of performance)
On Android you can't set this manually.
I agree, this is a non issue and intentional behaviour.

**Comment by VA1DER** [comment]
Consensus is intended behaviour.  Clogins.
