### ISSUE TITLE
Add implicit/explicit beamforming support for mt7628

### ISSUE THREAD

**Issue by yamazaki15** [openwrt/mt76#805]
Hi,

Would it be possible to integrate beamforming support (implicit or explicit) to MT7628 chip driver?

Thanks

**Comment by lukasz1992** [comment]
No - as this is WiFi 4 device

**Comment by yamazaki15** [comment]
Beamforming is supported since 802.11n (Some atheros 802.11n chips support beamforming & CSI). Is there any way to extract CSI data from Mediatek chips?

**Comment by ryderlee1110** [comment]
only mt7915 and further devices can do CSI.

**Comment by ygtcnclk** [comment]
Hi @ryderlee1110 ! Can you explain how can i extract csi through Xiaomi AX3200 (with MT7915) because i couldn't find any way of doing it.
