### ISSUE TITLE
HT/VHT modes have weak range

### ISSUE THREAD

**Issue by psyborg55** [openwrt/mt76#84]
connecting to mt7612e wifi from greater distance makes the connection very slow in N/AC modes.
with tx rate HT40 30 Mbps that sometimes change to 54, 60 or 90 Mbps max speed was 2.5/1.5 Mbps.

changing to legacy mode with the notebook in the same place and tx rate 18 Mbps the speed was 8.5/4.5 Mbps

throughput measured with speedtest.net, in N/AC modes it had 6 ms larger ping response time.

additional test: 

measure performance in N mode with HT40 and AC mode with HT40 & VHT80

in both N and AC modes HT40 TX = ~50Mbps RX = ~80Mbps
in AC mode VHT80 TX = ~70Mbps RX = ~120Mbps

the card supports abgn standards only (HT40) but still in VHT80 mode had better performance

update: checked again now i got same throughput in HT40 or VHT80. not sure what caused it first time.

update: 2.4GHz N mode has also weaker range than legacy with same chip/driver

**Comment by nbd168** [comment]
Current versions should behave much better now, there were some rate control related bugs

**Comment by psyborg55** [comment]
unfortunately, still the same. i have notebook connecting from 5m distance behind thin wall and glass doors, syncs at 30-78Mbps (12-36Mbps in legacy mode) but no data passes through. page loading starts and hangs. in the original test the notebook was placed 2 floors below the router and signal was going through 2 ~50cm walls

**Comment by psyborg55** [comment]
this bug may be related to txpower issue: https://github.com/openwrt/mt76/issues/16
