### ISSUE TITLE
bw40/bw80 delta not working

### ISSUE THREAD

**Issue by psyborg55** [openwrt/mt76#89]
setting up gain delta for bw40/bw80 in eeprom makes no gain difference if bw operation is changed between 20/40/80 MHz. i've even tried lowering output power, still same gain level for all bandwidths.

**Comment by nbd168** [comment]
Please try the latest version, it should work now.

**Comment by psyborg55** [comment]
no hardware in condition to try. also no interest to repair it or buy another.
