### ISSUE TITLE
Support MT7976

### ISSUE THREAD

**Issue by peterwillcn** [openwrt/mt76#924]
Support MT7976

![image](https://github.com/user-attachments/assets/3996859e-5941-4532-8410-de54505684b5)

**Comment by nachalni** [comment]
It's already supported with the appropriate SoC(MT7981/MT7986) by the MT7915 driver ?

**Comment by peterwillcn** [comment]
@nachalni  MT7915 driver  work for MT7986, Thanks!

**Comment by peterwillcn** [comment]
@nbd168 But, the wireless transmission speed cannot reach the MT7976 chip specification speed.
![image](https://github.com/user-attachments/assets/96509694-b51e-4c40-9641-c027c2ca85c7)
