### ISSUE TITLE
[Snapshot] AX3000T no CPU clock management

### ISSUE THREAD

**Issue by erayrafet** [openwrt/mt76#933]
I have the Xiaomi AX3000T and there is no CPU clock management. The CPU directories in /dev do not exist as btop doesn't display clock speeds either. Because of that, the CPU is always hovering at about 60C which is quite hot on the outside as well. Seems like cpufreq isn't enabled.

https://forum.openwrt.org/t/openwrt-support-for-xiaomi-ax3000t/180490/1782?u=erayrafet

https://forum.openwrt.org/t/openwrt-support-for-xiaomi-ax3000t/180490/1783?u=erayrafet

![image](https://github.com/user-attachments/assets/c3fca8c1-e0fa-4cd8-83ed-d7b62f60259e)
![image](https://github.com/user-attachments/assets/fc3df04c-7451-4a32-b08e-a85bc79fbd82)

**Comment by Bartvz** [comment]
This is the driver for the wireless chips so this does not look like the right place to me.

**Comment by erayrafet** [comment]
You're right. I should've checked. I assumed it was geared towards newer Mediatek SoCs.
