### ISSUE TITLE
Mt76 as client cause kernel WARNING 

### ISSUE THREAD

**Issue by sevencheng798** [openwrt/mt76#96]
I am using MT7628 modules, when i try  to use it as client to connect  a AP SSID, then do iperf test, i found cause below issue:
[  434.510254] br-lan: port 2(wlan0) entered forwarding state
[  434.521209] br-lan: port 2(wlan0) entered forwarding state
[  436.520513] br-lan: port 2(wlan0) entered forwarding state
[  436.650511] ------------[ cut here ]------------
[  436.659714] WARNING: CPU: 0 PID: 10 at /home/buildbot/slave-lede-local/ramips_mt7628/build/build_dir/target-mipsel_24kc_musl/linux-ramips_mt7628/mt76-2017-03-17-712b8e8f/mt7603_mac.c:1219 mt7603_mac_work+0xf0/0x284 [mt7603e]()
[  436.699497] Modules linked in: pppoe ppp_async pppox ppp_generic nf_conntrack_ipv6 iptable_nat ipt_REJECT ipt_MASQUERADE xt_time xt_tcpudp xt_state xt_nat xt_multiport xt_mark xt_mac xt_limit xt_conntrack xt_comment xt_TCPMSS xt_REDIRECT xt_LOG xt_CT slhc nf_reject_ipv4 nf_nat_redirect nf_nat_masquerade_ipv4 nf_conntrack_ipv4 nf_nat_ipv4 nf_nat nf_log_ipv4 nf_defrag_ipv6 nf_defrag_ipv4 nf_conntrack_rtcache nf_conntrack iptable_mangle iptable_filter ip_tables crc_ccitt mt76x2e mt7603e ledtrig_usbport mt76 mac80211 cfg80211 compat ip6t_REJECT nf_reject_ipv6 nf_log_ipv6 nf_log_common ip6table_mangle ip6table_filter ip6_tables x_tables leds_gpio ohci_platform ohci_hcd ehci_platform ehci_hcd gpio_button_hotplug usbcore nls_base usb_common
[  436.828671] CPU: 0 PID: 10 Comm: kworker/u2:2 Not tainted 4.4.56 #0
[  436.841096] Workqueue: phy0 mt7603_mac_work [mt7603e]
[  436.851098] Stack : 81803410 818a5c18 00000088 8004ae04 8182eac4 803b0e23 8034c334 0000000a
          803745a4 818b3d64 803b0000 80048d70 00000088 8004ae04 80351834 803b0000
          00000003 818b3d64 803b0000 80038d80 00000088 818b3d9c 000000d5 00000000
          00000001 00000000 80c951dc 81b8ea00 81b8e900 30796870 00000000 00000000
          00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000
          ...
[  436.921546] Call Trace:
[  436.926388] [<800148e0>] show_stack+0x50/0x84
[  436.935028] [<800253f4>] warn_slowpath_common+0xa0/0xd0
[  436.945394] [<800254ac>] warn_slowpath_null+0x18/0x24
[  436.955419] [<80c952cc>] mt7603_mac_work+0xf0/0x284 [mt7603e]
[  436.966827] [<80036c98>] process_one_work+0x1f8/0x334
[  436.976845] [<80037aac>] worker_thread+0x2b0/0x404
[  436.986343] [<8003be64>] kthread+0xd8/0xec
[  436.994464] [<80004478>] ret_from_kernel_thread+0x14/0x1c
[  437.005161] 
[  437.008102] ---[ end trace 5f5f4414575f3955 ]---

I have used the lastest version for mt76 driver. and i also test the new release image - https://downloads.lede-project.org/snapshots/targets/ramips/mt7628/lede-ramips-mt7628-mt7628-squashfs-sysupgrade.bin, it has same problem.
Could someone help me?

**Comment by nbd168** [comment]
Fixed in current versions
