### ISSUE TITLE
Massive Packetloss with 802.11s

### ISSUE THREAD

**Issue by mmalte** [openwrt/mt76#97]
I'm running the Freifunk Aachen Gluon on a DIR-860L B1:
https://images.ffac.rocks/experimental-2017.1/

This Firmware is based on Lede r2993+10-af29b2d

The Client Wifi and IBSS Mesh is working flawless, but when I replace the IBSS Mesh by 802.11s I get massive packetloss on the 5GHz radio.

I'll be happy to provide additional Data, but I'm not sure what might be helpful. @dangowrt suggest filing a report here in https://github.com/freifunk-gluon/gluon/issues/1040#issuecomment-279806765

**Comment by nbd168** [comment]
Should be fixed in the latest version
